python3 - << 'PYEOF'
B = "https://insightful-data-lab.com/2025/"
# (title, date_slug_path) in CURRICULUM order (oldest first), transcribed verbatim
# from the 15 listing pages fetched this turn. Landmine titles use \u escapes.
R = [
 ("The three steps of Bayesian data analysis","11/08/the-three-steps-of-bayesian-data-analysis"),
 ("General Notation for Statistical Inference","11/08/general-notation-for-statistical-inference"),
 ("Bayesian Inference","11/08/bayesian-inference-2"),
 ("Discrete Bayesian Examples \u2013 Genetics and Spell Checking (with \u03b8)","11/08/discrete-bayesian-examples-genetics-and-spell-checking-with-%ce%b8"),
 ("Probability as a Measure of Uncertainty","11/08/probability-as-a-measure-of-uncertainty"),
 ("Example \u2014 Probabilities from Football Point Spreads","11/08/example-probabilities-from-football-point-spreads"),
 ("Example \u2014 Calibration for Record Linkage","11/08/example-calibration-for-record-linkage"),
 ("Some Useful Results from Probability Theory","11/08/some-useful-results-from-probability-theory"),
 ("Computation and Software","11/09/computation-and-software"),
 ("Bayesian Inference in Applied Statistics","11/09/bayesian-inference-in-applied-statistics"),
 ("Estimating a Probability from Binomial Data","11/09/estimating-a-probability-from-binomial-data"),
 ("Posterior as a Compromise Between Data and Prior Information","11/09/posterior-as-a-compromise-between-data-and-prior-information"),
 ("Summarizing Posterior Inference","11/09/summarizing-posterior-inference"),
 ("Informative Prior Distributions","11/09/informative-prior-distributions"),
 ("Normal Distribution with Known Variance","11/09/normal-distribution-with-known-variance"),
 ("Other Standard Single-Parameter Models","11/09/other-standard-single-parameter-models"),
 ("Informative Prior Distribution for Cancer Rates","11/09/informative-prior-distribution-for-cancer-rates"),
 ("Noninformative Prior Distributions","11/09/noninformative-prior-distributions"),
 ("Weakly Informative Prior Distributions","11/09/weakly-informative-prior-distributions"),
 ("Averaging Over Nuisance Parameters","11/09/averaging-over-nuisance-parameters"),
 ("Normal Data with a Noninformative Prior Distribution","11/09/normal-data-with-a-noninformative-prior-distribution"),
 ("Normal Data with a Conjugate Prior Distribution","11/09/normal-data-with-a-conjugate-prior-distribution"),
 ("Multinomial Model for Categorical Data","11/09/multinomial-model-for-categorical-data"),
 ("Multivariate Normal Model with Known Variance","11/09/multivariate-normal-model-with-known-variance"),
 ("Multivariate Normal with Unknown Mean and Variance","11/09/multivariate-normal-with-unknown-mean-and-variance"),
 ("Example: Bayesian analysis of a bioassay experiment (logistic, nonconjugate)","11/09/example-bayesian-analysis-of-a-bioassay-experiment-logistic-nonconjugate"),
 ("Summary of Elementary Modeling and Computation","11/09/summary-of-elementary-modeling-and-computation"),
 ("Normal Approximations to the Posterior Distribution","11/09/normal-approximations-to-the-posterior-distribution"),
 ("Large-Sample Theory","11/09/large-sample-theory"),
 ("Counterexamples to large-sample (asymptotic) Bayesian theorems","11/09/counterexamples-to-large-sample-asymptotic-bayesian-theorems"),
 ("Frequency Evaluations of Bayesian Inferences","11/09/frequency-evaluations-of-bayesian-inferences"),
 ("Bayesian interpretations of other statistical methods","11/09/bayesian-interpretations-of-other-statistical-methods"),
 ("Constructing a Parameterized Prior Distribution","11/09/constructing-a-parameterized-prior-distribution"),
 ("Exchangeability and hierarchical models","11/09/exchangeability-and-hierarchical-models"),
 ("Bayesian analysis of conjugate hierarchical models","11/09/bayesian-analysis-of-conjugate-hierarchical-models"),
 ("Normal model with exchangeable parameters","11/09/normal-model-with-exchangeable-parameters"),
 ("Example: parallel experiments in eight schools","11/09/example-parallel-experiments-in-eight-schools"),
 ("Hierarchical modeling applied to a meta-analysis","11/10/hierarchical-modeling-applied-to-a-meta-analysis"),
 ("Weakly Informative Priors for Variance Parameters","11/10/weakly-informative-priors-for-variance-parameters"),
 ("The Place of Model Checking in Applied Bayesian Statistics","11/10/the-place-of-model-checking-in-applied-bayesian-statistics"),
 ("Do the Inferences from the Model Make Sense?","11/10/do-the-inferences-from-the-model-make-sense"),
 ("Posterior predictive checking","11/10/posterior-predictive-checking"),
 ("Graphical posterior predictive checks","11/10/graphical-posterior-predictive-checks"),
 ("Model checking for the educational testing example","11/10/model-checking-for-the-educational-testing-example"),
 ("Measures of predictive accuracy","11/10/measures-of-predictive-accuracy"),
 ("Model comparison based on predictive performance","11/10/model-comparison-based-on-predictive-performance"),
 ("Model comparison using Bayes factors","11/10/model-comparison-using-bayes-factors"),
 ("Continuous model expansion","11/10/continuous-model-expansion"),
 ("Implicit assumptions and model expansion: an example","11/10/implicit-assumptions-and-model-expansion-an-example"),
 ("Bayesian inference requires a model for data collection","11/11/bayesian-inference-requires-a-model-for-data-collection"),
 ("Data-collection models and ignorability","11/11/data-collection-models-and-ignorability"),
 ("Sample surveys","11/11/sample-surveys"),
 ("Designed experiments","11/11/designed-experiments"),
 ("Sensitivity and the role of randomization","11/11/sensitivity-and-the-role-of-randomization"),
 ("Observational studies","11/11/observational-studies"),
 ("Censoring and truncation","11/11/censoring-and-truncation"),
 ("Bayesian decision theory in di\ufb00erent contexts","11/11/bayesian-decision-theory-in-di%ef%ac%80erent-contexts"),
 ("Using regression predictions: survey incentives","11/11/using-regression-predictions-survey-incentives"),
 ("Multistage decision making: medical screening","11/11/multistage-decision-making-medical-screening"),
 ("Hierarchical decision analysis for home radon","11/11/hierarchical-decision-analysis-for-home-radon"),
 ("Personal vs. institutional decision analysis","11/11/personal-vs-institutional-decision-analysis"),
 ("Numerical integration","11/11/numerical-integration"),
 ("Distributional approximations","11/11/distributional-approximations"),
 ("Direct simulation and rejection sampling","11/11/direct-simulation-and-rejection-sampling"),
 ("Importance sampling","11/11/importance-sampling"),
 ("How many simulation draws are needed?","11/11/how-many-simulation-draws-are-needed"),
 ("Computing environments","11/11/computing-environments"),
 ("Debugging Bayesian computing","11/11/debugging-bayesian-computing"),
 ("Gibbs sampler","11/12/gibbs-sampler"),
 ("Metropolis and Metropolis-Hastings algorithms","11/12/metropolis-and-metropolis-hastings-algorithms"),
 ("Using Gibbs and Metropolis as building blocks","11/12/using-gibbs-and-metropolis-as-building-blocks"),
 ("Inference and assessing convergence","11/12/inference-and-assessing-convergence"),
 ("E\ufb00ective number of simulation draws","11/12/e%ef%ac%80ective-number-of-simulation-draws"),
 ("Example: hierarchical normal model","11/12/example-hierarchical-normal-model"),
 ("E\ufb03cient Gibbs samplers","11/21/e%ef%ac%83cient-gibbs-samplers"),
 ("E\ufb03cient Metropolis jumping rules","11/21/e%ef%ac%83cient-metropolis-jumping-rules"),
 ("Further extensions to Gibbs and Metropolis","11/21/further-extensions-to-gibbs-and-metropolis"),
 ("Hamiltonian Monte Carlo","11/22/hamiltonian-monte-carlo"),
 ("Hamiltonian Monte Carlo for a hierarchical model","11/22/hamiltonian-monte-carlo-for-a-hierarchical-model"),
 ("Stan: developing a computing environment","11/22/stan-developing-a-computing-environment"),
 ("Finding posterior modes","11/22/finding-posterior-modes"),
 ("Boundary-avoiding priors for modal summaries","11/22/boundary-avoiding-priors-for-modal-summaries"),
 ("Normal and related mixture approximations","11/22/normal-and-related-mixture-approximations"),
 ("Finding marginal posterior modes using EM","11/22/finding-marginal-posterior-modes-using-em"),
 ("Conditional and marginal posterior approximations","11/22/conditional-and-marginal-posterior-approximations"),
 ("Example: hierarchical normal model (continued)","11/22/example-hierarchical-normal-model-2"),
 ("Variational inference","11/22/variational-inference"),
 ("Expectation propagation","11/23/expectation-propagation"),
 ("Other approximations","11/23/other-approximations"),
 ("Unknown normalizing factors","11/23/unknown-normalizing-factors"),
 ("Conditional modeling","11/23/conditional-modeling"),
 ("Bayesian analysis of classical regression","11/23/bayesian-analysis-of-classical-regression"),
 ("Regression for causal inference: incumbency and voting","11/23/regression-for-causal-inference-incumbency-and-voting"),
 ("Goals of regression analysis","11/23/goals-of-regression-analysis"),
 ("Assembling the matrix of explanatory variables","11/23/assembling-the-matrix-of-explanatory-variables"),
 ("Regularization and dimension reduction","11/23/regularization-and-dimension-reduction"),
 ("Unequal variances and correlations","11/23/unequal-variances-and-correlations"),
 ("Including numerical prior information","11/24/including-numerical-prior-information"),
 ("Regression coe\ufb03cients exchangeable in batches","11/24/regression-coe%ef%ac%83cients-exchangeable-in-batches"),
 ("Example: forecasting U.S. presidential elections","11/24/example-forecasting-u-s-presidential-elections"),
 ("Interpreting a normal prior distribution as extra data","11/24/interpreting-a-normal-prior-distribution-as-extra-data"),
 ("Varying intercepts and slopes","11/24/varying-intercepts-and-slopes"),
 ("Computation: batching and transformation","12/06/computation-batching-and-transformation"),
 ("Analysis of variance and the batching of coe\ufb03cients","12/06/analysis-of-variance-and-the-batching-of-coe%ef%ac%83cients"),
 ("Hierarchical models for batches of variance components","12/06/hierarchical-models-for-batches-of-variance-components"),
 ("Standard generalized linear model likelihoods","12/06/standard-generalized-linear-model-likelihoods"),
 ("Working with generalized linear models","12/06/working-with-generalized-linear-models"),
 ("Weakly informative priors for logistic regression","12/06/weakly-informative-priors-for-logistic-regression"),
 ("Overdispersed Poisson regression for police stops","12/06/overdispersed-poisson-regression-for-police-stops"),
 ("State-level opinons from national polls","12/06/state-level-opinons-from-national-polls"),
 ("Models for multivariate and multinomial responses","12/06/models-for-multivariate-and-multinomial-responses"),
 ("Loglinear models for multivariate discrete data","12/06/loglinear-models-for-multivariate-discrete-data"),
 ("Aspects of robustness","12/07/aspects-of-robustness"),
 ("Overdispersed versions of standard models","12/07/overdispersed-versions-of-standard-models"),
 ("Posterior inference and computation","12/07/posterior-inference-and-computation"),
 ("Robust inference for the eight schools","12/07/robust-inference-for-the-eight-schools"),
 ("Robust regression using t-distributed errors","12/07/robust-regression-using-t-distributed-errors"),
 ("Notation","12/07/notation"),
 ("Multiple imputation","12/07/multiple-imputation"),
 ("Missing data in the multivariate normal and t models","12/07/missing-data-in-the-multivariate-normal-and-t-models"),
 ("Example: multiple imputation for a series of polls","12/07/example-multiple-imputation-for-a-series-of-polls"),
 ("Missing values with counted data","12/09/missing-values-with-counted-data"),
 ("Example: an opinion poll in Slovenia","12/09/example-an-opinion-poll-in-slovenia"),
 ("Example: serial dilution assay","12/09/example-serial-dilution-assay"),
 ("Example: population toxicokinetics","12/09/example-population-toxicokinetics"),
 ("Splines and weighted sums of basis functions","12/09/splines-and-weighted-sums-of-basis-functions"),
 ("Basis selection and shrinkage of coe\ufb03cients","12/09/basis-selection-and-shrinkage-of-coe%ef%ac%83cients"),
 ("Non-normal models and regression surfaces","12/09/non-normal-models-and-regression-surfaces"),
 ("Gaussian process regression","12/09/gaussian-process-regression"),
 ("Example: birthdays and birthdates","12/09/example-birthdays-and-birthdates"),
 ("Latent Gaussian process models","12/09/latent-gaussian-process-models"),
 ("Functional data analysis","12/09/functional-data-analysis"),
 ("Density estimation and regression","12/09/density-estimation-and-regression"),
 ("Setting up and interpreting mixture models","12/09/setting-up-and-interpreting-mixture-models"),
 ("Example: reaction times and schizophrenia","12/09/example-reaction-times-and-schizophrenia"),
 ("Label switching and posterior computation","12/09/label-switching-and-posterior-computation"),
 ("Unspecified number of mixture components","12/09/unspecified-number-of-mixture-components"),
 ("Mixture models for classification and regression","12/09/mixture-models-for-classification-and-regression"),
 ("Bayesian histograms","12/13/bayesian-histograms"),
 ("Dirichlet process prior distributions","12/13/dirichlet-process-prior-distributions"),
 ("Dirichlet process mixtures","12/13/dirichlet-process-mixtures"),
 ("Beyond density estimation","12/13/beyond-density-estimation"),
 ("Hierarchical dependence","12/13/hierarchical-dependence"),
 ("Density regression","12/13/density-regression"),
]
counts = [10,9,8,5,7,10,12,7,12,10,8,7,7,11,9,12]
keys = ["bayes_idea","single_param","multiparam","asymptotics","hierarchical",
        "checking","collection_decision","simulation","mcmc","approximation",
        "regression","hier_regression","glm","robust_missing","gp_basis","nonparametric"]
assert len(R) == 144, f"rows={len(R)}"
assert sum(counts) == 144
titles = [t for t, _ in R]
assert len(set(titles)) == 144, "duplicate titles remain"
# landmine assertions (verbatim-from-source checks)
assert sum('\ufb03' in t for t in titles) == 5, "ffi count"
assert sum('\ufb00' in t for t in titles) == 2, "ff count"
assert sum('\u03b8' in t for t in titles) == 1 and sum('\u2013' in t for t in titles) == 1
assert sum('\u2014' in t for t in titles) == 2
assert any('opinons' in t for t in titles), "source typo preserved"
assert titles[85] == "Example: hierarchical normal model (continued)" and R[85][1].endswith("-2")
assert titles[73] == "Example: hierarchical normal model"
stages = [k for k, c in zip(keys, counts) for _ in range(c)]
with open("bda_inventory.tsv", "w", encoding="utf-8") as f:
    f.write("title\turl\tstage\n")
    for (t, p), s in zip(R, stages):
        f.write(f"{t}\t{B}{p}/\t{s}\n")
print("bda_inventory.tsv frozen: 144 rows, all assertions passed")
from collections import Counter
print("per-stage:", dict(Counter(stages)))
print("first:", titles[0], "| last:", titles[-1])
print("landmines: ffi=5 ff=2 theta=1 endash=1 emdash=2 opinons=yes dup-resolved=yes")
PYEOF
