# codecov used to be able to find this anywhere, now we have to manually
# tell it where to look
---
comment: false

codecov:
  notify:
    require_ci_to_pass: false

coverage:
  status:
    patch:
      default:
        target: 50%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
    project:
      default: false
      library:
        target: 50%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        paths:
          - '!lib/.*/tests/.*'
      tests:
        target: auto
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        paths:
          - 'lib/.*/tests/.*'
