# For a single document, --- is optional and has no effect on parsing but can improve clarity and consistency.

# This file contains globs for automatically adding labels based on changed files,
# for use with https://github.com/actions/labeler.

######################################################################
## CI
######################################################################

# "CI: Run wheels":
# - changed-files:
#   - any-glob-to-any-file: ['.github/workflows/wheels.yml']

"build/ci":
- changed-files:
  - any-glob-to-any-file:
    - .binder/*
    - .circleci/*
    - .devcontainer/**/*
    - .github/**/*
    - .spin/*
    - docker/**/*

build:templates:
- changed-files:
  - any-glob-to-any-file:
    - scikitplot/**/*.tp

build:meson:
- changed-files:
  - any-glob-to-any-file:
    - pyproject.toml
    - meson.build
    - meson.options
    - scikitplot/**/meson.build
    - setup.cfg

release:
- changed-files:
  - any-glob-to-any-file:
    - .github/workflows/wheels.yml
    - .github/workflows/publish_to_pypi.yml
    - docs/source/devel/maintainers*

######################################################################
## Documentation
######################################################################

DX:
- changed-files:
  - any-glob-to-any-file:
    - docs/source/devel/**/*

documentation:
- changed-files:
  - any-glob-to-any-file:
    # Add 'Documentation' label to any changes within 'docs' folder or any subfolders
    # Add 'Documentation' label to any file changes within 'docs' folder
    - docs/**/*
    - CITATION*
    - COPYING
    - LICENSE
    - LICENSE.txt
    - LICENSE.rst
    - LICENSES/*
    # Add 'Documentation' label to any change to .md files within the entire repository
    # - '**/*.md'
    # Add 'Documentation' label to any change to .rst files within the entire repository
    # - '**/*.rst'
  - all-globs-to-any-file:
    - '!CHANGES.rst'
    - '!docs/changes/*'

"doc:examples":
- changed-files:
  - any-glob-to-any-file:
    - 'galleries/**/*'

######################################################################
## Language
######################################################################

lang:c/c++:
- changed-files:
  - any-glob-to-any-file:
    - scikitplot/**/*.c
    - scikitplot/**/*.c.in
    - scikitplot/**/*.c.old
    - scikitplot/**/*.h
    - scikitplot/**/*.h.in
    - scikitplot/**/*.cpp
    - scikitplot/**/*.cc
    - scikitplot/**/*.cxx
    - scikitplot/**/*.hpp

lang:fortran:
- changed-files:
  - any-glob-to-any-file:
    - scikitplot/**/*.f
    - scikitplot/**/*.f.src
    - scikitplot/**/*.F
    - scikitplot/**/*.f90
    - scikitplot/**/*.pyf

lang:cython:
- changed-files:
  - any-glob-to-any-file:
    - scikitplot/**/*.pyx*
    - scikitplot/**/*.pxd*
    - scikitplot/**/*.pxi*
    - scikitplot/**/*.pyi*
    - scikitplot/**/_generate_pyx.py

######################################################################
## Modules separated
######################################################################

# config:
# - changed-files:
#   - any-glob-to-any-file:
#     - '**/config/**/*'
#     - scikitplot/extern/configobj/**/*

# "scikitplot/sp_logging":
# - changed-files:
#   - any-glob-to-any-file:
#     - scikitplot/sp_logging/**/*

######################################################################
## Testing
######################################################################

tests:
- changed-files:
  - any-glob-to-any-file:
    - scikitplot/tests/**/*
    - '**/conftest.py'
    - conftest.py
    - codecov.yml
    - tox.ini
    - .flake8
    - .mypy.ini
    - .pre-commit-config.yaml
    - .pre-commit-hooks.yaml
    - .ruff.toml

installation:
- changed-files:
  - any-glob-to-any-file:
    - docs/source/install/*
    - MANIFEST.in
    - pyproject.toml
    - setup.cfg
    - setup.py

######################################################################
## dev-automation
######################################################################

# dev-automation:
# - changed-files:
#   - any-glob-to-any-file:
#     - .github/**/*
#     - .github/ISSUE_TEMPLATE/**
#     - .github/workflows/stalebot.
#     - .github/workflows/open_actions.yml
#     - .github/workflows/update_astropy_iers_data_pin.*
#     - .devcontainer/**/*
#     - .pre-commit-config.yaml
#     - .ruff.toml

######################################################################
## Topics
######################################################################

# "topic: sphinx extension":
# - changed-files:
#   - any-glob-to-any-file:
#     - 'scikitplot/sphinxext/**/*'

# "backend: agg":
# - changed-files:
#   - any-glob-to-any-file:
#     - 'lib/matplotlib/backends/backend_agg.py*'

# "GUI: tk":
# - changed-files:
#   - any-glob-to-any-file:
#     - 'src/_tkagg.cpp'
#     - 'src/_tkmini.h'

# "topic: axes":
# - changed-files:
#   - any-glob-to-any-file:
#     # Note, axes.py is not included here because it contains many plotting
#     # methods, for which changes would not be considered on topic.
#     - 'lib/matplotlib/axes/_base.py*'
