"scikitplot/_api":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/_api/**/*"

"scikitplot/_build_utils":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/_build_utils/**/*"

"scikitplot/_cli":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/_cli/**/*"

"scikitplot/_compat":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/_compat/**/*"

"scikitplot/_docstrings":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/_docstrings/**/*"

"scikitplot/_factory_api":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/_factory_api/**/*"

"scikitplot/_lib":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/_lib/**/*"

"scikitplot/_testing":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/_testing/**/*"

"scikitplot/_typing":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/_typing/**/*"

"scikitplot/_utils":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/_utils/**/*"

"scikitplot/annoy":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/annoy/**/*"

"scikitplot/api":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/api/**/*"

"scikitplot/cexperimental":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/cexperimental/**/*"

"scikitplot/cexternals":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/cexternals/**/*"

"scikitplot/cexternals/_astropy":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/cexternals/_astropy/**/*"

"scikitplot/cexternals/_f2py":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/cexternals/_f2py/**/*"

"scikitplot/config":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/config/**/*"

"scikitplot/decile":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/decile/**/*"

"scikitplot/experimental":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/experimental/**/*"

"scikitplot/experimental/_clv":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/experimental/_clv/**/*"

"scikitplot/externals":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/externals/**/*"

"scikitplot/externals/_probscale":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/externals/_probscale/**/*"

"scikitplot/externals/_seaborn":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/externals/_seaborn/**/*"

"scikitplot/externals/_sphinxext":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/externals/_sphinxext/**/*"

"scikitplot/externals/_tweedie":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/externals/_tweedie/**/*"

"scikitplot/impute":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/impute/**/*"

"scikitplot/misc":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/misc/**/*"

"scikitplot/nc":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/nc/**/*"

"scikitplot/preprocessing":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/preprocessing/**/*"

"scikitplot/seaborn":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/seaborn/**/*"

"scikitplot/stats":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/stats/**/*"

"scikitplot/utils":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/utils/**/*"

"scikitplot/visualkeras":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/visualkeras.py"
