"scikitplot/_api":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/_api/**/*"

"scikitplot/api":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/api/**/*"

"scikitplot/_astropy":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/_astropy/**/*"

"scikitplot/_build_utils":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/_build_utils/**/*"

"scikitplot/_clv":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/_clv/**/*"

"scikitplot/_compat":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/_compat/**/*"

"scikitplot/experimental":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/experimental/**/*"

"scikitplot/externals":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/externals/**/*"

"scikitplot/_factory_api":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/_factory_api/**/*"

"scikitplot/kds":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/kds/**/*"

"scikitplot/misc":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/misc/**/*"

"scikitplot/modelplotpy":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/modelplotpy/**/*"

"scikitplot/preprocessing":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/preprocessing/**/*"

"scikitplot/probscale":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/probscale/**/*"

"scikitplot/_seaborn":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/_seaborn/**/*"

"scikitplot/sphinxext":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/sphinxext.py"

"scikitplot/stats":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/stats/**/*"

"scikitplot/typing":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/typing/**/*"

"scikitplot/_testing":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/_testing/**/*"

"scikitplot/_tweedie":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/_tweedie/**/*"

"scikitplot/_utils":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/_utils/**/*"

"scikitplot/utils":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/utils/**/*"

"scikitplot/visualkeras":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/visualkeras.py"

"scikitplot/_lib":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/_lib/**/*"
