"scikitplot/_api":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/_api/**/*"

"scikitplot/api":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/api/**/*"

"scikitplot/_build_utils":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/_build_utils/**/*"

"scikitplot/_compat":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/_compat/**/*"

"scikitplot/cexperimental":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/cexperimental/**/*"

"scikitplot/cexternals":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/cexternals/**/*"

"scikitplot/cexternals/_astropy":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/cexternals/_astropy/**/*"

"scikitplot/cexternals/_f2py":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/cexternals/_f2py/**/*"

"scikitplot/experimental":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/experimental/**/*"

"scikitplot/experimental/_clv":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/experimental/_clv/**/*"

"scikitplot/externals":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/externals/**/*"

"scikitplot/externals/_probscale":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/externals/_probscale/**/*"

"scikitplot/externals/_seaborn":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/externals/_seaborn/**/*"

"scikitplot/externals/_sphinxext":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/externals/_sphinxext/**/*"

"scikitplot/externals/_tweedie":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/externals/_tweedie/**/*"

"scikitplot/_factory_api":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/_factory_api/**/*"

"scikitplot/kds":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/kds/**/*"

"scikitplot/misc":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/misc/**/*"

"scikitplot/modelplotpy":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/modelplotpy/**/*"

"scikitplot/preprocessing":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/preprocessing/**/*"

"scikitplot/stats":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/stats/**/*"

"scikitplot/typing":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/typing/**/*"

"scikitplot/_testing":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/_testing/**/*"

"scikitplot/_utils":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/_utils/**/*"

"scikitplot/utils":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/utils/**/*"

"scikitplot/visualkeras":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/visualkeras.py"

"scikitplot/_lib":
- changed-files:
  - any-glob-to-any-file:
    - "scikitplot/_lib/**/*"
