# scikitplot/_externals/_sphinx_ext/_sphinx_ai_learn/_materialize.py
#
# flake8: noqa: D213
#
# Authors: The scikit-plots developers
# SPDX-License-Identifier: BSD-3-Clause

"""Deterministic AI Learn JSON -> RST source materialization.

Canonical Learn content lives in ``*.json`` files under the configured content
root.  Every canonical JSON page owns exactly one sibling ``*.rst`` file with
the same stem.  The RST is derived build source: it is safe to delete and
regenerate, and it is never an authoring authority.

The materializer performs no model calls, network I/O, repository writes outside
the configured content root, or HTML generation.  Sphinx remains responsible
for RST -> builder output.
"""

from __future__ import annotations

import hashlib
import json
import os
import re
import tempfile
from dataclasses import dataclass
from pathlib import Path, PurePosixPath

from ._generation import section_generation_id
from ._registry import detail_sections, topic_sections
from ._schema import (
    CATALOG_CONTRACT,
    FEEDBACK_EVENT_ID_PATTERN,
    ID_PATTERN,
    MAX_REVIEWED_FEEDBACK_EVENTS,
    MAX_SUBJECT_SECTIONS,
    LearnValidationError,
    canonical_bytes,
    validate_catalog,
    validate_subject,
)

RECORD_CONTRACT = "learn.record.v2"
SECTION_CONTRACT = "learn.section.v1"
SECTION_CONTRACT_V2 = "learn.section.v2"
PAGE_CONTRACT = "learn.page.v1"
PROMPT_CONTRACT = "learn.topic-prompt.v1"
SKILL_CONTRACT = "learn.skill.v1"
FEEDBACK_CONTRACT = "learn.generation-feedback.v1"
GENERATED_MARKER = ".. Generated by _sphinx_ai_learn from canonical JSON. DO NOT EDIT."
MAX_JSON_BYTES = 2 * 1024 * 1024
MAX_JSON_FILES = 20_000
MAX_TOTAL_JSON_BYTES = 128 * 1024 * 1024


def json_source_bytes(value):
    """Return the one repository serialization for canonical Learn JSON."""
    return (
        json.dumps(value, ensure_ascii=False, indent=2, sort_keys=True) + "\n"
    ).encode("utf-8")


DIRECTORIES = {
    "topic": "topics",
    "problem": "open-problems",
    "source": "sources",
    "whiteboard": "whiteboards",
    "video": "videos",
    "audio": "audios",
    "document": "documents",
}
LABELS = {
    "topic": "Topics",
    "problem": "Open Problems",
    "source": "Sources",
    "whiteboard": "Whiteboards",
    "video": "Videos",
    "audio": "Audio",
    "document": "Documents",
}

_PAGE_VIEWS = frozenset(
    {
        "root",
        "explorer",
        "media-gallery",
        "record-create",
        "media-create",
        "prompt-library",
        "prompt-create",
        "skill-library",
        "skill-create",
        "user-library",
    }
)
_MEDIA_CREATE_DIRECTIVES = {
    "video": "ai-video-generation",
    "audio": "ai-audio-generation",
    "document": "ai-document-generation",
    "whiteboard": "ai-whiteboard-generation",
}
_CREATION_KINDS = frozenset({"topic", "problem", "source"})
_USER_LIBRARY_MODES = frozenset(
    {"bookmarks", "collections", "want-to-read", "currently-reading", "completed"}
)


def _reject_duplicate_keys(pairs):
    result = {}
    for key, value in pairs:
        if key in result:
            raise ValueError(f"duplicate JSON key: {key}")
        result[key] = value
    return result


def _reject_nonfinite(value):
    raise ValueError(f"non-finite JSON number: {value}")


def _read_json(path: Path):
    if path.is_symlink():
        raise LearnValidationError(
            f"AI Learn: symlink JSON is not allowed: {path.name}",
        )
    size = path.stat().st_size
    if size > MAX_JSON_BYTES:
        raise LearnValidationError(
            f"AI Learn: JSON exceeds {MAX_JSON_BYTES} bytes: {path.name}"
        )
    try:
        return (
            json.loads(
                path.read_text(encoding="utf-8"),
                object_pairs_hook=_reject_duplicate_keys,
                parse_constant=_reject_nonfinite,
            ),
            size,
        )
    except (OSError, UnicodeError, ValueError, RecursionError) as exc:
        raise LearnValidationError(f"AI Learn: invalid JSON: {path.name}") from exc


def _object(value, *, required=(), allowed=(), where="artifact"):
    if not isinstance(value, dict):
        raise LearnValidationError(f"AI Learn: {where} must be an object")
    if set(value) - set(allowed) or set(required) - set(value):
        raise LearnValidationError(
            f"AI Learn: {where} has unexpected or missing fields",
        )
    return value


def _text(value, where, limit=2000, *, empty=False, multiline=False):
    if not isinstance(value, str) or len(value) > limit:
        raise LearnValidationError(f"AI Learn: {where} has invalid text")
    if any(
        (
            ord(char) < 32  # ruff: ignore[magic-value-comparison]
            and not (multiline and char in "\n\t\r")
        )
        or ord(char) == 127  # ruff: ignore[magic-value-comparison]
        for char in value
    ):
        raise LearnValidationError(f"AI Learn: {where} contains control characters")
    value = value.strip()
    if not empty and not value:
        raise LearnValidationError(f"AI Learn: {where} is required")
    return value


def _ids(value, where, limit=256):
    if not isinstance(value, list) or len(value) > limit:
        raise LearnValidationError(f"AI Learn: {where} must be a bounded list")
    result = []
    for item in value:
        if not isinstance(item, str) or not ID_PATTERN.fullmatch(item):
            raise LearnValidationError(
                f"AI Learn: {where} contains an invalid identifier",
            )
        result.append(item)
    if len(result) != len(set(result)):
        raise LearnValidationError(f"AI Learn: {where} contains duplicate identifiers")
    return result


def route_key(subject):
    """Return one immutable folder name from validated ``created_at`` + kind/id."""
    created = subject.get("created_at")
    if not isinstance(created, str) or not re.fullmatch(
        r"\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z", created
    ):
        raise LearnValidationError(
            "AI Learn record requires an immutable UTC created_at",
        )
    stamp = created.replace("-", "").replace(":", "")
    digest = hashlib.sha256(
        (subject["kind"] + ":" + subject["id"]).encode(),
    ).hexdigest()[:16]
    return f"{stamp}-{digest}"


def record_docpath(subject):
    """Return the JSON-root-relative docname (without suffix) for one record."""
    return f"{DIRECTORIES[subject['kind']]}/{route_key(subject)}/index"


def _heading(title, adornment="="):
    escaped = re.sub(r"([\\`*_<>|])", r"\\\1", title)
    return escaped + "\n" + adornment * len(escaped) + "\n"


def page_size(kind):
    """Bound explorer payloads; browser pagination remains presentation-only."""
    if kind == "topic":
        return 24
    if kind == "whiteboard":
        return 6
    return 12


def _heading_with(title, adornment="="):
    """Compatibility-free internal heading helper shared by page renderers."""
    return _heading(title, adornment)


def _rst_text(value):
    """Escape maintainer-authored page prose so it cannot become a directive."""
    value = value.replace("\\", "\\\\")
    value = re.sub(r"([`*_<>|])", r"\\\1", value)
    # A paragraph line beginning with '.. ' can become a directive/comment. Escape
    # the leading period in every line, including after user-supplied newlines.
    return "\n".join(
        ("\\." + line[1:] if line.startswith(".. ") else line)
        for line in value.splitlines()
    )


def _owner_header(source_rel: str, source_digest: str):
    return (
        GENERATED_MARKER
        + "\n"
        + f".. source-json: {source_rel}\n"
        + f".. source-sha256: {source_digest}\n\n"
    )


def _section_directive(subject_id: str, section_id: str, kind: str):
    if kind == "overview":
        return f".. ai-topic-overview:: {subject_id}\n"
    if kind == "prompt-group":
        return f".. ai-topic-prompts:: {subject_id}\n"
    if kind == "skill-group":
        return f".. ai-topic-skills:: {subject_id}\n"
    return f".. ai-topic-section:: {section_id}\n   :topic-id: {subject_id}\n"


_DESIGN_CLASS_RE = re.compile(r"[A-Za-z][A-Za-z0-9_-]{0,63}\Z")
_DOCNAME_RE = re.compile(r"[A-Za-z0-9][A-Za-z0-9_-]*(?:/[A-Za-z0-9][A-Za-z0-9_-]*)*\Z")


def _safe_docname(value, where):
    value = _text(value, where, 200)
    path = PurePosixPath(value)
    if (
        path.is_absolute()
        or ".." in path.parts
        or value.endswith((".rst", ".json"))
        or not _DOCNAME_RE.fullmatch(value)
    ):
        raise LearnValidationError(f"AI Learn: {where} contains an unsafe docname")
    return value


def _responsive_values(value, where, *, minimum, maximum, allow_auto=False):
    """Normalize one-or-four responsive Sphinx-Design values."""
    rows = value if isinstance(value, list) else [value]
    if len(rows) not in {1, 4}:
        raise LearnValidationError(f"AI Learn: {where} must contain one or four values")
    result = []
    for item in rows:
        if allow_auto and item == "auto":
            result.append("auto")
            continue
        if (
            isinstance(item, bool)
            or not isinstance(item, int)
            or not minimum <= item <= maximum
        ):
            raise LearnValidationError(
                f"AI Learn: {where} contains an invalid responsive value"
            )
        result.append(str(item))
    return " ".join(result)


def _design_class_list(value, where):
    if isinstance(value, str):
        rows = value.split()
    elif isinstance(value, list):
        rows = value
    else:
        raise LearnValidationError(f"AI Learn: {where} must be a class name or list")
    if not rows or len(rows) > 16:  # ruff: ignore[magic-value-comparison]
        raise LearnValidationError(f"AI Learn: {where} must be a bounded class list")
    result = []
    for row in rows:
        if not isinstance(row, str) or not _DESIGN_CLASS_RE.fullmatch(row):
            raise LearnValidationError(
                f"AI Learn: {where} contains an invalid class name"
            )
        result.append(row)
    return " ".join(result)


def _validate_design_grid(value, where):  # ruff: ignore[too-many-branches]
    """Validate an RST-free Sphinx-Design grid projection for one page."""
    _object(
        value,
        required=("columns", "items"),
        allowed=(
            "columns",
            "gutter",
            "margin",
            "padding",
            "outline",
            "reverse",
            "class_container",
            "class_row",
            "items",
        ),
        where=where,
    )
    grid = {
        "columns": _responsive_values(
            value["columns"], f"{where}.columns", minimum=1, maximum=12, allow_auto=True
        )
    }
    for name in ("gutter", "padding"):
        if name in value:
            grid[name] = _responsive_values(
                value[name], f"{where}.{name}", minimum=0, maximum=5
            )
    if "margin" in value:
        grid["margin"] = _responsive_values(
            value["margin"], f"{where}.margin", minimum=0, maximum=5, allow_auto=True
        )
    for name in ("outline", "reverse"):
        if name in value:
            if not isinstance(value[name], bool):
                raise LearnValidationError(f"AI Learn: {where}.{name} must be boolean")
            grid[name] = value[name]
    for name in ("class_container", "class_row"):
        if name in value:
            grid[name] = _design_class_list(value[name], f"{where}.{name}")
    items = value["items"]
    _len = len(items) > 64  # ruff: ignore[magic-value-comparison]
    if not isinstance(items, list) or not items or _len:
        raise LearnValidationError(
            f"AI Learn: {where}.items must be a non-empty bounded list"
        )
    normalized = []
    for index, raw in enumerate(items):
        item_where = f"{where}.items[{index}]"
        _object(
            raw,
            required=("title", "toctree"),
            allowed=("title", "card", "toctree"),
            where=item_where,
        )
        card_raw = raw.get("card", {})
        _object(
            card_raw,
            allowed=(
                "columns",
                "margin",
                "padding",
                "child_direction",
                "child_align",
                "outline",
                "text_align",
                "shadow",
                "class_item",
                "class_card",
                "class_header",
                "class_body",
            ),
            where=f"{item_where}.card",
        )
        card = {}
        if "columns" in card_raw:
            card["columns"] = _responsive_values(
                card_raw["columns"],
                f"{item_where}.card.columns",
                minimum=1,
                maximum=12,
                allow_auto=True,
            )
        if "padding" in card_raw:
            card["padding"] = _responsive_values(
                card_raw["padding"], f"{item_where}.card.padding", minimum=0, maximum=5
            )
        if "margin" in card_raw:
            card["margin"] = _responsive_values(
                card_raw["margin"],
                f"{item_where}.card.margin",
                minimum=0,
                maximum=5,
                allow_auto=True,
            )
        if "child_direction" in card_raw:
            if card_raw["child_direction"] not in {"column", "row"}:
                raise LearnValidationError(
                    f"AI Learn: {item_where}.card.child_direction is unsupported"
                )
            card["child_direction"] = card_raw["child_direction"]
        if "child_align" in card_raw:
            if card_raw["child_align"] not in {
                "start",
                "end",
                "center",
                "justify",
                "spaced",
            }:
                raise LearnValidationError(
                    f"AI Learn: {item_where}.card.child_align is unsupported"
                )
            card["child_align"] = card_raw["child_align"]
        if "text_align" in card_raw:
            if card_raw["text_align"] not in {"left", "right", "center", "justify"}:
                raise LearnValidationError(
                    f"AI Learn: {item_where}.card.text_align is unsupported"
                )
            card["text_align"] = card_raw["text_align"]
        if "shadow" in card_raw:
            if card_raw["shadow"] not in {"none", "sm", "md", "lg"}:
                raise LearnValidationError(
                    f"AI Learn: {item_where}.card.shadow is unsupported"
                )
            card["shadow"] = card_raw["shadow"]
        if "outline" in card_raw:
            if not isinstance(card_raw["outline"], bool):
                raise LearnValidationError(
                    f"AI Learn: {item_where}.card.outline must be boolean"
                )
            card["outline"] = card_raw["outline"]
        for name in ("class_item", "class_card", "class_header", "class_body"):
            if name in card_raw:
                card[name] = _design_class_list(
                    card_raw[name], f"{item_where}.card.{name}"
                )
        tree_raw = raw["toctree"]
        _object(
            tree_raw,
            required=("children",),
            allowed=("children", "maxdepth", "hidden", "titlesonly", "caption"),
            where=f"{item_where}.toctree",
        )
        children = tree_raw["children"]
        _len = len(children) > 64  # ruff: ignore[magic-value-comparison]
        if not isinstance(children, list) or not children or _len:
            raise LearnValidationError(
                f"AI Learn: {item_where}.toctree.children must be a non-empty bounded list"
            )
        docs = [
            _safe_docname(child, f"{item_where}.toctree.children") for child in children
        ]
        if len(docs) != len(set(docs)):
            raise LearnValidationError(
                f"AI Learn: {item_where}.toctree.children contains duplicate docnames"
            )
        maxdepth = tree_raw.get("maxdepth", 2)
        _maxdepth = 0 <= maxdepth <= 10  # ruff: ignore[magic-value-comparison]
        if isinstance(maxdepth, bool) or not isinstance(maxdepth, int) or not _maxdepth:
            raise LearnValidationError(
                f"AI Learn: {item_where}.toctree.maxdepth must be an integer from 0 to 10"
            )
        toctree = {"children": docs, "maxdepth": maxdepth}
        for name in ("hidden", "titlesonly"):
            if name in tree_raw:
                if not isinstance(tree_raw[name], bool):
                    raise LearnValidationError(
                        f"AI Learn: {item_where}.toctree.{name} must be boolean"
                    )
                toctree[name] = tree_raw[name]
        if "caption" in tree_raw:
            toctree["caption"] = _text(
                tree_raw["caption"], f"{item_where}.toctree.caption", 200
            )
        normalized.append(
            {
                "title": _text(raw["title"], f"{item_where}.title", 200),
                "card": card,
                "toctree": toctree,
            }
        )
    grid["items"] = normalized
    return grid


def _render_design_grid(grid):
    """Render one validated design grid without accepting raw RST from JSON."""
    lines = [f".. grid:: {grid['columns']}"]
    option_names = ("gutter", "margin", "padding", "class_container", "class_row")
    option_rst = {"class_container": "class-container", "class_row": "class-row"}
    lines.extend(
        f"   :{option_rst.get(name, name.replace('_', '-'))}: {grid[name]}"
        for name in option_names
        if name in grid
    )
    lines.extend(f"   :{name}:" for name in ("outline", "reverse") if grid.get(name))
    lines.append("")
    card_option_rst = {
        "child_direction": "child-direction",
        "child_align": "child-align",
        "text_align": "text-align",
        "class_item": "class-item",
        "class_card": "class-card",
        "class_header": "class-header",
        "class_body": "class-body",
    }
    for item in grid["items"]:
        lines.append("   .. grid-item-card::")
        lines.extend(
            f"      :{card_option_rst.get(name, name.replace('_', '-'))}: {item['card'][name]}"
            for name in (
                "columns",
                "margin",
                "padding",
                "child_direction",
                "child_align",
                "text_align",
                "shadow",
                "class_item",
                "class_card",
                "class_header",
                "class_body",
            )
            if name in item["card"]
        )
        if item["card"].get("outline"):
            lines.append("      :outline:")
        lines.extend(["", f"      **{_rst_text(item['title'])}**", "      ^^^"])
        tree = item["toctree"]
        lines.append("      .. toctree::")
        lines.append(f"         :maxdepth: {tree['maxdepth']}")
        if tree.get("hidden"):
            lines.append("         :hidden:")
        if tree.get("titlesonly"):
            lines.append("         :titlesonly:")
        if tree.get("caption"):
            lines.append(f"         :caption: {_rst_text(tree['caption'])}")
        lines.append("")
        lines.extend(f"         {child}" for child in tree["children"])
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _media_directive(subject):
    kind = subject["kind"]
    if kind == "audio":
        return f".. ai-audio-player:: {subject['id']}\n\n.. ai-media-actions:: {subject['id']}\n"
    if kind == "document":
        return f".. ai-document-viewer:: {subject['id']}\n\n.. ai-media-actions:: {subject['id']}\n"
    if kind == "whiteboard":
        return f".. ai-whiteboard-gallery:: {subject['id']}\n\n.. ai-media-actions:: {subject['id']}\n"
    if kind == "video":
        media = subject.get("media", {})
        youtube_id = media.get("youtube_id")
        if youtube_id:
            return (
                f".. youtube:: {youtube_id}\n"
                "   :width: 100%\n"
                "   :aspect: 16:9\n"
                "   :privacy_mode:\n\n"
                f".. ai-media-actions:: {subject['id']}\n"
            )
        return (
            "No playable video is attached to this record yet.\n\n"
            + f".. ai-media-actions:: {subject['id']}\n"
        )
    return ""


def _validate_page(  # ruff: ignore[too-many-branches]
    data,
    rel,
):
    _object(
        data,
        required=("contract", "view", "title"),
        allowed=(
            "contract",
            "view",
            "title",
            "description",
            "kind",
            "mode",
            "children",
            "create_label",
            "explorer_header",
            "design_grid",
            "hide_secondary_sidebar",
        ),
        where=str(rel),
    )
    if data["contract"] != PAGE_CONTRACT or data["view"] not in _PAGE_VIEWS:
        raise LearnValidationError(f"AI Learn: unsupported page contract/view at {rel}")
    result = {
        "contract": PAGE_CONTRACT,
        "view": data["view"],
        "title": _text(data["title"], f"{rel}.title", 200),
        "description": _text(
            data.get("description", ""),
            f"{rel}.description",
            4000,
            empty=True,
            multiline=True,
        ),
        "hide_secondary_sidebar": data.get("hide_secondary_sidebar", True),
    }
    if not isinstance(result["hide_secondary_sidebar"], bool):
        raise LearnValidationError(
            f"AI Learn: {rel}.hide_secondary_sidebar must be boolean"
        )
    if "kind" in data:
        result["kind"] = _text(data["kind"], f"{rel}.kind", 64)
    if "mode" in data:
        result["mode"] = _text(data["mode"], f"{rel}.mode", 64)
    if "create_label" in data:
        result["create_label"] = _text(data["create_label"], f"{rel}.create_label", 100)
    if "explorer_header" in data:
        header = data["explorer_header"]
        _object(
            header,
            required=("kicker", "title"),
            allowed=("kicker", "title"),
            where=f"{rel}.explorer_header",
        )
        result["explorer_header"] = {
            "kicker": _text(header["kicker"], f"{rel}.explorer_header.kicker", 100),
            "title": _text(header["title"], f"{rel}.explorer_header.title", 200),
        }
    if "children" in data:
        _len = len(data["children"]) > 256  # ruff: ignore[magic-value-comparison]
        if not isinstance(data["children"], list) or _len:
            raise LearnValidationError(
                f"AI Learn: {rel}.children must be a bounded list",
            )
        children = [
            _safe_docname(child, f"{rel}.children") for child in data["children"]
        ]
        if len(children) != len(set(children)):
            raise LearnValidationError(
                f"AI Learn: {rel}.children contains duplicate docnames"
            )
        result["children"] = children
    if "design_grid" in data:
        result["design_grid"] = _validate_design_grid(
            data["design_grid"], f"{rel}.design_grid"
        )
    view = result["view"]
    if result.get("explorer_header") and view not in {
        "explorer",
        "media-gallery",
        "prompt-library",
        "skill-library",
    }:
        raise LearnValidationError(
            f"AI Learn: {rel}.explorer_header is unsupported for {view} pages"
        )
    if view == "root" and result.get("design_grid"):
        layout_children = [
            child
            for item in result["design_grid"]["items"]
            for child in item["toctree"]["children"]
        ]
        if layout_children != result.get("children", []):
            raise LearnValidationError(
                f"AI Learn: {rel}.design_grid must cover root children exactly once and in order"
            )
    if view == "root" and rel != Path("index.json"):
        raise LearnValidationError("AI Learn: the root page must be index.json")
    if view in {"explorer", "media-gallery"}:
        kind = result.get("kind")
        if kind not in DIRECTORIES:
            raise LearnValidationError(f"AI Learn: {rel}.kind is unsupported")
        expected = Path(DIRECTORIES[kind]) / "index.json"
        if rel != expected:
            raise LearnValidationError(f"AI Learn: {rel} must be {expected.as_posix()}")
    if view == "record-create":
        kind = result.get("kind")
        if kind not in _CREATION_KINDS:
            raise LearnValidationError(f"AI Learn: {rel}.kind is unsupported")
        expected = Path(DIRECTORIES[kind]) / "new.json"
        if rel != expected:
            raise LearnValidationError(f"AI Learn: {rel} must be {expected.as_posix()}")
    if view == "media-create":
        kind = result.get("kind")
        if kind not in _MEDIA_CREATE_DIRECTIVES:
            raise LearnValidationError(f"AI Learn: {rel}.kind is unsupported")
        expected = Path(DIRECTORIES[kind]) / "new.json"
        if rel != expected:
            raise LearnValidationError(f"AI Learn: {rel} must be {expected.as_posix()}")
    if view == "prompt-library" and rel != Path("topic-prompts/index.json"):
        raise LearnValidationError(
            "AI Learn: prompt library must be topic-prompts/index.json",
        )
    if view == "prompt-create" and rel != Path("topic-prompts/new.json"):
        raise LearnValidationError(
            "AI Learn: prompt creation must be topic-prompts/new.json",
        )
    if view == "skill-library" and rel != Path("skills/index.json"):
        raise LearnValidationError("AI Learn: skill library must be skills/index.json")
    if view == "skill-create" and rel != Path("skills/new.json"):
        raise LearnValidationError("AI Learn: skill creation must be skills/new.json")
    if view == "user-library":
        mode = result.get("mode")
        if mode not in _USER_LIBRARY_MODES:
            raise LearnValidationError(f"AI Learn: {rel}.mode is unsupported")
        expected = {
            "bookmarks": Path("bookmarks/index.json"),
            "collections": Path("collections/index.json"),
            "want-to-read": Path("collections/want-to-read/index.json"),
            "currently-reading": Path("collections/currently-reading/index.json"),
            "completed": Path("collections/completed/index.json"),
        }[mode]
        if rel != expected:
            raise LearnValidationError(f"AI Learn: {rel} must be {expected.as_posix()}")
    return result


def _validate_definition(data, rel, *, contract, directory, label, optional=()):
    _object(
        data,
        required=(
            "contract",
            "id",
            "title",
            "author",
            "description",
            "instruction",
            "empty_message",
            "default_enabled",
            "order",
        ),
        allowed=(
            "contract",
            "id",
            "title",
            "author",
            "authors",
            "description",
            "instruction",
            "empty_message",
            "default_enabled",
            "order",
            "hide_secondary_sidebar",
            *optional,
        ),
        where=str(rel),
    )
    if data["contract"] != contract:
        raise LearnValidationError(f"AI Learn: unsupported {label} contract at {rel}")
    definition_id = _text(data["id"], f"{rel}.id", 64)
    expected = Path(directory) / definition_id / "index.json"
    if not ID_PATTERN.fullmatch(definition_id) or rel != expected:
        raise LearnValidationError(
            f"AI Learn: {label} path/id mismatch at {rel}; expected {expected.as_posix()}"
        )
    if not isinstance(data["default_enabled"], bool):
        raise LearnValidationError(f"AI Learn: {rel}.default_enabled must be boolean")
    hide_secondary_sidebar = data.get("hide_secondary_sidebar", True)
    if not isinstance(hide_secondary_sidebar, bool):
        raise LearnValidationError(
            f"AI Learn: {rel}.hide_secondary_sidebar must be boolean"
        )
    if (
        isinstance(data["order"], bool)
        or not isinstance(data["order"], int)
        or not 0 <= data["order"] <= 10_000  # ruff: ignore[magic-value-comparison]
    ):
        raise LearnValidationError(
            f"AI Learn: {rel}.order must be an integer from 0 to 10000"
        )
    author = _text(data["author"], f"{rel}.author", 200)
    raw_authors = data.get("authors", [author])
    _len = len(raw_authors) > 32  # ruff: ignore[magic-value-comparison]
    if not isinstance(raw_authors, list) or not raw_authors or _len:
        raise LearnValidationError(
            f"AI Learn: {rel}.authors must be a bounded non-empty list"
        )
    authors = [_text(item, f"{rel}.authors", 80) for item in raw_authors]
    if len({item.casefold() for item in authors}) != len(authors):
        raise LearnValidationError(
            f"AI Learn: {rel}.authors contains duplicate display names"
        )
    if author.casefold() not in {item.casefold() for item in authors}:
        raise LearnValidationError(f"AI Learn: {rel}.author must appear in authors")
    return {
        "id": definition_id,
        "title": _text(data["title"], f"{rel}.title", 200),
        "author": author,
        "authors": authors,
        "description": _text(data["description"], f"{rel}.description", 2000),
        "instruction": _text(
            data["instruction"], f"{rel}.instruction", 20_000, multiline=True
        ),
        "empty_message": _text(data["empty_message"], f"{rel}.empty_message", 1000),
        "default_enabled": data["default_enabled"],
        "order": data["order"],
        "hide_secondary_sidebar": hide_secondary_sidebar,
    }


def _validate_prompt(data, rel):
    return _validate_definition(
        data,
        rel,
        contract=PROMPT_CONTRACT,
        directory="topic-prompts",
        label="topic-prompt",
    )


def _validate_skill(data, rel):
    result = _validate_definition(
        data,
        rel,
        contract=SKILL_CONTRACT,
        directory="skills",
        label="skill",
        optional=("domains", "related"),
    )
    result["domains"] = _ids(data.get("domains", []), f"{rel}.domains", 20)
    result["related"] = _ids(data.get("related", []), f"{rel}.related", 100)
    return result


def _validate_feedback_sidecar(data, rel):
    """Validate one immutable reviewed generation-feedback sidecar."""
    _object(
        data,
        required=("contract", "record_id", "section_id", "generation_id", "feedback"),
        allowed=("contract", "record_id", "section_id", "generation_id", "feedback"),
        where=str(rel),
    )
    if data["contract"] != FEEDBACK_CONTRACT:
        raise LearnValidationError(f"AI Learn: unsupported feedback contract at {rel}")
    record_id = _text(data["record_id"], f"{rel}.record_id", 64)
    section_id = _text(data["section_id"], f"{rel}.section_id", 64)
    generation_id = _text(data["generation_id"], f"{rel}.generation_id", 64)
    for value, where in (
        (record_id, f"{rel}.record_id"),
        (section_id, f"{rel}.section_id"),
        (generation_id, f"{rel}.generation_id"),
    ):
        if not ID_PATTERN.fullmatch(value):
            raise LearnValidationError(f"AI Learn: {where} is invalid")
    feedback = data["feedback"]
    _object(
        feedback,
        required=("id", "rating", "contributor"),
        allowed=("id", "rating", "comment", "contributor", "mode"),
        where=f"{rel}.feedback",
    )
    feedback_id = _text(feedback["id"], f"{rel}.feedback.id", 64)
    if not FEEDBACK_EVENT_ID_PATTERN.fullmatch(feedback_id):
        raise LearnValidationError(
            f"AI Learn: {rel}.feedback.id must be an opaque reviewed-feedback event nonce"
        )
    rating = feedback["rating"]
    _rating = -5 <= rating <= 5  # ruff: ignore[magic-value-comparison]
    if isinstance(rating, bool) or not isinstance(rating, int) or not _rating:
        raise LearnValidationError(
            f"AI Learn: {rel}.feedback.rating must be an integer from -5 to 5"
        )
    normalized = {
        "contract": FEEDBACK_CONTRACT,
        "record_id": record_id,
        "section_id": section_id,
        "generation_id": generation_id,
        "feedback": {
            "id": feedback_id,
            "rating": rating,
            "contributor": _text(
                feedback["contributor"], f"{rel}.feedback.contributor", 80
            ),
        },
    }
    if "comment" in feedback:
        normalized["feedback"]["comment"] = _text(
            feedback["comment"],
            f"{rel}.feedback.comment",
            2000,
            empty=True,
            multiline=True,
        )
    if "mode" in feedback:
        mode = _text(feedback["mode"], f"{rel}.feedback.mode", 16)
        if mode not in {"quick", "detailed"}:
            raise LearnValidationError(
                f"AI Learn: {rel}.feedback.mode must be quick or detailed"
            )
        if mode == "quick" and rating not in {-1, 1}:
            raise LearnValidationError(
                f"AI Learn: {rel}.feedback.rating must be -1 or 1 for quick mode"
            )
        normalized["feedback"]["mode"] = mode
    if (
        len(rel.parts) < 5  # ruff: ignore[magic-value-comparison]
        or rel.parts[-4] != "feedback"
        or rel.parts[-3] != section_id
        or rel.parts[-2] != generation_id
        or rel.stem != feedback_id
    ):
        raise LearnValidationError(
            f"AI Learn: feedback sidecar path does not match generation/event ids at {rel}"
        )
    return normalized


def _validate_record_wrapper(data, rel):
    _object(
        data,
        required=("contract", "record", "sections"),
        allowed=(
            "contract",
            "record",
            "sections",
            "add_toctree",
            "hide_secondary_sidebar",
        ),
        where=str(rel),
    )
    if data["contract"] != RECORD_CONTRACT or not isinstance(data["record"], dict):
        raise LearnValidationError(f"AI Learn: unsupported record contract at {rel}")
    record = dict(data["record"])
    if "sections" in record:
        raise LearnValidationError(f"AI Learn: {rel}.record must not inline sections")
    add_toctree = data.get("add_toctree", False)
    if not isinstance(add_toctree, bool):
        raise LearnValidationError(f"AI Learn: {rel}.add_toctree must be boolean")
    hide_secondary_sidebar = data.get("hide_secondary_sidebar", True)
    if not isinstance(hide_secondary_sidebar, bool):
        raise LearnValidationError(
            f"AI Learn: {rel}.hide_secondary_sidebar must be boolean"
        )
    refs = data["sections"]
    if not isinstance(refs, list) or len(refs) > MAX_SUBJECT_SECTIONS:
        raise LearnValidationError(f"AI Learn: {rel}.sections must be a bounded list")
    normalized = []
    ids = set()
    sources = set()
    for index, ref in enumerate(refs):
        where = f"{rel}.sections[{index}]"
        _object(ref, required=("id", "source"), allowed=("id", "source"), where=where)
        section_id = _text(ref["id"], f"{where}.id", 64)
        if not ID_PATTERN.fullmatch(section_id):
            raise LearnValidationError(f"AI Learn: {where}.id is invalid")
        source = _text(ref["source"], f"{where}.source", 200)
        source_path = PurePosixPath(source)
        if (  # ruff: ignore[collapsible-if]
            source_path.is_absolute()
            or ".." in source_path.parts
            or source_path.suffix != ".json"
            or (source_path.name == "index.json" and len(source_path.parts) == 1)
            or any(not ID_PATTERN.fullmatch(part) for part in source_path.parts[:-1])
            or not ID_PATTERN.fullmatch(source_path.stem)
        ):
            # Nested index.json is allowed for structural groups such as
            # topic-prompts/index.json; the record's own index.json is not.
            if not (
                len(source_path.parts) >= 2  # ruff: ignore[magic-value-comparison]
                and source_path.name == "index.json"
                and all(ID_PATTERN.fullmatch(part) for part in source_path.parts[:-1])
            ):
                raise LearnValidationError(f"AI Learn: {where}.source is unsafe")
        if section_id in ids or source in sources:
            raise LearnValidationError(f"AI Learn: {rel}.sections contains duplicates")
        ids.add(section_id)
        sources.add(source)
        normalized.append({"id": section_id, "source": source})

    probe = validate_subject({**record, "sections": []})
    if probe["kind"] == "skill":
        raise LearnValidationError(
            "AI Learn: learn.record.v2 skill records are unsupported; use learn.skill.v1"
        )
    expected = Path(DIRECTORIES[probe["kind"]]) / route_key(probe) / "index.json"
    if rel != expected:
        raise LearnValidationError(
            f"AI Learn: record path mismatch at {rel}; expected {expected.as_posix()}"
        )
    return probe, tuple(normalized), add_toctree, hide_secondary_sidebar


def _validate_section_wrapper(data, rel, *, record_id, section_id):
    _object(
        data,
        required=("contract", "record_id", "section"),
        allowed=("contract", "record_id", "section", "hide_secondary_sidebar"),
        where=str(rel),
    )
    if (
        data["contract"] not in {SECTION_CONTRACT, SECTION_CONTRACT_V2}
        or data["record_id"] != record_id
    ):
        raise LearnValidationError(f"AI Learn: section parent mismatch at {rel}")
    if not isinstance(data["section"], dict):
        raise LearnValidationError(f"AI Learn: {rel}.section must be an object")
    hide_secondary_sidebar = data.get("hide_secondary_sidebar", True)
    if not isinstance(hide_secondary_sidebar, bool):
        raise LearnValidationError(
            f"AI Learn: {rel}.hide_secondary_sidebar must be boolean"
        )
    actual_id = data["section"].get("id")
    if (
        actual_id != section_id
        or not isinstance(actual_id, str)
        or not ID_PATTERN.fullmatch(actual_id)
    ):
        raise LearnValidationError(
            f"AI Learn: section source/id mismatch at {rel}",
        )
    if data["contract"] == SECTION_CONTRACT:
        return dict(data["section"]), hide_secondary_sidebar

    section = data["section"]
    if set(section) != {"id", "title", "active_generation_id", "generations"}:
        raise LearnValidationError(
            f"AI Learn: {rel}.section v2 has unexpected or missing fields"
        )
    active_id = section.get("active_generation_id")
    generations = section.get("generations")
    if not isinstance(generations, list):
        raise LearnValidationError(
            f"AI Learn: {rel}.section.generations must be a list"
        )
    active = next(
        (
            generation
            for generation in generations
            if isinstance(generation, dict) and generation.get("id") == active_id
        ),
        None,
    )
    if active is None:
        raise LearnValidationError(
            f"AI Learn: {rel}.section.active_generation_id is unknown"
        )
    projected = {
        "id": actual_id,
        "title": section.get("title"),
        "body": active.get("body", ""),
        "citations": active.get("citations", []),
        "links": active.get("links", []),
        "contributors": active.get("contributors", []),
        "active_generation_id": active_id,
        "generations": generations,
    }
    if "review" in active:
        projected["review"] = active["review"]
    return projected, hide_secondary_sidebar


@dataclass(frozen=True)
class ContentTree:
    root: Path
    catalog: dict
    routes: dict[str, str]
    prompts: tuple[dict, ...]
    skills: tuple[dict, ...]
    pages: dict[Path, dict]
    records: dict[Path, dict]
    sections: dict[Path, dict]
    feedback_events: dict[Path, dict]
    generation_feedback: dict[tuple[str, str, str], tuple[dict, ...]]
    source_digests: dict[Path, str]
    digest: str
    content_digest: str

    @property
    def dependencies(self):
        """Return global authored-content dependencies.

        Feedback sidecars are intentionally record-scoped.  Treating them as
        global dependencies would make one community vote invalidate every AI
        Learn doctree.  Sphinx integration tracks those event files separately
        by record identity.
        """
        return tuple(
            str(self.root / rel)
            for rel in sorted(set(self.source_digests) - set(self.feedback_events))
        )

    @property
    def feedback_dependencies(self):
        """Return immutable feedback sidecars grouped by owning record id."""
        grouped = {}
        for rel, wrapper in self.feedback_events.items():
            grouped.setdefault(wrapper["record_id"], []).append(str(self.root / rel))
        return {record_id: tuple(sorted(paths)) for record_id, paths in grouped.items()}

    @property
    def feedback_digests(self):
        """Return a stable per-record digest of reviewed feedback events."""
        grouped = {}
        for rel, wrapper in self.feedback_events.items():
            grouped.setdefault(wrapper["record_id"], []).append(rel)
        result = {}
        for record_id, paths in grouped.items():
            digest = hashlib.sha256()
            for rel in sorted(paths):
                digest.update(rel.as_posix().encode())
                digest.update(b"\0")
                digest.update(self.source_digests[rel].encode())
                digest.update(b"\n")
            result[record_id] = digest.hexdigest()
        return result


def skill_subject(skill):
    """Return the normalized catalog projection for one reusable skill definition."""
    return {
        "id": skill["id"],
        "kind": "skill",
        "title": skill["title"],
        "summary": skill["description"],
        "authors": list(skill.get("authors", [skill["author"]])),
        "domains": list(skill.get("domains", [])),
        "related": list(skill.get("related", [])),
        "sections": [
            {
                "id": "instructions",
                "title": "Instructions",
                "body": skill["instruction"],
                "citations": [],
                "links": [],
                "contributors": list(skill.get("authors", [skill["author"]])),
            }
        ],
    }


def validate_interaction_registry(prompts, skills):
    """Validate cross-registry identity/order invariants for reusable interactions."""
    prompt_ids = {prompt["id"] for prompt in prompts}
    prompt_orders = {prompt["order"] for prompt in prompts}
    skill_ids = {skill["id"] for skill in skills}
    skill_orders = {skill["order"] for skill in skills}
    if len(prompt_ids) != len(prompts):
        raise LearnValidationError("AI Learn: duplicate topic-prompt identifier")
    if len(prompt_orders) != len(prompts):
        raise LearnValidationError("AI Learn: duplicate topic-prompt order")
    if len(skill_ids) != len(skills):
        raise LearnValidationError("AI Learn: duplicate skill identifier")
    if len(skill_orders) != len(skills):
        raise LearnValidationError("AI Learn: duplicate skill order")
    if prompt_ids & skill_ids:
        raise LearnValidationError(
            "AI Learn: prompt and skill identifiers must be disjoint",
        )
    reserved = {spec["id"] for spec in topic_sections(prompts=(), skills=())}
    collision = sorted((prompt_ids | skill_ids) & reserved)
    if collision:
        raise LearnValidationError(
            f"AI Learn: interaction identifier collides with structural section: {collision[0]}",
        )


def load_content_tree(  # ruff: ignore[too-many-branches]
    root,
) -> ContentTree:
    """Load and validate one complete canonical JSON tree without mutating files."""
    root = Path(root).absolute()
    if root.is_symlink() or any(parent.is_symlink() for parent in root.parents):
        raise LearnValidationError("AI Learn: content root may not be a symlink")
    if not root.is_dir():
        raise LearnValidationError(f"AI Learn: content root does not exist: {root}")
    paths = sorted(root.rglob("*.json"))
    if len(paths) > MAX_JSON_FILES:
        raise LearnValidationError("AI Learn: too many canonical JSON files")

    raw_by_rel = {}
    source_digests = {}
    total = 0
    for path in paths:
        rel = path.relative_to(root)
        if any(part.startswith(".") for part in rel.parts):
            continue
        data, size = _read_json(path)
        total += size
        if total > MAX_TOTAL_JSON_BYTES:
            raise LearnValidationError(
                "AI Learn: canonical JSON tree exceeds total size limit"
            )
        raw = canonical_bytes(data) + b"\n"
        source_digests[rel] = hashlib.sha256(raw).hexdigest()
        raw_by_rel[rel] = data

    pages = {}
    prompts = []
    skills = []
    record_wrappers = {}
    section_raw = {}
    feedback_events = {}
    for rel, data in raw_by_rel.items():
        contract = data.get("contract") if isinstance(data, dict) else None
        if contract == PAGE_CONTRACT:
            pages[rel] = _validate_page(data, rel)
        elif contract == PROMPT_CONTRACT:
            prompts.append(_validate_prompt(data, rel))
        elif contract == SKILL_CONTRACT:
            skills.append(_validate_skill(data, rel))
        elif contract == RECORD_CONTRACT:
            record_wrappers[rel] = _validate_record_wrapper(data, rel)
        elif contract in {SECTION_CONTRACT, SECTION_CONTRACT_V2}:
            section_raw[rel] = data
        elif contract == FEEDBACK_CONTRACT:
            feedback_events[rel] = _validate_feedback_sidecar(data, rel)
        else:
            raise LearnValidationError(f"AI Learn: unsupported JSON contract at {rel}")

    # Typed page grids may only point at canonical materialized documents.
    # Resolve nested toctree docnames relative to the owning page, matching
    # Sphinx semantics, while keeping layout incapable of reaching handwritten
    # files outside the JSON-owned tree.
    materialized_sources = {
        rel
        for rel, data in raw_by_rel.items()
        if isinstance(data, dict) and data.get("contract") != FEEDBACK_CONTRACT
    }
    for page_rel, page in pages.items():
        for item in page.get("design_grid", {}).get("items", []):
            for child in item["toctree"]["children"]:
                target = page_rel.parent / (child + ".json")
                if target not in materialized_sources:
                    raise LearnValidationError(
                        f"AI Learn: {page_rel}.design_grid references unknown canonical document {child}"
                    )

    prompts.sort(key=lambda item: (item["order"], item["id"]))
    skills.sort(key=lambda item: (item["order"], item["id"]))
    validate_interaction_registry(prompts, skills)
    prompt_ids = {prompt["id"] for prompt in prompts}
    skill_ids = {skill["id"] for skill in skills}

    subjects = []
    records = {}
    sections = {}
    routes = {}
    subject_origins = {}
    section_origins = {}
    subject_ids = set()
    for rel, (
        base,
        refs,
        add_toctree,
        hide_secondary_sidebar,
    ) in record_wrappers.items():
        if base["id"] in subject_ids:
            raise LearnValidationError(f"AI Learn: duplicate record id {base['id']}")
        subject_ids.add(base["id"])
        folder = rel.parent
        loaded = []
        for ref in refs:
            section_id = ref["id"]
            source = PurePosixPath(ref["source"])
            if base["kind"] == "topic":
                expected = (
                    PurePosixPath("topic-prompts/index.json")
                    if section_id == "topic-prompts"
                    else (
                        PurePosixPath("topic-prompts") / f"{section_id}.json"
                        if section_id in prompt_ids
                        else (
                            PurePosixPath("skills/index.json")
                            if section_id == "skills"
                            else (
                                PurePosixPath("skills") / f"{section_id}.json"
                                if section_id in skill_ids
                                else PurePosixPath(f"{section_id}.json")
                            )
                        )
                    )
                )
                if source != expected:
                    raise LearnValidationError(
                        f"AI Learn: topic section {section_id} must use {expected.as_posix()}"
                    )
            else:
                expected = PurePosixPath(f"{section_id}.json")
                if source != expected:
                    raise LearnValidationError(
                        f"AI Learn: {base['kind']} section {section_id} must use {expected.as_posix()}"
                    )
            section_rel = folder.joinpath(*source.parts)
            data = section_raw.pop(section_rel, None)
            if data is None:
                raise LearnValidationError(
                    f"AI Learn: record {base['id']} is missing section JSON {ref['source']}"
                )
            section, section_hide_secondary_sidebar = _validate_section_wrapper(
                data, section_rel, record_id=base["id"], section_id=section_id
            )
            loaded.append(section)
            section_origins[(base["id"], section_id)] = section_rel
            sections[section_rel] = {
                "section": section,
                "hide_secondary_sidebar": section_hide_secondary_sidebar,
            }

        subject = validate_subject({**base, "sections": loaded})
        subjects.append(subject)
        subject_origins[subject["id"]] = rel
        records[rel] = {
            "subject": subject,
            "section_refs": refs,
            "add_toctree": add_toctree,
            "hide_secondary_sidebar": hide_secondary_sidebar,
        }
        for ref in refs:
            section_rel = folder.joinpath(*PurePosixPath(ref["source"]).parts)
            sections[section_rel]["subject"] = subject
        routes[subject["id"]] = record_docpath(subject)

    if section_raw:
        orphan = next(iter(sorted(section_raw)))
        raise LearnValidationError(f"AI Learn: orphan section JSON at {orphan}")

    # Feedback sidecars are metadata events, not authored sections. They must
    # resolve to an immutable accepted generation and live under that record's
    # canonical route. They are intentionally kept out of section JSON so
    # independent votes do not contend on one hot file.
    subjects_by_id = {subject["id"]: subject for subject in subjects}
    generation_feedback_lists = {}
    global_feedback_ids = {}
    for rel, wrapper in sorted(feedback_events.items()):
        record_id = wrapper["record_id"]
        subject = subjects_by_id.get(record_id)
        if subject is None:
            raise LearnValidationError(
                f"AI Learn: feedback sidecar targets unknown record {record_id} at {rel}"
            )
        record_rel = subject_origins[record_id]
        expected = (
            record_rel.parent
            / "feedback"
            / wrapper["section_id"]
            / wrapper["generation_id"]
            / f"{wrapper['feedback']['id']}.json"
        )
        if rel != expected:
            raise LearnValidationError(
                f"AI Learn: feedback sidecar path mismatch at {rel}; expected {expected.as_posix()}"
            )
        section = next(
            (row for row in subject["sections"] if row["id"] == wrapper["section_id"]),
            None,
        )
        if section is None:
            raise LearnValidationError(
                f"AI Learn: feedback sidecar targets unknown section at {rel}"
            )
        generation_id = wrapper["generation_id"]
        if section.get("generations"):
            target = next(
                (row for row in section["generations"] if row["id"] == generation_id),
                None,
            )
            if target is None:
                raise LearnValidationError(
                    f"AI Learn: feedback sidecar targets unknown generation at {rel}"
                )
        elif section_generation_id(subject, section) != generation_id:
            raise LearnValidationError(
                f"AI Learn: feedback sidecar targets unknown projected section generation at {rel}"
            )
        feedback_id = wrapper["feedback"]["id"]
        prior = global_feedback_ids.get(feedback_id)
        identity = (record_id, wrapper["section_id"], generation_id)
        if prior is not None:
            raise LearnValidationError(
                f"AI Learn: duplicate feedback identifier across canonical stores: {feedback_id}"
            )
        global_feedback_ids[feedback_id] = identity
        bucket = generation_feedback_lists.setdefault(identity, [])
        if len(bucket) >= MAX_REVIEWED_FEEDBACK_EVENTS:
            raise LearnValidationError(
                "AI Learn: reviewed feedback event limit exceeded for generation "
                + generation_id
            )
        bucket.append(dict(wrapper["feedback"]))
    generation_feedback = {
        key: tuple(sorted(rows, key=lambda row: row["id"]))
        for key, rows in generation_feedback_lists.items()
    }

    # Two hashes serve different authorities. ``digest`` covers every canonical
    # JSON input, including append-only community feedback sidecars, so Sphinx
    # invalidation observes score/event changes. ``content_digest`` excludes
    # feedback-only metadata: a +1/-1 event must not invalidate unrelated
    # authored drafts or make evidence reviews stale merely because community
    # feedback arrived elsewhere in the tree.
    tree_hash = hashlib.sha256()
    content_hash = hashlib.sha256()
    feedback_paths = set(feedback_events)
    for rel in sorted(source_digests):
        chunk = rel.as_posix().encode() + b"\0" + source_digests[rel].encode() + b"\n"
        tree_hash.update(chunk)
        if rel not in feedback_paths:
            content_hash.update(chunk)
    digest = tree_hash.hexdigest()
    content_digest = content_hash.hexdigest()
    skill_subjects = [skill_subject(skill) for skill in skills]
    subjects.extend(skill_subjects)
    for skill, subject in zip(skills, skill_subjects):
        skill_rel = Path("skills") / skill["id"] / "index.json"
        subject_origins[subject["id"]] = skill_rel
        routes[skill["id"]] = f"skills/{skill['id']}/index"

    known_subjects = {subject["id"]: subject for subject in subjects}
    graph_errors = []
    for subject in subjects:
        subject_origin = subject_origins.get(subject["id"], Path("<unknown>"))
        graph_errors.extend(
            (
                f"{subject_origin.as_posix()}: subject.related: "
                f"{subject['id']} -> unknown target {target}"
            )
            for target in subject.get("related", ())
            if target not in known_subjects
        )
        for section in subject.get("sections", ()):
            section_origin = section_origins.get(
                (subject["id"], section["id"]), subject_origin
            )
            for citation in section.get("citations", ()):
                target = known_subjects.get(citation["source_id"])
                if target is None:
                    graph_errors.append(
                        f"{section_origin.as_posix()}: section.citations: "
                        f"{subject['id']}#{section['id']} -> unknown source "
                        f"{citation['source_id']}"
                    )
                elif target["kind"] != "source":
                    graph_errors.append(
                        f"{section_origin.as_posix()}: section.citations: "
                        f"{subject['id']}#{section['id']} -> target "
                        f"{citation['source_id']} has kind {target['kind']}, expected source"
                    )
    if graph_errors:
        details = "\n".join(f"  - {message}" for message in graph_errors)
        raise LearnValidationError(
            "AI Learn: canonical graph has invalid references:\n" + details
        )

    catalog = validate_catalog(
        {
            "contract": CATALOG_CONTRACT,
            "revision": "tree-" + content_digest[:16],
            "subjects": subjects,
        }
    )
    if len(routes) != len(catalog["subjects"]):
        raise LearnValidationError("AI Learn: duplicate route or subject identity")

    return ContentTree(
        root=root,
        catalog=catalog,
        routes=routes,
        prompts=tuple(prompts),
        skills=tuple(skills),
        pages=pages,
        records=records,
        sections=sections,
        feedback_events=feedback_events,
        generation_feedback=generation_feedback,
        source_digests=source_digests,
        digest=digest,
        content_digest=content_digest,
    )


def _canonical_definition_json_files(
    definitions, *, contract, directory, validator, label
):
    files = {}
    seen_ids = set()
    seen_orders = set()
    for definition in sorted(
        definitions or (), key=lambda item: (item["order"], item["id"])
    ):
        definition_id = definition["id"]
        order = definition["order"]
        if definition_id in seen_ids or order in seen_orders:
            raise LearnValidationError(f"AI Learn: duplicate {label} id or order")
        seen_ids.add(definition_id)
        seen_orders.add(order)
        payload = {
            "contract": contract,
            "id": definition_id,
            "title": definition["title"],
            "author": definition["author"],
            "authors": list(definition.get("authors", [definition["author"]])),
            "description": definition["description"],
            "instruction": definition["instruction"],
            "empty_message": definition["empty_message"],
            "default_enabled": definition["default_enabled"],
            "order": order,
            "hide_secondary_sidebar": definition.get(
                "hide_secondary_sidebar",
                True,
            ),
        }
        rel = Path(directory) / definition_id / "index.json"
        normalized = validator(payload, rel)
        expected_definition = dict(definition)
        expected_definition.setdefault("hide_secondary_sidebar", True)
        if normalized != {key: expected_definition[key] for key in normalized}:
            raise LearnValidationError(
                f"AI Learn: non-canonical {label} {definition_id}"
            )
        files[rel] = json_source_bytes(payload)
    return files


def canonical_prompt_json_files(prompts):
    """Project normalized reusable prompt definitions to canonical JSON files."""
    return _canonical_definition_json_files(
        prompts,
        contract=PROMPT_CONTRACT,
        directory="topic-prompts",
        validator=_validate_prompt,
        label="topic-prompt",
    )


def canonical_skill_json_files(skills):
    """Project normalized reusable skill definitions to canonical JSON files."""
    files = {}
    seen_ids = set()
    seen_orders = set()
    for skill in sorted(skills or (), key=lambda item: (item["order"], item["id"])):
        skill_id = skill["id"]
        order = skill["order"]
        if skill_id in seen_ids or order in seen_orders:
            raise LearnValidationError("AI Learn: duplicate skill id or order")
        seen_ids.add(skill_id)
        seen_orders.add(order)
        payload = {
            "contract": SKILL_CONTRACT,
            "id": skill_id,
            "title": skill["title"],
            "author": skill["author"],
            "authors": list(skill.get("authors", [skill["author"]])),
            "description": skill["description"],
            "instruction": skill["instruction"],
            "empty_message": skill["empty_message"],
            "default_enabled": skill["default_enabled"],
            "order": order,
            "hide_secondary_sidebar": skill.get("hide_secondary_sidebar", True),
            "domains": list(skill.get("domains", [])),
            "related": list(skill.get("related", [])),
        }
        rel = Path("skills") / skill_id / "index.json"
        normalized = _validate_skill(payload, rel)
        expected_skill = dict(skill)
        expected_skill.setdefault("hide_secondary_sidebar", True)
        expected_skill.setdefault("domains", [])
        expected_skill.setdefault("related", [])
        if normalized != {key: expected_skill[key] for key in normalized}:
            raise LearnValidationError(f"AI Learn: non-canonical skill {skill_id}")
        files[rel] = json_source_bytes(payload)
    return files


def canonical_record_json_files(  # ruff: ignore[too-many-branches]
    subject,
    prompts,
    skills=(),
    *,
    add_toctree=False,
    hide_secondary_sidebar=True,
    section_hide_secondary_sidebar=None,
):
    """
    Project one validated subject into its canonical JSON record subtree.

    This is the single layout authority shared by migration, publication, and
    tests.  It returns content-root-relative JSON paths and canonical UTF-8
    bytes only; RST remains exclusively owned by :func:`materialize`.
    """
    if not isinstance(add_toctree, bool):
        raise LearnValidationError("AI Learn: add_toctree must be boolean")
    if not isinstance(hide_secondary_sidebar, bool):
        raise LearnValidationError(
            "AI Learn: hide_secondary_sidebar must be boolean",
        )
    if section_hide_secondary_sidebar is None:
        section_hide_secondary_sidebar = {}
    if not isinstance(section_hide_secondary_sidebar, dict):
        raise LearnValidationError(
            "AI Learn: section_hide_secondary_sidebar must be a mapping"
        )
    prompt_rows = tuple(prompts or ())
    skill_rows = tuple(skills or ())
    prompt_ids = {prompt["id"] for prompt in prompt_rows}
    skill_ids = {skill["id"] for skill in skill_rows}
    if len(prompt_ids) != len(prompt_rows):
        raise LearnValidationError(
            "AI Learn: duplicate topic-prompt identifier",
        )
    if len(skill_ids) != len(skill_rows):
        raise LearnValidationError(
            "AI Learn: duplicate skill identifier",
        )
    if prompt_ids & skill_ids:
        raise LearnValidationError(
            "AI Learn: prompt and skill identifiers must be disjoint",
        )

    subject = validate_subject(subject)
    specs = _record_specs(subject, prompt_rows, skill_rows)
    spec_ids = {spec["id"] for spec in specs}
    unknown_sidebar_sections = set(section_hide_secondary_sidebar) - spec_ids
    if unknown_sidebar_sections:
        raise LearnValidationError(
            "AI Learn: section_hide_secondary_sidebar contains unknown section ids"
        )
    if any(
        not isinstance(value, bool) for value in section_hide_secondary_sidebar.values()
    ):
        raise LearnValidationError(
            "AI Learn: section_hide_secondary_sidebar values must be boolean",
        )
    content = {section["id"]: section for section in subject.get("sections", [])}
    folder = PurePosixPath(DIRECTORIES[subject["kind"]]) / route_key(subject)
    refs = []
    files = {}

    for spec in specs:
        section_id = spec["id"]
        if subject["kind"] == "topic":
            source = (
                PurePosixPath("topic-prompts/index.json")
                if section_id == "topic-prompts"
                else (
                    PurePosixPath("topic-prompts") / f"{section_id}.json"
                    if section_id in prompt_ids
                    else (
                        PurePosixPath("skills/index.json")
                        if section_id == "skills"
                        else (
                            PurePosixPath("skills") / f"{section_id}.json"
                            if section_id in skill_ids
                            else PurePosixPath(f"{section_id}.json")
                        )
                    )
                )
            )
        else:
            source = PurePosixPath(f"{section_id}.json")
        section = copy_section = content.get(section_id)
        if copy_section is None:
            section = {
                "id": section_id,
                "title": spec["title"],
                "body": "",
                "citations": [],
                "links": [],
            }
        else:
            section = dict(copy_section)
        refs.append({"id": section_id, "source": source.as_posix()})
        if section.get("generations"):
            payload = {
                "contract": SECTION_CONTRACT_V2,
                "record_id": subject["id"],
                "hide_secondary_sidebar": section_hide_secondary_sidebar.get(
                    section_id, True
                ),
                "section": {
                    "id": section_id,
                    "title": section["title"],
                    "active_generation_id": section["active_generation_id"],
                    "generations": section["generations"],
                },
            }
        else:
            payload = {
                "contract": SECTION_CONTRACT,
                "record_id": subject["id"],
                "hide_secondary_sidebar": section_hide_secondary_sidebar.get(
                    section_id, True
                ),
                "section": section,
            }
        files[Path(folder.joinpath(source))] = json_source_bytes(payload)

    base = {key: value for key, value in subject.items() if key != "sections"}
    index = {
        "contract": RECORD_CONTRACT,
        "record": base,
        "add_toctree": add_toctree,
        "hide_secondary_sidebar": hide_secondary_sidebar,
        "sections": refs,
    }
    files[Path(folder / "index.json")] = json_source_bytes(index)
    return files


def _toctree(children, *, maxdepth=1, hidden=False):
    if not children:
        return ""
    lines = [".. toctree::"]
    if hidden:
        lines.append("   :hidden:")
    lines.extend([f"   :maxdepth: {maxdepth}", ""])
    lines.extend(f"   {child}" for child in children)
    return "\n".join(lines) + "\n"


def _append_page_design(body, page):
    grid = page.get("design_grid")
    if not grid:
        return body
    separator = "" if not body or body.endswith("\n\n") else "\n"
    return body + separator + _render_design_grid(grid)


def _page_body(  # ruff: ignore[too-many-branches, too-many-return-statements]
    page,
    tree: ContentTree,
    rel: Path,
):
    view = page["view"]
    description = page.get("description", "")
    subjects_by_id = {subject["id"]: subject for subject in tree.catalog["subjects"]}
    body = _rst_text(description) + "\n\n" if description else ""
    explorer_header = page.get("explorer_header")
    explorer_header_rst = ""
    if explorer_header:
        explorer_header_rst = (
            ".. ai-index-explorer-header::\n"
            f"   :kicker: {_rst_text(explorer_header['kicker'])}\n"
            f"   :title: {_rst_text(explorer_header['title'])}\n\n"
        )
    if view == "root":
        if page.get("design_grid"):
            return body + _render_design_grid(page["design_grid"])
        return body + _toctree(page.get("children", []), maxdepth=2)
    if view == "explorer":
        kind = page["kind"]
        create_label = page.get("create_label", "")
        if create_label:
            body += f".. container:: learn-index-actions learn-{kind}-index-actions\n\n   :doc:`{_rst_text(create_label)} <new>`\n\n"
        body += explorer_header_rst
        body += f".. ai-topic-explorer:: {kind}\n   :offset: 0\n\n"
        children = ["new"]
        directory = DIRECTORIES[kind]
        children.extend(
            PurePosixPath(route).parent.name + "/index"
            for identity, route in sorted(tree.routes.items())
            if subjects_by_id[identity]["kind"] == kind
        )
        return _append_page_design(body + _toctree(children, hidden=True), page)
    if view == "media-gallery":
        # Keep media indexes simple and reusable: the rich explorer/directives own
        # presentation, while the materializer owns only deterministic structure.
        kind = page["kind"]
        create_label = page.get("create_label", "")
        if create_label:
            body += (
                f".. container:: learn-index-actions learn-{kind}-index-actions\n\n"
                f"   :doc:`{_rst_text(create_label)} <new>`\n\n"
            )
        body += explorer_header_rst
        body += f".. ai-topic-explorer:: {kind}\n   :offset: 0\n\n"
        children = ["new"]
        children.extend(
            PurePosixPath(route).parent.name + "/index"
            for identity, route in sorted(tree.routes.items())
            if subjects_by_id[identity]["kind"] == kind
        )
        return _append_page_design(body + _toctree(children, hidden=True), page)
    if view == "record-create":
        return _append_page_design(
            body + f".. ai-record-generation:: {page['kind']}\n", page
        )
    if view == "media-create":
        return _append_page_design(
            body + f".. {_MEDIA_CREATE_DIRECTIVES[page['kind']]}::\n", page
        )
    if view == "prompt-library":
        children = ["new", *(f"{prompt['id']}/index" for prompt in tree.prompts)]
        create_label = page.get("create_label", "Create a Topic Prompt")
        return _append_page_design(
            body
            + ".. container:: learn-index-actions learn-topic-prompt-index-actions\n\n"
            + f"   :doc:`{_rst_text(create_label)} <new>`\n\n"
            + explorer_header_rst
            + ".. ai-topic-prompt-library::\n\n"
            + _toctree(children, hidden=True),
            page,
        )
    if view == "prompt-create":
        return _append_page_design(
            body + ".. ai-record-generation:: topic-prompt\n", page
        )
    if view == "skill-library":
        children = ["new", *(f"{skill['id']}/index" for skill in tree.skills)]
        create_label = page.get("create_label", "Create a Skill")
        return _append_page_design(
            body
            + ".. container:: learn-index-actions learn-skill-index-actions\n\n"
            + f"   :doc:`{_rst_text(create_label)} <new>`\n\n"
            + explorer_header_rst
            + ".. ai-skill-library::\n\n"
            + _toctree(children, hidden=True),
            page,
        )
    if view == "skill-create":
        return _append_page_design(body + ".. ai-record-generation:: skill\n", page)
    if view == "user-library":
        result = body + f".. ai-topic-user-library:: {page['mode']}\n"
        if page.get("children"):
            result += "\n" + _toctree(page["children"], hidden=True)
        return _append_page_design(result, page)
    raise LearnValidationError(f"AI Learn: unsupported page view at {rel}")


def _secondary_sidebar_metadata(hide_secondary_sidebar):
    """Render one validated page-level secondary-sidebar metadata field."""
    return ":html_theme.sidebar_secondary.remove:\n\n" if hide_secondary_sidebar else ""


def _render_page(page, tree, rel):
    return (
        _secondary_sidebar_metadata(page["hide_secondary_sidebar"])
        + _heading(page["title"])
        + "\n"
        + _page_body(page, tree, rel)
    )


def _render_prompt(prompt):
    return (
        _secondary_sidebar_metadata(prompt["hide_secondary_sidebar"])
        + _heading(prompt["title"])
        + "\n"
        + f".. ai-topic-prompt-detail:: {prompt['id']}\n"
    )


def _render_skill(skill):
    return (
        _secondary_sidebar_metadata(skill["hide_secondary_sidebar"])
        + _heading(skill["title"])
        + "\n"
        + f".. ai-skill-detail:: {skill['id']}\n"
    )


def _record_specs(subject, prompts, skills):
    return (
        topic_sections(subject, prompts=prompts, skills=skills)
        if subject["kind"] == "topic"
        else detail_sections(subject)
    )


def _section_rst_source(ref):
    return PurePosixPath(ref["source"]).with_suffix(".rst").as_posix()


def _render_record(
    subject,
    section_refs,
    *,
    add_toctree,
    hide_secondary_sidebar,
    prompts,
    skills,
):
    specs = {spec["id"]: spec for spec in _record_specs(subject, prompts, skills)}
    prefix = _secondary_sidebar_metadata(hide_secondary_sidebar)
    lines = [
        _heading(subject["title"]),
        f".. ai-topic-page:: {subject['id']}",
        "",
    ]
    media = _media_directive(subject)
    if media:
        lines.extend([media.rstrip(), ""])

    if add_toctree:
        children = [
            PurePosixPath(_section_rst_source(ref)).with_suffix("").as_posix()
            for ref in section_refs
        ]
        lines.append(_toctree(children, maxdepth=2).rstrip())
        rendered = "\n".join(line for line in lines if line is not None).rstrip()
        return prefix + rendered + "\n"

    for ref in section_refs:
        section_id = ref["id"]
        spec = specs.get(section_id)
        if spec is None:
            section = next(
                item for item in subject["sections"] if item["id"] == section_id
            )
            spec = {
                "id": section_id,
                "title": section["title"],
                "level": 2,
                "kind": "text",
            }
        adornment = (
            "-"  # lint
            if spec.get("level", 2) == 2  # ruff: ignore[magic-value-comparison]
            else "~"
        )
        lines.extend(
            [
                f".. _learn-{subject['id']}-{section_id}:",
                "",
                _heading(spec["title"], adornment).rstrip(),
                f".. include:: {_section_rst_source(ref)}",
                "   :start-after: .. ai-learn-fragment-start",
                "",
            ]
        )
    rendered = "\n".join(line for line in lines if line is not None).rstrip()
    return prefix + rendered + "\n"


def _render_section(
    subject,
    section,
    *,
    add_toctree,
    hide_secondary_sidebar,
    prompts,
    skills,
):
    specs = {spec["id"]: spec for spec in _record_specs(subject, prompts, skills)}
    spec = specs.get(section["id"], {"kind": "text", "title": section["title"]})
    title = f"{subject['title']} — {spec.get('title', section['title'])}"
    prefix = "" if add_toctree else ":orphan:\n:no-search:\n\n"
    label = f".. _learn-{subject['id']}-{section['id']}:\n\n" if add_toctree else ""
    return (
        prefix
        + _secondary_sidebar_metadata(hide_secondary_sidebar)
        + _heading(title)
        + "\n"
        + label
        + f".. ai-topic-page:: {subject['id']}\n\n"
        + ".. ai-learn-fragment-start\n\n"
        + _section_directive(subject["id"], section["id"], spec.get("kind", "text"))
    )


def render_materialized(tree: ContentTree):
    """Return ``{relative_rst_path: bytes}`` for the complete canonical tree."""
    files = {}
    prompt_paths = {
        Path("topic-prompts") / prompt["id"] / "index.json": prompt
        for prompt in tree.prompts
    }
    skill_paths = {
        Path("skills") / skill["id"] / "index.json": skill for skill in tree.skills
    }
    for rel, page in tree.pages.items():
        out = rel.with_suffix(".rst")
        body = _render_page(page, tree, rel)
        files[out] = (
            _owner_header(rel.as_posix(), tree.source_digests[rel]) + body
        ).encode()
    for rel, prompt in prompt_paths.items():
        out = rel.with_suffix(".rst")
        body = _render_prompt(prompt)
        files[out] = (
            _owner_header(rel.as_posix(), tree.source_digests[rel]) + body
        ).encode()
    for rel, skill in skill_paths.items():
        out = rel.with_suffix(".rst")
        body = _render_skill(skill)
        files[out] = (
            _owner_header(rel.as_posix(), tree.source_digests[rel]) + body
        ).encode()
    for rel, wrapper in tree.records.items():
        out = rel.with_suffix(".rst")
        body = _render_record(
            wrapper["subject"],
            wrapper["section_refs"],
            add_toctree=wrapper["add_toctree"],
            hide_secondary_sidebar=wrapper["hide_secondary_sidebar"],
            prompts=tree.prompts,
            skills=tree.skills,
        )
        files[out] = (
            _owner_header(rel.as_posix(), tree.source_digests[rel]) + body
        ).encode()
    records_by_subject = {
        record["subject"]["id"]: record for record in tree.records.values()
    }
    for rel, wrapper in tree.sections.items():
        record = records_by_subject[wrapper["subject"]["id"]]
        out = rel.with_suffix(".rst")
        body = _render_section(
            wrapper["subject"],
            wrapper["section"],
            add_toctree=record["add_toctree"],
            hide_secondary_sidebar=wrapper["hide_secondary_sidebar"],
            prompts=tree.prompts,
            skills=tree.skills,
        )
        # In include mode :orphan: must remain the first source metadata field.
        # Ownership comments follow it and are excluded by the compiler sentinel.
        header = _owner_header(rel.as_posix(), tree.source_digests[rel])
        if body.startswith(":orphan:\n"):
            metadata, rest = body.split("\n\n", 1)
            raw = metadata + "\n\n" + header + rest
        else:
            raw = header + body
        files[out] = raw.encode()
    expected_sources = set(tree.source_digests) - set(tree.feedback_events)
    if len(files) != len(expected_sources):
        missing = sorted(
            expected_sources - {path.with_suffix(".json") for path in files},
        )
        raise LearnValidationError(
            f"AI Learn: not every renderable canonical JSON materialized: {missing[:1]}",
        )
    return files


def _safe_target(root: Path, rel: Path):
    if rel.is_absolute() or ".." in rel.parts or rel.suffix != ".rst":
        raise LearnValidationError("AI Learn: unsafe materialized RST path")
    target = root / rel
    for part in (target, *target.parents):
        if part == root.parent:
            break
        if part.is_symlink():
            raise LearnValidationError(
                "AI Learn: symlink RST destinations are not allowed",
            )
    return target


def _is_owned_rst(path: Path):
    try:
        with path.open("r", encoding="utf-8") as stream:
            return any(
                line.rstrip("\n") == GENERATED_MARKER
                for _, line in zip(range(12), stream)
            )
    except (OSError, UnicodeError):
        return False


def materialize(root):
    """Validate JSON, atomically update sibling RST, and prune stale owned RST."""
    tree = load_content_tree(root)
    files = render_materialized(tree)
    root = tree.root

    # Preflight before any mutation. A canonical JSON file may never overwrite a
    # handwritten RST file; extension-owned outputs are disposable by design.
    for rel, raw in files.items():
        target = _safe_target(root, rel)
        if target.exists() and not target.is_file():
            raise LearnValidationError(f"AI Learn: RST target is not a file: {rel}")
        if (
            target.is_file()
            and not _is_owned_rst(target)
            and target.read_bytes() != raw
        ):
            raise LearnValidationError(
                f"AI Learn: refusing to overwrite handwritten RST: {rel}",
            )

    expected = set(files)
    stale = []
    for path in root.rglob("*.rst"):
        rel = path.relative_to(root)
        if rel not in expected and _is_owned_rst(path):
            stale.append(path)

    changed = []
    for rel, raw in files.items():
        target = _safe_target(root, rel)
        target.parent.mkdir(parents=True, exist_ok=True)
        if target.is_file() and target.read_bytes() == raw:
            continue
        fd, temporary = tempfile.mkstemp(
            prefix=".ai-learn-",
            suffix=".rst",
            dir=target.parent,
        )
        try:
            with os.fdopen(fd, "wb") as stream:
                stream.write(raw)
            os.replace(temporary, target)
        finally:
            if os.path.exists(temporary):
                os.unlink(temporary)
        changed.append(rel.as_posix())
    for path in stale:
        path.unlink()
        changed.append(path.relative_to(root).as_posix())
    return tree, tuple(sorted(changed))
