

all:
	@cd bayesian_data_analysis         && python build_bayesian.py
	@cd data_analytics                 && python build_data_analytics.py
	@cd data_preparation_and_analysis  && python build_data_preparation.py
	@cd deep_learning                  && python build_deep_learning.py
	@cd terminology                    && python build_terminology.py
	@cd time_series                    && python build_time_series.py
