name: MesonBuildTest
description: "checkout repo, build, and test scikit-plots"
runs:
  using: composite
  steps:
  - name: Build
    env:
      TERM: xterm-256color
      PKG_CONFIG_PATH: ./.openblas
    shell: 'script -q -e -c "bash --noprofile --norc -eo pipefail {0}"'
    run: |
      set -Eeuo pipefail
      echo "::group::Installing Build Dependencies"
      pip install -r requirements/build_requirements.txt
      echo "::endgroup::"
      echo "::group::Building scikit-plots"
      spin build --clean -- ${MESON_ARGS[@]}
      echo "::endgroup::"

  - name: Meson Log
    if: always()
    shell: bash
    run: |
      set -Eeuo pipefail
      echo "::group::Meson Log"
      cat build/meson-logs/meson-log.txt
      echo "::endgroup::"

  - name: Test
    env:
      TERM: xterm-256color
    shell: 'script -q -e -c "bash --noprofile --norc -eo pipefail {0}"'
    run: |
      set -Eeuo pipefail
      echo "::group::Installing Test Dependencies"
      pip install pytest pytest-xdist hypothesis typing_extensions setuptools
      echo "::endgroup::"
      echo "::group::Test scikit-plots"
      spin test
      echo "::endgroup::"
