# Authors: The scikit-plots developers
# SPDX-License-Identifier: BSD-3-Clause

"""
Ephemeral lifecycle state for provider-generated binary artifacts.

Run 145 keeps the Run 144 metadata-only authority while making storage
pluggable.  ``memory`` remains the single-process compatibility backend;
``redis`` provides one atomic consistency domain for multi-worker / multi-replica
deployments.  Neither backend stores prompt text, generated bytes, archive
paths, provider credentials, or provider request/response bodies.
"""

from __future__ import annotations

import asyncio
import hashlib
import hmac
import json
import secrets
import time
from dataclasses import dataclass
from typing import Any, Mapping

from ._provider_artifact import (
    ProviderArtifactError,
    ProviderArtifactReceipt,
    ProviderArtifactRequest,
)
from ._redis_security import RedisSecurityError, redis_connection_kwargs

PROVIDER_ARTIFACT_LIFECYCLE_CONTRACT = "scikitplot-provider-artifact-lifecycle-v1"
PROVIDER_ARTIFACT_CANCEL_CONTRACT = "scikitplot-provider-artifact-cancel-v1"
PROVIDER_ARTIFACT_CANDIDATE_TTL_SECONDS = 15 * 60
PROVIDER_ARTIFACT_DUPLICATE_WINDOW_SECONDS = 90
PROVIDER_ARTIFACT_FAILURE_TTL_SECONDS = 60
PROVIDER_ARTIFACT_ZIP_RESERVATION_TTL_SECONDS = 30 * 60
PROVIDER_ARTIFACT_MAX_LIFECYCLE_RECORDS = 1024
PROVIDER_ARTIFACT_REDIS_OPERATION_ATTEMPTS = 2
PROVIDER_ARTIFACT_REDIS_WATCH_FAILURE_LIMIT = 3


@dataclass
class _LifecycleRecord:
    lifecycle_id: str
    fingerprint: str
    cancel_token_sha256: str
    generator_id: str
    provider: str
    model: str
    kind: str
    mime_type: str
    prompt_sha256: str
    regeneration_of: str
    status: str
    created_at: int
    expires_at: int
    output_size: int = 0
    output_sha256: str = ""
    task: asyncio.Task | None = None
    reservation_id: str = ""
    reserved_from_status: str = ""
    reservation_deadline: int = 0
    applied_reservation_id: str = ""

    def public_status(self) -> dict[str, object]:
        return {
            "contract": PROVIDER_ARTIFACT_LIFECYCLE_CONTRACT,
            "lifecycle_id": self.lifecycle_id,
            "status": self.status,
            "created_at": self.created_at,
            "expires_at": self.expires_at,
            "regeneration_of": self.regeneration_of or None,
        }


class ProviderArtifactLifecycleRegistry:
    """Bounded process-local metadata-only lifecycle authority."""

    backend = "memory"
    shared = False
    authoritative = True
    consistency_scope = "process_local"

    def manifest(self) -> dict[str, object]:
        return {
            "backend": self.backend,
            "shared": self.shared,
            "authoritative": self.authoritative,
            "consistency_scope": self.consistency_scope,
            "persistence": "ephemeral_process_memory",
        }

    async def initialize(self) -> None:
        return None

    async def close(self) -> None:
        await self.clear()

    def __init__(
        self,
        *,
        candidate_ttl_seconds: int = PROVIDER_ARTIFACT_CANDIDATE_TTL_SECONDS,
        duplicate_window_seconds: int = PROVIDER_ARTIFACT_DUPLICATE_WINDOW_SECONDS,
        max_records: int = PROVIDER_ARTIFACT_MAX_LIFECYCLE_RECORDS,
    ) -> None:
        self._candidate_ttl = max(30, min(int(candidate_ttl_seconds), 24 * 60 * 60))
        self._duplicate_window = max(
            1, min(int(duplicate_window_seconds), self._candidate_ttl)
        )
        self._max_records = max(32, min(int(max_records), 10_000))
        self._records: dict[str, _LifecycleRecord] = {}
        self._lock = asyncio.Lock()

    @staticmethod
    def _fingerprint(request: ProviderArtifactRequest) -> str:
        # Prompt/options are reduced to a digest before anything is retained.
        options_hash = hashlib.sha256(
            json.dumps(
                dict(request.options),
                sort_keys=True,
                separators=(",", ":"),
                ensure_ascii=True,
            ).encode("utf-8")
        ).hexdigest()
        payload = f"{request.generator_id}\n{request.kind}\n{request.mime_type}\n{request.prompt_sha256}\n{options_hash}\n{request.dedupe_key}".encode()
        return hashlib.sha256(payload).hexdigest()

    @staticmethod
    def _cancel_hash(token: str) -> str:
        normalized = str(token or "")
        try:
            payload = normalized.encode("ascii", "strict")
        except UnicodeEncodeError:
            return ""
        return hashlib.sha256(payload).hexdigest() if payload else ""

    def _cleanup_locked(self, now: int) -> None:
        expired: list[str] = []
        for lifecycle_id, record in self._records.items():
            deadline = (
                record.reservation_deadline
                if record.status == "reserved"
                else record.expires_at
            )
            if deadline <= now:
                record.status = "expired"
                if record.task is not None and not record.task.done():
                    record.task.cancel()
                record.task = None
                expired.append(lifecycle_id)
        for lifecycle_id in expired:
            self._records.pop(lifecycle_id, None)
        if len(self._records) <= self._max_records:
            return
        removable = sorted(
            (row for row in self._records.values() if row.status != "generating"),
            key=lambda row: (row.expires_at, row.created_at, row.lifecycle_id),
        )
        for row in removable[: max(0, len(self._records) - self._max_records)]:
            self._records.pop(row.lifecycle_id, None)

    async def clear(self) -> None:
        async with self._lock:
            tasks = [
                row.task
                for row in self._records.values()
                if row.task is not None and not row.task.done()
            ]
            self._records.clear()
        for task in tasks:
            task.cancel()
        if tasks:
            await asyncio.gather(*tasks, return_exceptions=True)

    async def begin(
        self,
        request: ProviderArtifactRequest,
        *,
        provider: str,
        model: str,
    ) -> str:
        now = int(time.time())
        fingerprint = self._fingerprint(request)
        async with self._lock:
            self._cleanup_locked(now)
            parent: _LifecycleRecord | None = None
            if request.regenerate_of:
                parent = self._records.get(request.regenerate_of)
                if (
                    parent is None
                    or parent.expires_at <= now
                    or parent.status not in {"ready", "delivered", "applied"}
                    or parent.generator_id != request.generator_id
                    or parent.provider != str(provider or "")
                    or parent.model != str(model or "")
                    or parent.kind != request.kind
                    or parent.mime_type != request.mime_type
                ):
                    raise ProviderArtifactError(
                        "PROVIDER_ARTIFACT_REGENERATION_INVALID"
                    )
            else:
                for row in self._records.values():
                    if (
                        row.fingerprint == fingerprint
                        and row.status
                        in {"generating", "ready", "delivered", "reserved", "applied"}
                        and now - row.created_at <= self._duplicate_window
                    ):
                        raise ProviderArtifactError("PROVIDER_ARTIFACT_DUPLICATE")
            cancel_hash = self._cancel_hash(request.cancel_token)
            if cancel_hash and any(
                row.cancel_token_sha256
                and hmac.compare_digest(row.cancel_token_sha256, cancel_hash)
                for row in self._records.values()
            ):
                raise ProviderArtifactError("PROVIDER_ARTIFACT_REQUEST_INVALID")
            if len(self._records) >= self._max_records:
                raise ProviderArtifactError("PROVIDER_ARTIFACT_LIFECYCLE_BUSY")
            lifecycle_id = secrets.token_hex(16)
            while lifecycle_id in self._records:
                lifecycle_id = secrets.token_hex(16)
            self._records[lifecycle_id] = _LifecycleRecord(
                lifecycle_id=lifecycle_id,
                fingerprint=fingerprint,
                cancel_token_sha256=cancel_hash,
                generator_id=request.generator_id,
                provider=str(provider or ""),
                model=str(model or ""),
                kind=request.kind,
                mime_type=request.mime_type,
                prompt_sha256=request.prompt_sha256,
                regeneration_of=parent.lifecycle_id if parent is not None else "",
                status="generating",
                created_at=now,
                # A stalled generation cannot reserve duplicate authority forever.
                expires_at=now + self._candidate_ttl,
            )
            self._cleanup_locked(now)
            return lifecycle_id

    async def attach_task(self, lifecycle_id: str, task: asyncio.Task) -> None:
        async with self._lock:
            row = self._records.get(lifecycle_id)
            if row is None or row.status != "generating":
                task.cancel()
                raise ProviderArtifactError("PROVIDER_ARTIFACT_CANCELLED")
            row.task = task

    async def complete(
        self, lifecycle_id: str, receipt: ProviderArtifactReceipt
    ) -> ProviderArtifactReceipt:
        now = int(time.time())
        async with self._lock:
            row = self._records.get(lifecycle_id)
            if row is None or row.status != "generating":
                raise ProviderArtifactError("PROVIDER_ARTIFACT_CANCELLED")
            if (
                receipt.generator_id != row.generator_id
                or receipt.provider != row.provider
                or receipt.model != row.model
                or receipt.kind != row.kind
                or receipt.mime_type != row.mime_type
                or receipt.prompt_sha256 != row.prompt_sha256
            ):
                raise ProviderArtifactError("PROVIDER_ARTIFACT_RECEIPT_INVALID")
            row.status = "ready"
            row.output_size = int(receipt.output_size)
            row.output_sha256 = str(receipt.output_sha256)
            row.expires_at = now + self._candidate_ttl
            row.task = None
            return receipt.with_lifecycle(
                lifecycle_id=row.lifecycle_id,
                expires_at=row.expires_at,
                regeneration_of=row.regeneration_of,
                state="ready",
            )

    async def fail(self, lifecycle_id: str, *, cancelled: bool = False) -> None:
        now = int(time.time())
        async with self._lock:
            row = self._records.get(lifecycle_id)
            if row is None:
                return
            row.status = "cancelled" if cancelled else "failed"
            row.task = None
            row.expires_at = now + PROVIDER_ARTIFACT_FAILURE_TTL_SECONDS

    async def cancel(self, cancel_token: str) -> Mapping[str, object]:
        normalized = str(cancel_token or "").strip().lower()
        _len = len(normalized) != 64  # ruff: ignore[magic-value-comparison]
        if _len or any(ch not in "0123456789abcdef" for ch in normalized):
            raise ProviderArtifactError("PROVIDER_ARTIFACT_CANCEL_INVALID")
        token_hash = self._cancel_hash(normalized)
        if not token_hash:
            raise ProviderArtifactError("PROVIDER_ARTIFACT_CANCEL_INVALID")
        async with self._lock:
            now = int(time.time())
            self._cleanup_locked(now)
            row = next(
                (
                    item
                    for item in self._records.values()
                    if item.cancel_token_sha256
                    and hmac.compare_digest(item.cancel_token_sha256, token_hash)
                ),
                None,
            )
            if row is None:
                raise ProviderArtifactError("PROVIDER_ARTIFACT_CANCEL_INVALID")
            if row.status == "generating":
                row.status = "cancelled"
                row.expires_at = now + PROVIDER_ARTIFACT_FAILURE_TTL_SECONDS
                task = row.task
                row.task = None
                if task is not None and not task.done():
                    task.cancel()
            return row.public_status()

    async def mark_delivered(self, lifecycle_id: str) -> None:
        async with self._lock:
            row = self._records.get(lifecycle_id)
            if row is not None and row.status == "ready":
                row.status = "delivered"

    async def validate_zip_correlation(
        self,
        *,
        lifecycle_id: str,
        output_sha256: str,
        output_size: int,
    ) -> Mapping[str, object]:
        now = int(time.time())
        async with self._lock:
            self._cleanup_locked(now)
            row = self._records.get(str(lifecycle_id or ""))
            if (
                row is None
                or row.status not in {"ready", "delivered"}
                or row.expires_at <= now
                or row.output_sha256 != str(output_sha256 or "").lower()
                or row.output_size != int(output_size)
            ):
                raise ProviderArtifactError("PROVIDER_ARTIFACT_PROVENANCE_INVALID")
            return row.public_status()

    async def reserve_zip_correlations(
        self,
        correlations: tuple[tuple[str, str, int], ...],
    ) -> tuple[str, tuple[str, ...]]:
        """Atomically reserve verified candidate provenance for one ZIP transaction."""
        if not correlations:
            return "", ()
        now = int(time.time())
        lifecycle_ids = tuple(str(row[0] or "") for row in correlations)
        if len(set(lifecycle_ids)) != len(lifecycle_ids):
            raise ProviderArtifactError("PROVIDER_ARTIFACT_PROVENANCE_INVALID")
        reservation_id = secrets.token_hex(16)
        async with self._lock:
            self._cleanup_locked(now)
            rows: list[_LifecycleRecord] = []
            for lifecycle_id, output_sha256, output_size in correlations:
                row = self._records.get(str(lifecycle_id or ""))
                if (
                    row is None
                    or row.status not in {"ready", "delivered"}
                    or row.expires_at <= now
                    or row.output_sha256 != str(output_sha256 or "").lower()
                    or row.output_size != int(output_size)
                ):
                    raise ProviderArtifactError("PROVIDER_ARTIFACT_PROVENANCE_INVALID")
                rows.append(row)
            while any(
                row.reservation_id == reservation_id for row in self._records.values()
            ):
                reservation_id = secrets.token_hex(16)
            for row in rows:
                row.reserved_from_status = row.status
                row.status = "reserved"
                row.reservation_id = reservation_id
                row.reservation_deadline = (
                    now + PROVIDER_ARTIFACT_ZIP_RESERVATION_TTL_SECONDS
                )
            return reservation_id, lifecycle_ids

    async def release_zip_reservation(
        self, lifecycle_ids: tuple[str, ...], reservation_id: str
    ) -> None:
        if not lifecycle_ids or not reservation_id:
            return
        now = int(time.time())
        async with self._lock:
            for lifecycle_id in lifecycle_ids:
                row = self._records.get(lifecycle_id)
                if (
                    row is None
                    or row.status != "reserved"
                    or row.reservation_id != reservation_id
                ):
                    continue
                if row.expires_at <= now:
                    self._records.pop(lifecycle_id, None)
                    continue
                row.status = (
                    row.reserved_from_status
                    if row.reserved_from_status in {"ready", "delivered"}
                    else "delivered"
                )
                row.reservation_id = ""
                row.reserved_from_status = ""
                row.reservation_deadline = 0

    async def mark_applied(
        self, lifecycle_ids: tuple[str, ...], reservation_id: str
    ) -> None:
        if not lifecycle_ids or not reservation_id:
            raise ProviderArtifactError("PROVIDER_ARTIFACT_PROVENANCE_INVALID")
        async with self._lock:
            rows: list[_LifecycleRecord] = []
            for lifecycle_id in lifecycle_ids:
                row = self._records.get(lifecycle_id)
                if (
                    row is None
                    or row.status != "reserved"
                    or row.reservation_id != reservation_id
                ):
                    raise ProviderArtifactError("PROVIDER_ARTIFACT_PROVENANCE_INVALID")
                rows.append(row)
            for row in rows:
                row.status = "applied"
                row.reservation_id = ""
                row.reserved_from_status = ""
                row.reservation_deadline = 0

    async def public_status(self, lifecycle_id: str) -> Mapping[str, object] | None:
        now = int(time.time())
        async with self._lock:
            self._cleanup_locked(now)
            row = self._records.get(str(lifecycle_id or ""))
            return None if row is None else dict(row.public_status())


# Redis lifecycle scripts deliberately operate within one hash slot so a Redis
# Cluster deployment preserves the same atomicity as a single Redis instance.
# Records contain hashes/IDs/timestamps only; prompt text and artifact bytes are
# never arguments to these scripts.
_REDIS_CLEANUP = r"""
local now=tonumber(ARGV[1]); local ids=redis.call('ZRANGEBYSCORE',KEYS[2],'-inf',now)
for _,id in ipairs(ids) do
  local raw=redis.call('HGET',KEYS[1],id)
  if raw then
    local e=cjson.decode(raw)
    if redis.call('HGET',KEYS[3],tostring(e.fingerprint or '')) == id then redis.call('HDEL',KEYS[3],tostring(e.fingerprint or '')) end
    if tostring(e.cancel_token_sha256 or '') ~= '' then redis.call('HDEL',KEYS[4],tostring(e.cancel_token_sha256)) end
  end
  redis.call('HDEL',KEYS[1],id); redis.call('ZREM',KEYS[2],id)
end
return {1,tostring(#ids)}
""".strip()

_REDIS_BEGIN = r"""
local now=tonumber(ARGV[1]); local lifecycle=ARGV[2]; local fingerprint=ARGV[3]; local cancel_hash=ARGV[4]
local generator=ARGV[5]; local provider=ARGV[6]; local model=ARGV[7]; local kind=ARGV[8]; local mime=ARGV[9]
local prompt_sha=ARGV[10]; local regen=ARGV[11]; local expires=tonumber(ARGV[12]); local max_records=tonumber(ARGV[13]); local dup_window=tonumber(ARGV[14])
local expired=redis.call('ZRANGEBYSCORE',KEYS[2],'-inf',now)
for _,id in ipairs(expired) do
  local raw=redis.call('HGET',KEYS[1],id)
  if raw then local e=cjson.decode(raw); if redis.call('HGET',KEYS[3],tostring(e.fingerprint or '')) == id then redis.call('HDEL',KEYS[3],tostring(e.fingerprint or '')) end; if tostring(e.cancel_token_sha256 or '') ~= '' then redis.call('HDEL',KEYS[4],tostring(e.cancel_token_sha256)) end end
  redis.call('HDEL',KEYS[1],id); redis.call('ZREM',KEYS[2],id)
end
-- A transport retry replays the exact same lifecycle id and arguments.  Check
-- that identity before fingerprint duplicate suppression so "response lost
-- after commit" cannot strand the caller behind its own successful BEGIN.
local retry_raw=redis.call('HGET',KEYS[1],lifecycle)
if retry_raw then
  local prior=cjson.decode(retry_raw)
  if prior.status == 'generating' and prior.fingerprint == fingerprint and tostring(prior.cancel_token_sha256 or '') == cancel_hash and prior.generator_id == generator and prior.provider == provider and prior.model == model and prior.kind == kind and prior.mime_type == mime and prior.prompt_sha256 == prompt_sha and tostring(prior.regeneration_of or '') == regen and tonumber(prior.created_at or -1) == now and tonumber(prior.expires_at or -1) == expires then return {1,tostring(prior.regeneration_of or '')} end
  return {0,'COLLISION'}
end
local parent_id=''
if regen ~= '' then
  local praw=redis.call('HGET',KEYS[1],regen); if not praw then return {0,'REGENERATION_INVALID'} end
  local p=cjson.decode(praw)
  if tonumber(p.expires_at or 0) <= now or (p.status ~= 'ready' and p.status ~= 'delivered' and p.status ~= 'applied') or p.generator_id ~= generator or p.provider ~= provider or p.model ~= model or p.kind ~= kind or p.mime_type ~= mime then return {0,'REGENERATION_INVALID'} end
  parent_id=regen
else
  local existing=redis.call('HGET',KEYS[3],fingerprint)
  if existing then
    local eraw=redis.call('HGET',KEYS[1],existing)
    if eraw then
      local e=cjson.decode(eraw)
      if (e.status == 'generating' or e.status == 'ready' or e.status == 'delivered' or e.status == 'reserved' or e.status == 'applied') and now-tonumber(e.created_at or 0) <= dup_window then return {0,'DUPLICATE'} end
    end
    redis.call('HDEL',KEYS[3],fingerprint)
  end
end
if cancel_hash ~= '' and redis.call('HEXISTS',KEYS[4],cancel_hash) == 1 then return {0,'REQUEST_INVALID'} end
if redis.call('HLEN',KEYS[1]) >= max_records then return {0,'BUSY'} end
local e={lifecycle_id=lifecycle,fingerprint=fingerprint,cancel_token_sha256=cancel_hash,generator_id=generator,provider=provider,model=model,kind=kind,mime_type=mime,prompt_sha256=prompt_sha,regeneration_of=parent_id,status='generating',created_at=now,expires_at=expires,output_size=0,output_sha256='',reservation_id='',reserved_from_status='',reservation_deadline=0,applied_reservation_id=''}
redis.call('HSET',KEYS[1],lifecycle,cjson.encode(e)); redis.call('ZADD',KEYS[2],expires,lifecycle); redis.call('HSET',KEYS[3],fingerprint,lifecycle)
if cancel_hash ~= '' then redis.call('HSET',KEYS[4],cancel_hash,lifecycle) end
return {1,parent_id}
""".strip()

_REDIS_COMPLETE = r"""
local id=ARGV[1]; local now=tonumber(ARGV[2]); local expires=tonumber(ARGV[3]); local out_size=tonumber(ARGV[4]); local out_sha=ARGV[5]
local generator=ARGV[6]; local provider=ARGV[7]; local model=ARGV[8]; local kind=ARGV[9]; local mime=ARGV[10]; local prompt_sha=ARGV[11]
local raw=redis.call('HGET',KEYS[1],id); if not raw then return {0,'CANCELLED'} end; local e=cjson.decode(raw)
if e.generator_id ~= generator or e.provider ~= provider or e.model ~= model or e.kind ~= kind or e.mime_type ~= mime or e.prompt_sha256 ~= prompt_sha then return {0,'RECEIPT_INVALID'} end
if e.status ~= 'generating' then
  if (e.status == 'ready' or e.status == 'delivered' or e.status == 'reserved' or e.status == 'applied') and tonumber(e.output_size or -1) == out_size and tostring(e.output_sha256 or '') == out_sha then return {1,cjson.encode(e)} end
  return {0,'CANCELLED'}
end
e.status='ready'; e.output_size=out_size; e.output_sha256=out_sha; e.expires_at=expires; e.reservation_id=''; e.reserved_from_status=''; e.reservation_deadline=0; e.applied_reservation_id=''
redis.call('HSET',KEYS[1],id,cjson.encode(e)); redis.call('ZADD',KEYS[2],expires,id); return {1,cjson.encode(e)}
""".strip()

_REDIS_FAIL = r"""
local id=ARGV[1]; local status=ARGV[2]; local expires=tonumber(ARGV[3]); local raw=redis.call('HGET',KEYS[1],id); if not raw then return {1,'MISSING'} end
local e=cjson.decode(raw); e.status=status; e.expires_at=expires; e.reservation_id=''; e.reserved_from_status=''; e.reservation_deadline=0
redis.call('HSET',KEYS[1],id,cjson.encode(e)); redis.call('ZADD',KEYS[2],expires,id); return {1,'OK'}
""".strip()

_REDIS_CANCEL = r"""
local token=ARGV[1]; local now=tonumber(ARGV[2]); local failure_exp=tonumber(ARGV[3]); local id=redis.call('HGET',KEYS[3],token); if not id then return {0,'INVALID'} end
local raw=redis.call('HGET',KEYS[1],id); if not raw then redis.call('HDEL',KEYS[3],token); return {0,'INVALID'} end
local e=cjson.decode(raw); if e.status == 'generating' then e.status='cancelled'; e.expires_at=failure_exp; redis.call('HSET',KEYS[1],id,cjson.encode(e)); redis.call('ZADD',KEYS[2],failure_exp,id) end
return {1,cjson.encode(e)}
""".strip()

_REDIS_MARK_DELIVERED = r"""
local id=ARGV[1]; local raw=redis.call('HGET',KEYS[1],id); if not raw then return {1,'MISSING'} end; local e=cjson.decode(raw)
if e.status == 'ready' then e.status='delivered'; redis.call('HSET',KEYS[1],id,cjson.encode(e)) end; return {1,'OK'}
""".strip()

_REDIS_GET = r"""
local id=ARGV[1]; local now=tonumber(ARGV[2]); local raw=redis.call('HGET',KEYS[1],id); if not raw then return {0,'NOT_FOUND'} end; local e=cjson.decode(raw)
local deadline=tonumber(e.status == 'reserved' and e.reservation_deadline or e.expires_at or 0)
if deadline <= now then redis.call('HDEL',KEYS[1],id); redis.call('ZREM',KEYS[2],id); if redis.call('HGET',KEYS[3],tostring(e.fingerprint or '')) == id then redis.call('HDEL',KEYS[3],tostring(e.fingerprint or '')) end; if tostring(e.cancel_token_sha256 or '') ~= '' then redis.call('HDEL',KEYS[4],tostring(e.cancel_token_sha256)) end; return {0,'NOT_FOUND'} end
return {1,raw}
""".strip()

_REDIS_RESERVE = r"""
local now=tonumber(ARGV[1]); local reservation=ARGV[2]; local deadline=tonumber(ARGV[3]); local correlations=cjson.decode(ARGV[4]); local seen={}; local rows={}
for i,c in ipairs(correlations) do
  local id=tostring(c[1] or ''); if seen[id] then return {0,'INVALID'} end; seen[id]=true
  local raw=redis.call('HGET',KEYS[1],id); if not raw then return {0,'INVALID'} end; local e=cjson.decode(raw)
  if tonumber(e.expires_at or 0) <= now or tostring(e.output_sha256 or '') ~= tostring(c[2] or '') or tonumber(e.output_size or -1) ~= tonumber(c[3] or -2) then return {0,'INVALID'} end
  if e.status == 'reserved' and e.reservation_id == reservation then rows[i]=e
  elseif e.status == 'ready' or e.status == 'delivered' then rows[i]=e
  else return {0,'INVALID'} end
end
for i,e in ipairs(rows) do local id=tostring(correlations[i][1]); if e.status ~= 'reserved' then e.reserved_from_status=e.status; e.status='reserved'; e.reservation_id=reservation; e.reservation_deadline=deadline; redis.call('HSET',KEYS[1],id,cjson.encode(e)); redis.call('ZADD',KEYS[2],deadline,id) end end
return {1,'OK'}
""".strip()

_REDIS_RELEASE = r"""
local now=tonumber(ARGV[1]); local reservation=ARGV[2]; local ids=cjson.decode(ARGV[3])
for _,id in ipairs(ids) do
  local raw=redis.call('HGET',KEYS[1],id)
  if raw then local e=cjson.decode(raw); if e.status == 'reserved' and e.reservation_id == reservation then
    if tonumber(e.expires_at or 0) <= now then redis.call('HDEL',KEYS[1],id); redis.call('ZREM',KEYS[2],id); if redis.call('HGET',KEYS[3],tostring(e.fingerprint or '')) == id then redis.call('HDEL',KEYS[3],tostring(e.fingerprint or '')) end; if tostring(e.cancel_token_sha256 or '') ~= '' then redis.call('HDEL',KEYS[4],tostring(e.cancel_token_sha256)) end
    else e.status=(e.reserved_from_status == 'ready' or e.reserved_from_status == 'delivered') and e.reserved_from_status or 'delivered'; e.reservation_id=''; e.reserved_from_status=''; e.reservation_deadline=0; redis.call('HSET',KEYS[1],id,cjson.encode(e)); redis.call('ZADD',KEYS[2],tonumber(e.expires_at),id) end
  end end
end
return {1,'OK'}
""".strip()

_REDIS_APPLY = r"""
local reservation=ARGV[1]; local ids=cjson.decode(ARGV[2]); local rows={}
for i,id in ipairs(ids) do
  local raw=redis.call('HGET',KEYS[1],id); if not raw then return {0,'INVALID'} end; local e=cjson.decode(raw)
  if e.status == 'applied' and tostring(e.applied_reservation_id or '') == reservation then rows[i]=e
  elseif e.status == 'reserved' and e.reservation_id == reservation then rows[i]=e
  else return {0,'INVALID'} end
end
for i,e in ipairs(rows) do local id=ids[i]; if e.status ~= 'applied' then e.status='applied'; e.applied_reservation_id=reservation; e.reservation_id=''; e.reserved_from_status=''; e.reservation_deadline=0; redis.call('HSET',KEYS[1],id,cjson.encode(e)); redis.call('ZADD',KEYS[2],tonumber(e.expires_at),id) end end
return {1,'OK'}
""".strip()


class RedisProviderArtifactLifecycleRegistry:
    """Shared Redis-backed lifecycle authority with atomic CAS transitions."""

    backend = "redis"
    shared = True
    authoritative = True
    consistency_scope = "single_redis_consistency_domain"

    def __init__(
        self,
        url: str,
        *,
        key_prefix: str = "sphinx-ai-assistant",
        candidate_ttl_seconds: int = PROVIDER_ARTIFACT_CANDIDATE_TTL_SECONDS,
        duplicate_window_seconds: int = PROVIDER_ARTIFACT_DUPLICATE_WINDOW_SECONDS,
        max_records: int = PROVIDER_ARTIFACT_MAX_LIFECYCLE_RECORDS,
        socket_timeout_seconds: float = 2.0,
        require_tls: bool = False,
        client: Any | None = None,
        cancellation_poll_seconds: float = 0.25,
        sweep_interval_seconds: float | None = None,
        operation_attempts: int = PROVIDER_ARTIFACT_REDIS_OPERATION_ATTEMPTS,
        cancellation_watch_failure_limit: int = PROVIDER_ARTIFACT_REDIS_WATCH_FAILURE_LIMIT,
        cluster_mode: bool = False,
    ) -> None:
        if not str(url or "").strip():
            raise ProviderArtifactError("PROVIDER_ARTIFACT_REDIS_URL_REQUIRED")
        self.url = str(url).strip()
        try:
            self._transport, self._connection_kwargs = redis_connection_kwargs(
                self.url,
                require_tls=bool(require_tls),
                socket_timeout_seconds=socket_timeout_seconds,
            )
        except RedisSecurityError as exc:
            raise ProviderArtifactError(f"PROVIDER_ARTIFACT_{exc.code}") from exc
        self._candidate_ttl = max(30, min(int(candidate_ttl_seconds), 24 * 60 * 60))
        self._duplicate_window = max(
            1, min(int(duplicate_window_seconds), self._candidate_ttl)
        )
        self._max_records = max(32, min(int(max_records), 10_000))
        self._poll_seconds = max(0.05, min(float(cancellation_poll_seconds), 2.0))
        self._operation_attempts = max(1, min(int(operation_attempts), 3))
        self._watch_failure_limit = max(
            1, min(int(cancellation_watch_failure_limit), 10)
        )
        self._cluster_mode = bool(cluster_mode)
        if self._cluster_mode and self._transport.database != 0:
            raise ProviderArtifactError(
                "PROVIDER_ARTIFACT_REDIS_CLUSTER_DATABASE_INVALID"
            )
        default_sweep = min(30.0, max(1.0, self._candidate_ttl / 4.0))
        self._sweep_seconds = max(
            0.05,
            min(
                float(
                    sweep_interval_seconds
                    if sweep_interval_seconds is not None
                    else default_sweep
                ),
                60.0,
            ),
        )
        safe = "".join(
            c
            for c in str(key_prefix or "sphinx-ai-assistant").lower()
            if c.isalnum() or c in "_-:"
        )[:64]
        tag = f"{safe or 'sphinx-ai-assistant'}:{{provider-artifact}}"
        self._records_key = f"{tag}:records"
        self._expiry_key = f"{tag}:expiry"
        self._fingerprints_key = f"{tag}:fingerprints"
        self._cancel_key = f"{tag}:cancel"
        self._keys = [
            self._records_key,
            self._expiry_key,
            self._fingerprints_key,
            self._cancel_key,
        ]
        self._client = client
        self._owns = client is None
        self._local_tasks: dict[str, asyncio.Task] = {}
        self._watchers: dict[str, asyncio.Task] = {}
        self._sweeper: asyncio.Task | None = None
        self._local_lock = asyncio.Lock()

    def manifest(self) -> dict[str, object]:
        return {
            "backend": self.backend,
            "shared": True,
            "authoritative": True,
            "consistency_scope": self.consistency_scope,
            "persistence": "ephemeral_shared_metadata",
            "topology": "cluster" if self._cluster_mode else "standalone",
            **self._transport.manifest(),
        }

    async def initialize(self) -> None:
        if self._client is None:
            try:
                if self._cluster_mode:
                    from redis.asyncio.cluster import (  # ruff: ignore[import-outside-top-level]
                        RedisCluster,  # type: ignore[import-not-found]  # ruff: ignore[import-outside-top-level]
                    )

                    self._client = RedisCluster.from_url(
                        self.url, **self._connection_kwargs
                    )
                else:
                    import redis.asyncio as redis_async  # type: ignore[import-not-found]  # ruff: ignore[import-outside-top-level]

                    self._client = redis_async.from_url(
                        self.url, **self._connection_kwargs
                    )
            except Exception as exc:
                raise ProviderArtifactError(
                    "PROVIDER_ARTIFACT_REDIS_DEPENDENCY_UNAVAILABLE"
                ) from exc
        try:
            await self._client.ping()
        except Exception as exc:
            raise ProviderArtifactError("PROVIDER_ARTIFACT_REDIS_UNAVAILABLE") from exc
        await self._cleanup_shared()
        if self._sweeper is None or self._sweeper.done():
            self._sweeper = asyncio.create_task(self._sweep_loop())

    async def _cleanup_shared(self) -> None:
        await self._eval(_REDIS_CLEANUP, [int(time.time())])

    async def _sweep_loop(self) -> None:
        try:
            while True:
                await asyncio.sleep(self._sweep_seconds)
                try:
                    await self._cleanup_shared()
                except ProviderArtifactError:
                    # Route operations remain fail-closed. A transient sweep
                    # failure must not terminate the worker or expose secrets.
                    continue
        except asyncio.CancelledError:
            pass

    async def close(self) -> None:
        async with self._local_lock:
            local_ids = tuple(self._local_tasks)
            tasks = list(self._local_tasks.values()) + list(self._watchers.values())
            if self._sweeper is not None:
                tasks.append(self._sweeper)
                self._sweeper = None
            self._local_tasks.clear()
            self._watchers.clear()
        # Graceful worker shutdown relinquishes only generations owned by this
        # process. Shared records owned by other replicas are never cleared.
        now = int(time.time())
        if self._client is not None:
            for lifecycle_id in local_ids:
                try:  # ruff: ignore[suppressible-exception]
                    await self._eval(
                        _REDIS_FAIL,
                        [
                            lifecycle_id,
                            "cancelled",
                            now + PROVIDER_ARTIFACT_FAILURE_TTL_SECONDS,
                        ],
                    )
                except ProviderArtifactError:  # ruff: ignore[try-except-in-loop]
                    # Shutdown cannot safely broaden into a global cleanup. A
                    # crashed/unreachable store leaves the record to its TTL.
                    pass
        for task in tasks:
            if not task.done():
                task.cancel()
        if tasks:
            await asyncio.gather(*tasks, return_exceptions=True)
        if self._client is not None and self._owns:
            closer = getattr(self._client, "aclose", None) or getattr(
                self._client, "close", None
            )
            if closer:
                result = closer()
                if hasattr(result, "__await__"):
                    await result
            self._client = None

    async def clear(self) -> None:
        """Clear only process-owned tasks; never erase shared Redis authority."""
        async with self._local_lock:
            tasks = list(self._local_tasks.values()) + list(self._watchers.values())
            self._local_tasks.clear()
            self._watchers.clear()
        for task in tasks:
            if not task.done():
                task.cancel()
        if tasks:
            await asyncio.gather(*tasks, return_exceptions=True)

    async def _eval(self, script: str, args: list[Any]) -> tuple[int, str]:
        if self._client is None:
            raise ProviderArtifactError("PROVIDER_ARTIFACT_REDIS_NOT_INITIALIZED")
        last_exc: Exception | None = None
        for attempt in range(self._operation_attempts):
            try:
                out = await self._client.eval(
                    script, len(self._keys), *self._keys, *args
                )
            except ProviderArtifactError:
                raise
            except Exception as exc:
                last_exc = exc
                if attempt + 1 >= self._operation_attempts:
                    raise ProviderArtifactError(
                        "PROVIDER_ARTIFACT_REDIS_OPERATION_FAILED"
                    ) from exc
                # Every lifecycle Lua mutation is retry-idempotent for the same
                # arguments.  This bounds failover/reconnect outcome ambiguity
                # without ever widening authority or generating a new ID.
                await asyncio.sleep(0)
                continue
            _len = len(out) < 2  # ruff: ignore[magic-value-comparison]
            if not isinstance(out, (list, tuple)) or _len:
                raise ProviderArtifactError("PROVIDER_ARTIFACT_REDIS_PROTOCOL_ERROR")
            value = out[1].decode("utf-8") if isinstance(out[1], bytes) else str(out[1])
            return int(out[0]), value
        raise ProviderArtifactError(
            "PROVIDER_ARTIFACT_REDIS_OPERATION_FAILED"
        ) from last_exc

    @staticmethod
    def _public(raw: str) -> dict[str, object]:
        try:
            e = json.loads(raw)
        except Exception as exc:
            raise ProviderArtifactError(
                "PROVIDER_ARTIFACT_REDIS_PROTOCOL_ERROR"
            ) from exc
        return {
            "contract": PROVIDER_ARTIFACT_LIFECYCLE_CONTRACT,
            "lifecycle_id": str(e.get("lifecycle_id") or ""),
            "status": str(e.get("status") or ""),
            "created_at": int(e.get("created_at") or 0),
            "expires_at": int(e.get("expires_at") or 0),
            "regeneration_of": str(e.get("regeneration_of") or "") or None,
        }

    async def begin(
        self, request: ProviderArtifactRequest, *, provider: str, model: str
    ) -> str:
        now = int(time.time())
        fingerprint = ProviderArtifactLifecycleRegistry._fingerprint(request)
        cancel_hash = ProviderArtifactLifecycleRegistry._cancel_hash(
            request.cancel_token
        )
        for _ in range(4):
            lifecycle_id = secrets.token_hex(16)
            ok, val = await self._eval(
                _REDIS_BEGIN,
                [
                    now,
                    lifecycle_id,
                    fingerprint,
                    cancel_hash,
                    request.generator_id,
                    str(provider or ""),
                    str(model or ""),
                    request.kind,
                    request.mime_type,
                    request.prompt_sha256,
                    request.regenerate_of,
                    now + self._candidate_ttl,
                    self._max_records,
                    self._duplicate_window,
                ],
            )
            if ok:
                return lifecycle_id
            mapping = {
                "REGENERATION_INVALID": "PROVIDER_ARTIFACT_REGENERATION_INVALID",
                "DUPLICATE": "PROVIDER_ARTIFACT_DUPLICATE",
                "REQUEST_INVALID": "PROVIDER_ARTIFACT_REQUEST_INVALID",
                "BUSY": "PROVIDER_ARTIFACT_LIFECYCLE_BUSY",
            }
            if val == "COLLISION":
                continue
            raise ProviderArtifactError(
                mapping.get(val, "PROVIDER_ARTIFACT_REDIS_PROTOCOL_ERROR")
            )
        raise ProviderArtifactError("PROVIDER_ARTIFACT_LIFECYCLE_BUSY")

    async def attach_task(self, lifecycle_id: str, task: asyncio.Task) -> None:
        status = await self.public_status(lifecycle_id)
        if status is None or status.get("status") != "generating":
            task.cancel()
            raise ProviderArtifactError("PROVIDER_ARTIFACT_CANCELLED")
        async with self._local_lock:
            self._local_tasks[lifecycle_id] = task
            watcher = asyncio.create_task(self._watch_cancel(lifecycle_id, task))
            self._watchers[lifecycle_id] = watcher

    async def _watch_cancel(self, lifecycle_id: str, task: asyncio.Task) -> None:
        failures = 0
        try:
            while not task.done():
                await asyncio.sleep(self._poll_seconds)
                try:
                    status = await self.public_status(lifecycle_id)
                except ProviderArtifactError:
                    failures += 1
                    if failures >= self._watch_failure_limit:
                        # If shared authority cannot be observed for several
                        # consecutive polls, stop spending provider work rather
                        # than continuing outside the lifecycle control plane.
                        if not task.done():
                            task.cancel()
                        break
                    continue
                failures = 0
                if status is None or status.get("status") != "generating":
                    if (
                        status is not None
                        and status.get("status") == "cancelled"
                        and not task.done()
                    ):
                        task.cancel()
                    break
        except asyncio.CancelledError:
            pass
        finally:
            async with self._local_lock:
                self._watchers.pop(lifecycle_id, None)

    async def _forget_local(self, lifecycle_id: str) -> None:
        async with self._local_lock:
            self._local_tasks.pop(lifecycle_id, None)
            watcher = self._watchers.pop(lifecycle_id, None)
        current = asyncio.current_task()
        if watcher is not None and watcher is not current and not watcher.done():
            watcher.cancel()

    async def complete(
        self, lifecycle_id: str, receipt: ProviderArtifactReceipt
    ) -> ProviderArtifactReceipt:
        now = int(time.time())
        expires = now + self._candidate_ttl
        ok, val = await self._eval(
            _REDIS_COMPLETE,
            [
                lifecycle_id,
                now,
                expires,
                int(receipt.output_size),
                str(receipt.output_sha256),
                receipt.generator_id,
                receipt.provider,
                receipt.model,
                receipt.kind,
                receipt.mime_type,
                receipt.prompt_sha256,
            ],
        )
        await self._forget_local(lifecycle_id)
        if not ok:
            raise ProviderArtifactError(
                "PROVIDER_ARTIFACT_RECEIPT_INVALID"
                if val == "RECEIPT_INVALID"
                else "PROVIDER_ARTIFACT_CANCELLED"
            )
        public = self._public(val)
        return receipt.with_lifecycle(
            lifecycle_id=lifecycle_id,
            expires_at=int(public["expires_at"]),
            regeneration_of=str(public.get("regeneration_of") or ""),
            state="ready",
        )

    async def fail(self, lifecycle_id: str, *, cancelled: bool = False) -> None:
        now = int(time.time())
        await self._eval(
            _REDIS_FAIL,
            [
                lifecycle_id,
                "cancelled" if cancelled else "failed",
                now + PROVIDER_ARTIFACT_FAILURE_TTL_SECONDS,
            ],
        )
        await self._forget_local(lifecycle_id)

    async def cancel(self, cancel_token: str) -> Mapping[str, object]:
        normalized = str(cancel_token or "").strip().lower()
        _len = len(normalized) != 64  # ruff: ignore[magic-value-comparison]
        if _len or any(ch not in "0123456789abcdef" for ch in normalized):
            raise ProviderArtifactError("PROVIDER_ARTIFACT_CANCEL_INVALID")
        token_hash = ProviderArtifactLifecycleRegistry._cancel_hash(normalized)
        if not token_hash:
            raise ProviderArtifactError("PROVIDER_ARTIFACT_CANCEL_INVALID")
        now = int(time.time())
        ok, val = await self._eval(
            _REDIS_CANCEL,
            [token_hash, now, now + PROVIDER_ARTIFACT_FAILURE_TTL_SECONDS],
        )
        if not ok:
            raise ProviderArtifactError("PROVIDER_ARTIFACT_CANCEL_INVALID")
        public = self._public(val)
        lifecycle_id = str(public["lifecycle_id"])
        async with self._local_lock:
            task = self._local_tasks.get(lifecycle_id)
        if public.get("status") == "cancelled" and task is not None and not task.done():
            task.cancel()
        return public

    async def mark_delivered(self, lifecycle_id: str) -> None:
        await self._eval(_REDIS_MARK_DELIVERED, [lifecycle_id])

    async def public_status(self, lifecycle_id: str) -> Mapping[str, object] | None:
        ok, val = await self._eval(
            _REDIS_GET, [str(lifecycle_id or ""), int(time.time())]
        )
        return self._public(val) if ok else None

    async def validate_zip_correlation(
        self, *, lifecycle_id: str, output_sha256: str, output_size: int
    ) -> Mapping[str, object]:
        status = await self.public_status(lifecycle_id)
        if status is None or status.get("status") not in {"ready", "delivered"}:
            raise ProviderArtifactError("PROVIDER_ARTIFACT_PROVENANCE_INVALID")
        # Full hash/size binding is performed atomically by reserve_zip_correlations.
        reservation, ids = await self.reserve_zip_correlations(
            ((lifecycle_id, output_sha256, output_size),)
        )
        await self.release_zip_reservation(ids, reservation)
        status = await self.public_status(lifecycle_id)
        if status is None:
            raise ProviderArtifactError("PROVIDER_ARTIFACT_PROVENANCE_INVALID")
        return status

    async def reserve_zip_correlations(
        self, correlations: tuple[tuple[str, str, int], ...]
    ) -> tuple[str, tuple[str, ...]]:
        if not correlations:
            return "", ()
        ids = tuple(str(c[0] or "") for c in correlations)
        reservation = secrets.token_hex(16)
        now = int(time.time())
        ok, _ = await self._eval(
            _REDIS_RESERVE,
            [
                now,
                reservation,
                now + PROVIDER_ARTIFACT_ZIP_RESERVATION_TTL_SECONDS,
                json.dumps(
                    [[c[0], str(c[1] or "").lower(), int(c[2])] for c in correlations],
                    separators=(",", ":"),
                ),
            ],
        )
        if not ok:
            raise ProviderArtifactError("PROVIDER_ARTIFACT_PROVENANCE_INVALID")
        return reservation, ids

    async def release_zip_reservation(
        self, lifecycle_ids: tuple[str, ...], reservation_id: str
    ) -> None:
        if not lifecycle_ids or not reservation_id:
            return
        await self._eval(
            _REDIS_RELEASE,
            [
                int(time.time()),
                reservation_id,
                json.dumps(list(lifecycle_ids), separators=(",", ":")),
            ],
        )

    async def mark_applied(
        self, lifecycle_ids: tuple[str, ...], reservation_id: str
    ) -> None:
        if not lifecycle_ids or not reservation_id:
            raise ProviderArtifactError("PROVIDER_ARTIFACT_PROVENANCE_INVALID")
        ok, _ = await self._eval(
            _REDIS_APPLY,
            [reservation_id, json.dumps(list(lifecycle_ids), separators=(",", ":"))],
        )
        if not ok:
            raise ProviderArtifactError("PROVIDER_ARTIFACT_PROVENANCE_INVALID")


def build_provider_artifact_lifecycle_registry(
    backend: str,
    *,
    redis_url: str = "",
    redis_key_prefix: str = "sphinx-ai-assistant",
    redis_timeout_seconds: float = 2.0,
    redis_client: Any | None = None,
    require_redis_tls: bool = False,
    candidate_ttl_seconds: int = PROVIDER_ARTIFACT_CANDIDATE_TTL_SECONDS,
    duplicate_window_seconds: int = PROVIDER_ARTIFACT_DUPLICATE_WINDOW_SECONDS,
    max_records: int = PROVIDER_ARTIFACT_MAX_LIFECYCLE_RECORDS,
    redis_cluster_mode: bool = False,
):
    name = str(backend or "memory").strip().lower()
    if name == "memory":
        return ProviderArtifactLifecycleRegistry(
            candidate_ttl_seconds=candidate_ttl_seconds,
            duplicate_window_seconds=duplicate_window_seconds,
            max_records=max_records,
        )
    if name == "redis":
        return RedisProviderArtifactLifecycleRegistry(
            redis_url,
            key_prefix=redis_key_prefix,
            socket_timeout_seconds=redis_timeout_seconds,
            client=redis_client,
            require_tls=require_redis_tls,
            candidate_ttl_seconds=candidate_ttl_seconds,
            duplicate_window_seconds=duplicate_window_seconds,
            max_records=max_records,
            cluster_mode=redis_cluster_mode,
        )
    raise ProviderArtifactError("PROVIDER_ARTIFACT_LIFECYCLE_BACKEND_INVALID")


__all__ = [
    "PROVIDER_ARTIFACT_CANCEL_CONTRACT",
    "PROVIDER_ARTIFACT_CANDIDATE_TTL_SECONDS",
    "PROVIDER_ARTIFACT_DUPLICATE_WINDOW_SECONDS",
    "PROVIDER_ARTIFACT_FAILURE_TTL_SECONDS",
    "PROVIDER_ARTIFACT_LIFECYCLE_CONTRACT",
    "PROVIDER_ARTIFACT_MAX_LIFECYCLE_RECORDS",
    "PROVIDER_ARTIFACT_REDIS_OPERATION_ATTEMPTS",
    "PROVIDER_ARTIFACT_REDIS_WATCH_FAILURE_LIMIT",
    "PROVIDER_ARTIFACT_ZIP_RESERVATION_TTL_SECONDS",
    "ProviderArtifactLifecycleRegistry",
    "RedisProviderArtifactLifecycleRegistry",
    "build_provider_artifact_lifecycle_registry",
]
