# docker/Dockerfile.win

# https://docs.docker.com/reference/dockerfile#user
FROM microsoft/windowsservercore
# Create Windows user in the container
RUN net user /add patrick
# Set it for subsequent commands
USER patrick
