# Authors: The scikit-plots developers
# SPDX-License-Identifier: BSD-3-Clause

"""
Mandatory Redis lifecycle chaos gate for CI.

This entrypoint is intentionally standard-library only. It validates the Redis
server major, verifies that the configured Python can import the pinned Redis
client, and then executes the live Redis lifecycle doctors with skip-as-failure
environment flags enabled.

Run from any working directory::

    python _hf_spaces_proxy/ci/run_redis_chaos.py --mode all

The test suite itself starts disposable standalone/cluster Redis processes. No
Redis authority URL, password, provider token, prompt, or generated bytes are
printed by this runner.
"""

from __future__ import annotations

import argparse
import logging
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

_CI_DIR = Path(__file__).resolve().parent
if str(_CI_DIR) not in sys.path:
    sys.path.insert(0, str(_CI_DIR))
from redis_chaos_attestation import write_attestation  # noqa: E402

_SUPPORTED_REDIS_MAJORS = {7, 8}
_TRUE = {"1", "true", "yes", "on"}
logger = logging.getLogger(__name__)


def _extension_root() -> Path:
    return Path(__file__).resolve().parents[2]


def _repo_pythonpath() -> Path:
    # .../scikitplot/_externals/_sphinx_ext/_sphinx_ai_assistant/_hf_spaces_proxy/ci
    # parents[6] is the directory containing the top-level scikitplot package.
    return Path(__file__).resolve().parents[6]


def _resolve_binary(explicit: str, env_name: str, default_name: str) -> str:
    candidate = str(explicit or "").strip() or os.environ.get(env_name, "").strip()
    if candidate:
        path = Path(candidate).expanduser()
        if not path.is_file() or not os.access(path, os.X_OK):
            raise RuntimeError(f"{env_name} does not name an executable file")
        return str(path.resolve())
    found = shutil.which(default_name)
    if not found:
        raise RuntimeError(f"required executable is unavailable: {default_name}")
    return found


def _redis_major(binary: str) -> int:
    result = subprocess.run(  # ruff: ignore[subprocess-without-shell-equals-true]
        [binary, "--version"],
        capture_output=True,
        text=True,
        timeout=10,
        check=False,
    )
    if result.returncode != 0:
        raise RuntimeError("redis-server --version failed")
    rendered = (result.stdout or "") + " " + (result.stderr or "")
    match = re.search(r"(?:v=|Redis server v=)(\d+)(?:\.|\b)", rendered)
    if not match:
        match = re.search(r"\b(\d+)\.\d+(?:\.\d+)?\b", rendered)
    if not match:
        raise RuntimeError("could not determine redis-server major version")
    major = int(match.group(1))
    if major not in _SUPPORTED_REDIS_MAJORS:
        raise RuntimeError(
            f"unsupported redis-server major {major}; expected Redis 7 or 8"
        )
    return major


def _verify_python_runtime(python: str) -> None:
    code = (
        "import pytest, redis; "
        "from redis.asyncio.cluster import RedisCluster; "
        "print(getattr(redis, '__version__', 'unknown'))"
    )
    result = subprocess.run(  # ruff: ignore[subprocess-without-shell-equals-true]
        [python, "-c", code],
        capture_output=True,
        text=True,
        timeout=20,
        check=False,
    )
    if result.returncode != 0:
        raise RuntimeError(
            "CI Python must provide pytest, redis, and redis.asyncio.cluster.RedisCluster"
        )


def _run_pytest(*, python: str, redis_server: str, mode: str) -> None:
    root = _extension_root()
    env = os.environ.copy()
    existing = env.get("PYTHONPATH", "").strip()
    repo_path = str(_repo_pythonpath())
    env["PYTHONPATH"] = repo_path if not existing else repo_path + os.pathsep + existing
    env["RUN146_REDIS_SERVER"] = redis_server
    env["RUN147_REDIS_SERVER"] = redis_server

    if mode == "standalone":
        env["RUN146_REDIS_CHAOS_REQUIRED"] = "1"
        env["RUN147_REDIS_STANDALONE_REQUIRED"] = "1"
        command = [
            python,
            "-m",
            "pytest",
            "-q",
            "-p",
            "no:cacheprovider",
            "tests/_hf_spaces_proxy/_utils/test__provider_artifact_lifecycle__redis_chaos.py",
            "tests/_hf_spaces_proxy/ci/test_run_redis_chaos.py",
            "-k",
            "live_redis or live_standalone",
        ]
    elif mode == "cluster":
        env["RUN147_REDIS_CLUSTER_REQUIRED"] = "1"
        command = [
            python,
            "-m",
            "pytest",
            "-q",
            "-p",
            "no:cacheprovider",
            "tests/_hf_spaces_proxy/ci/test_run_redis_chaos.py",
            "-k",
            "live_cluster",
        ]
    else:  # pragma: no cover - argparse constrains this
        raise RuntimeError("unsupported chaos mode")

    result = subprocess.run(  # ruff: ignore[subprocess-without-shell-equals-true]
        command,
        cwd=root,
        env=env,
        check=False,
    )
    if result.returncode != 0:
        raise RuntimeError(f"Redis {mode} chaos gate failed")


def main(  # ruff: ignore[undocumented-public-function]
    argv: list[str] | None = None,
) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--mode", choices=("standalone", "cluster", "all"), default="all"
    )
    parser.add_argument("--redis-server", default="")
    parser.add_argument("--python", default=sys.executable)
    parser.add_argument("--attestation-dir", type=Path)
    parser.add_argument("--source-revision", default="")
    parser.add_argument("--redis-image", default="")
    args = parser.parse_args(argv)

    try:
        redis_server = _resolve_binary(
            args.redis_server, "RUN147_REDIS_SERVER", "redis-server"
        )
        major = _redis_major(redis_server)
        _verify_python_runtime(args.python)
        modes = ("standalone", "cluster") if args.mode == "all" else (args.mode,)
        if args.attestation_dir is not None and (
            not args.source_revision or not args.redis_image
        ):
            raise RuntimeError(
                "attestation output requires --source-revision and digest-pinned --redis-image"
            )
        for mode in modes:
            logger.info("[run147] Redis %s %s chaos gate", major, mode)
            _run_pytest(python=args.python, redis_server=redis_server, mode=mode)
            if args.attestation_dir is not None:
                logger.info(
                    "[run147] writing Redis %s attestation for mode=%s", major, mode
                )
                write_attestation(
                    args.attestation_dir,
                    mode=mode,
                    redis_major=major,
                    redis_image=args.redis_image,
                    source_revision=args.source_revision,
                )
        logger.info("[run147] PASS Redis %s mode=%s", major, args.mode)
        return 0
    except (OSError, RuntimeError, subprocess.SubprocessError) as exc:
        # Never include Redis URLs or secret environment values in failures.
        logger.error("[run147] FAIL: %s", exc)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
