cat > source/_templates/layout.html << 'EOF'
{#
  layout.html
  ===========
  Minimal PyData Sphinx Theme layout override.
  Works across all PyData versions (0.7 - 0.17+).

  Purpose
  -------
  Inject shell.html into the Sphinx Gallery notebook index page.
  The main index.html already manages its own shell.html include
  inside its own {% block docs_main %} — this file never touches
  that page.

  Why docs_main is safe for all versions
  ---------------------------------------
  docs_main is the stable core block present in every PyData
  release. article-header-extra was added in 0.13 and removed
  in later versions — it is not reliable across versions.

  Why there is no conflict with index.html
  -----------------------------------------
  Jinja2 inheritance rule: when index.html defines {% block
  docs_main %}, it completely replaces this layout.html's
  docs_main for that page. Our block is never executed on the
  main index page regardless of pagename check.

  Two independent guards (defense in depth)
  ------------------------------------------
  Guard 1 — Jinja2 inheritance: index.html's docs_main override
            makes this block unreachable on main index page.
  Guard 2 — pagename condition: explicit string match ensures
            shell only renders on the exact target page.

  Sub-includes
  ------------
  shell.html uses:
    {% include 'shell_py_example.html' %}
    {% include 'shell_interactive.html' %}
  Both resolve automatically via Sphinx's Jinja loader using
  templates_path = ["_templates"] from conf.py.

  pagename confirmed
  ------------------
  Verified from built HTML:
    DOCUMENTATION_OPTIONS.pagename =
      'auto_examples/00-jupyter_notebooks/index'
#}
{% extends "!layout.html" %}


{% block docs_main %}

  {#- Guard: only inject on the exact gallery notebook index page -#}
  {%- if pagename == "auto_examples/00-jupyter_notebooks/index" %}
    <div class="additional-content">
      {%- include "shell.html" %}
    </div>
  {%- endif %}

  {{- super() }}

{% endblock docs_main %}
EOF

cat > source/_templates/layout.html << 'EOF'
{#
  layout.html
  ===========
  PyData Sphinx Theme layout override.
  Compatible: PyData 0.7 - 0.17+ (all versions).

  Purpose
  -------
  Inject Jinja components into specific pages, driven entirely
  by conf.py html_context["page_components"]. This file contains
  only logic — it never needs editing to add or remove pages.

  To add a page
  -------------
  Edit conf.py html_context["page_components"] only.
  Do not edit this file.

  Why docs_main is the correct block
  -----------------------------------
  Across all PyData versions (0.7 - 0.17+), docs_main is the
  stable core block. article-header-extra was added in 0.13
  and removed in later versions. docs_main has never changed.

  Why there is no conflict with index.html
  -----------------------------------------
  Jinja2 inheritance rule: when index.html defines
  {% block docs_main %}, it completely replaces this block for
  that page. Our block is unreachable on the main index page
  regardless of any pagename condition. The pagename guard is
  defense-in-depth only.

  Two independent safety guards
  ------------------------------
  Guard 1 — Jinja2 inheritance
              index.html's docs_main override makes this block
              unreachable on the main page. Architectural.
  Guard 2 — page_components lookup
              pagename must appear as an explicit key in the
              conf.py dict. No accidental matches possible.

  Position semantics
  ------------------
  before : rendered ABOVE {{ super() }} → above page content
  after  : rendered BELOW {{ super() }} → below page content

  Missing template handling
  -------------------------
  Jinja2 "ignore missing" directive: if a listed template file
  does not exist, that slot is silently skipped. The build
  always completes. No KeyError, no TemplateNotFound crash.

  Sub-include resolution
  ----------------------
  shell.html contains:
    {% include 'shell_py_example.html' %}
    {% include 'shell_interactive.html' %}
  Both resolve automatically via Sphinx's Jinja loader
  (templates_path = ["_templates"] in conf.py).

  Theme compatibility note
  ------------------------
  This file targets PyData Sphinx Theme via docs_main block.
  For other themes:
    Read the Docs / Alabaster → replace docs_main with body
    Furo                      → replace docs_main with content
  The logic inside the block is identical for all themes.
#}
{% extends "!layout.html" %}


{% block docs_main %}

  {# ------------------------------------------------------------------ #}
  {# Resolve component lists for this page from conf.py html_context    #}
  {#                                                                    #}
  {# page_components is injected by Sphinx from:                        #}
  {#   html_context["page_components"] in conf.py                       #}
  {#                                                                    #}
  {# .get() with default {} means: unknown pagenames yield empty lists. #}
  {# Missing "before"/"after" keys also yield empty lists.              #}
  {# Result: this block is a pure no-op on every unconfigured page.     #}
  {# ------------------------------------------------------------------ #}
  {%- if page_components is defined %}
    {%- set _page_cfg = page_components.get(pagename, {}) %}
  {%- else %}
    {%- set _page_cfg = {} %}
  {%- endif %}

  {%- set _before = _page_cfg.get("before", []) %}
  {%- set _after  = _page_cfg.get("after",  []) %}

  {# ------------------------------------------------------------------ #}
  {# Inject BEFORE components (above page content)                      #}
  {# ------------------------------------------------------------------ #}
  {%- for _tmpl in _before %}
    <div class="page-component page-component--before"
         data-component="{{ _tmpl }}">
      {%- include _tmpl ignore missing %}
    </div>
  {%- endfor %}

  {# ------------------------------------------------------------------ #}
  {# Original page content                                              #}
  {# ------------------------------------------------------------------ #}
  {{- super() }}

  {# ------------------------------------------------------------------ #}
  {# Inject AFTER components (below page content)                       #}
  {# ------------------------------------------------------------------ #}
  {%- for _tmpl in _after %}
    <div class="page-component page-component--after"
         data-component="{{ _tmpl }}">
      {%- include _tmpl ignore missing %}
    </div>
  {%- endfor %}

{% endblock docs_main %}
EOF

cat > source/_templates/layout.html << 'EOF'
{#
  layout.html
  ===========
  PyData Sphinx Theme layout override.
  Compatible: PyData 0.7 – 0.17+ (all versions).

  Strategy: render → stage → relocate
  -------------------------------------
  Jinja's super() is atomic — no parent template can inject content
  at an interior position inside a child block. The only correct
  non-extension solution is:

    1. Render the Jinja component here (Jinja runs fully, all
       sub-includes resolve: shell_py_example.html,
       shell_interactive.html, etc.)

    2. Place rendered HTML into a hidden staging <div> with a
       known id. This div sits outside the article DOM.

    3. Emit a <script> that runs at DOMContentLoaded, finds the
       CSS selector target inside the article, and moves the
       staging div's contents to that exact position using
       insertAdjacentHTML — the standard DOM API, no libraries.

  Why this is correct and stable
  --------------------------------
  - Jinja rendering happens at build time (server side) — all
    {% include %} calls resolve through Sphinx's own Jinja loader.
  - DOM relocation happens at load time (client side) — only
    standard DOM APIs used (insertAdjacentHTML, getElementById).
  - No dependency on PyData internals. No version-specific blocks.
  - CSS selectors in conf.py are stable sphinx-gallery class names.

  Safety guards
  -------------
  Guard 1 — Jinja inheritance:
    index.html overrides docs_main entirely → this block is
    unreachable on the main page. Architectural, not conditional.

  Guard 2 — page_components dict lookup:
    Only pages explicitly listed in conf.py receive components.
    Unknown pagenames produce an empty _cfg → nothing emitted.

  Guard 3 — JS selector check:
    If target element not found on page → logs to console, drops
    silently. Page always loads correctly.

  Guard 4 — ignore missing:
    If template file does not exist → silently skipped.
    Build always completes.

  Adding a new page
  -----------------
  Edit conf.py html_context["page_components"] only.
  Do not edit this file.
#}
{% extends "!layout.html" %}


{% block docs_main %}

  {# ------------------------------------------------------------------ #}
  {# Resolve config for this page from conf.py html_context             #}
  {# ------------------------------------------------------------------ #}
  {%- if page_components is defined %}
    {%- set _cfg = page_components.get(pagename, {}) %}
  {%- else %}
    {%- set _cfg = {} %}
  {%- endif %}

  {%- set _template = _cfg.get("template", "") %}
  {%- set _selector = _cfg.get("selector", "") %}
  {%- set _position = _cfg.get("position", "beforebegin") %}

  {# ------------------------------------------------------------------ #}
  {# Original page content — untouched                                  #}
  {# ------------------------------------------------------------------ #}
  {{- super() }}

  {# ------------------------------------------------------------------ #}
  {# Stage + relocate — only when this page has a component configured  #}
  {# ------------------------------------------------------------------ #}
  {%- if _template and _selector %}

    {#- Render the Jinja component fully at build time.                 #}
    {#- All sub-includes resolve here via Sphinx's Jinja loader.        #}
    {#- The staging div is hidden — user never sees it at this position.#}
    <div id="psc-staging-{{ loop.index | default(0) }}"
         data-psc-template="{{ _template }}"
         data-psc-selector="{{ _selector }}"
         data-psc-position="{{ _position }}"
         style="display:none;">
      {%- include _template ignore missing %}
    </div>

    {#- Relocate at DOMContentLoaded using standard DOM API only.       #}
    <script>
    (function () {
      var STAGING_ID = "psc-staging-{{ loop.index | default(0) }}";
      var SELECTOR   = {{ _selector | tojson }};
      var POSITION   = {{ _position | tojson }};

      function relocate() {
        var staging = document.getElementById(STAGING_ID);
        if (!staging) {
          console.warn("[page-component] staging div not found:", STAGING_ID);
          return;
        }

        var target = document.querySelector(SELECTOR);
        if (!target) {
          console.warn("[page-component] selector not found:", SELECTOR);
          staging.remove();
          return;
        }

        // Move rendered HTML to exact position inside article
        target.insertAdjacentHTML(POSITION, staging.innerHTML);
        staging.remove();

        console.debug("[page-component] inserted", {{ _template | tojson }},
                      "at", SELECTOR, POSITION);
      }

      if (document.readyState === "loading") {
        document.addEventListener("DOMContentLoaded", relocate);
      } else {
        // DOMContentLoaded already fired (e.g. script deferred)
        relocate();
      }
    })();
    </script>

  {%- endif %}

{% endblock docs_main %}
EOF
