# libs/_tools/generate.py
#
# Authors: The scikit-plots developers
# SPDX-License-Identifier: BSD-3-Clause

"""
Generate the packaging files of every partial distribution.

Inputs, each the single home of the facts it holds:

* ``scikitplot/_distributions.py``: which files a distribution owns;
* ``libs/_tools/registry.py``: how a distribution is packaged;
* the root ``pyproject.toml``: shared metadata, and every version specifier;
* ``scikitplot/__init__.py``: the version.

Outputs, per ``libs/<name>/``: ``pyproject.toml``, ``setup.py``,
``MANIFEST.in``, ``README.md`` and ``README_<NAME>.md``; plus
``libs/README.md`` and ``libs/.gitignore``.

Notes
-----
**User.** Run ``python -m libs._tools generate`` from the repository root after
changing any input, and commit the result. ``python -m libs._tools check``
exits non-zero when the files on disk differ from what the inputs produce.

**Developer.** Generation is a pure function of the inputs: no timestamps, no
environment, sorted iteration. Running it twice writes nothing the second
time, and that is what lets ``check`` compare bytes.
"""

from __future__ import annotations

import ast
import json
import re
from pathlib import Path
from typing import NamedTuple, Sequence

from . import registry, staging

__all__ = [
    "GENERATED_NOTICE",
    "RootMetadata",
    "check",
    "expected_files",
    "generate",
    "inherit_requirements",
    "read_root_metadata",
    "read_version",
    "readme_name",
    "requirement_name",
]

#: First line of every generated file that has a comment syntax.
GENERATED_NOTICE = (
    "Generated by libs/_tools. Do not edit; run: python -m libs._tools generate"
)

_REQUIREMENT_NAME = re.compile(r"^\s*([A-Za-z0-9][A-Za-z0-9._-]*)")


class RootMetadata(NamedTuple):
    """
    What every partial distribution inherits from the root project.

    Parameters
    ----------
    version : str
        The version in ``scikitplot/__init__.py``.
    requires_python : str
        Root ``requires-python``.
    authors, maintainers : tuple of dict
        Root ``authors`` and ``maintainers``.
    urls, scripts : dict of str to str
        Root ``[project.urls]`` and ``[project.scripts]``.
    dependencies : tuple of str
        Root ``[project.dependencies]``.
    build_requires : tuple of str
        Root ``[build-system].requires``.
    extras : dict of str to tuple of str
        Root ``[project.optional-dependencies]``.
    classifiers : tuple of str
        Root ``classifiers``.
    """

    version: str
    requires_python: str
    authors: tuple[dict[str, str], ...]
    maintainers: tuple[dict[str, str], ...]
    urls: dict[str, str]
    scripts: dict[str, str]
    dependencies: tuple[str, ...]
    build_requires: tuple[str, ...]
    extras: dict[str, tuple[str, ...]]
    classifiers: tuple[str, ...]


def _load_toml(path: Path) -> dict:
    """Parse a TOML file with the standard library, or its backport."""
    try:
        import tomllib  # Python >= 3.11  # noqa: PLC0415
    except ModuleNotFoundError:
        try:
            import tomli as tomllib  # noqa: PLC0415
        except ModuleNotFoundError as exc:
            raise ModuleNotFoundError(
                "libs/_tools needs a TOML parser to read the root pyproject.toml: "
                "use Python >= 3.11, or run: pip install tomli"
            ) from exc
    with path.open("rb") as handle:
        return tomllib.load(handle)


def read_version(root: Path) -> str:
    """
    Return the version declared in ``scikitplot/__init__.py``.

    Parameters
    ----------
    root : pathlib.Path
        Repository root.

    Returns
    -------
    str
        The first module-level ``__version__ = "<literal>"``.

    Raises
    ------
    ValueError
        If there is no such assignment, or its value is not a non-empty
        string literal.

    Notes
    -----
    **Developer.** This is the assignment the full distribution's build reads
    (``scikitplot/_build_utils/gitversion.py``), found by parsing rather than
    by importing, so the package is never executed to build one of its parts.
    """
    path = root / staging.PACKAGE_NAME / "__init__.py"
    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    for node in tree.body:
        if not isinstance(node, ast.Assign):
            continue
        targets = [t.id for t in node.targets if isinstance(t, ast.Name)]
        if "__version__" not in targets:
            continue
        value = node.value
        if (
            isinstance(value, ast.Constant)
            and isinstance(value.value, str)
            and value.value
        ):
            return value.value
        raise ValueError(f"{path}: __version__ is not a non-empty string literal")
    raise ValueError(f"{path}: no module-level __version__ assignment found")


def read_root_metadata(root: Path) -> RootMetadata:
    """
    Read the inherited metadata from the root project.

    Parameters
    ----------
    root : pathlib.Path
        Repository root.

    Returns
    -------
    RootMetadata

    Raises
    ------
    KeyError
        If the root ``pyproject.toml`` lacks a field that is inherited.
    """
    document = _load_toml(root / "pyproject.toml")
    project = document["project"]
    return RootMetadata(
        version=read_version(root),
        requires_python=project["requires-python"],
        authors=tuple(dict(entry) for entry in project["authors"]),
        maintainers=tuple(dict(entry) for entry in project["maintainers"]),
        urls=dict(project["urls"]),
        scripts=dict(project["scripts"]),
        dependencies=tuple(project["dependencies"]),
        build_requires=tuple(document["build-system"]["requires"]),
        extras={
            name: tuple(requirements)
            for name, requirements in project["optional-dependencies"].items()
        },
        classifiers=tuple(project["classifiers"]),
    )


def requirement_name(requirement: str) -> str:
    """
    Return the canonical project name of a requirement string.

    Parameters
    ----------
    requirement : str
        A dependency specifier, e.g. ``'numpy>=2.0.0; python_version >= "3.9"'``.

    Returns
    -------
    str
        The project name in canonical form, e.g. ``"numpy"``.

    Raises
    ------
    ValueError
        If the string does not start with a project name.
    """
    match = _REQUIREMENT_NAME.match(requirement)
    if match is None:
        raise ValueError(f"cannot read a project name from requirement {requirement!r}")
    return staging.load_distributions().canonicalize_name(match.group(1))


def inherit_requirements(
    names: Sequence[str],
    dependencies: Sequence[str],
    table: str = "[project.dependencies]",
) -> list[str]:
    """
    Return the root requirement lines for the named projects, verbatim.

    Parameters
    ----------
    names : sequence of str
        Project names to inherit.
    dependencies : sequence of str
        The root requirement list to inherit from.
    table : str, optional
        The name of that list in the root ``pyproject.toml``, for the error
        message.

    Returns
    -------
    list of str
        Every root line for each name, in root order, grouped by ``names``
        order. A project with several marker-specific lines yields them all.

    Raises
    ------
    ValueError
        If a name has no line in the root list. Inheriting is the only way a
        partial distribution gets a specifier for a shared dependency, so a
        missing one is a mistake in the registry, not something to guess.
    """
    canonicalize = staging.load_distributions().canonicalize_name
    lines: list[str] = []
    for name in names:
        wanted = canonicalize(name)
        found = [line for line in dependencies if requirement_name(line) == wanted]
        if not found:
            raise ValueError(
                f"{name!r} is not declared in the root {table}; declare it "
                "there, or write the requirement in full in the registry"
            )
        lines.extend(found)
    return lines


def readme_name(directory: str) -> str:
    """Return the package-description file name for a lib directory."""
    return f"README_{directory.upper()}.md"


# ---------------------------------------------------------------------------
# TOML rendering
# ---------------------------------------------------------------------------


def _string(value: str) -> str:
    """Render a TOML basic string (JSON string syntax is a subset of it)."""
    return json.dumps(value, ensure_ascii=False)


def _array(values: Sequence[str]) -> str:
    """Render a TOML array of strings, one per line."""
    if not values:
        return "[]"
    return "[\n" + "".join(f"  {_string(value)},\n" for value in values) + "]"


def _people(entries: Sequence[dict[str, str]]) -> str:
    """Render a TOML array of inline ``{name, email}`` tables."""
    rendered = []
    for entry in entries:
        fields = ", ".join(f"{key} = {_string(entry[key])}" for key in sorted(entry))
        rendered.append(f"  {{{fields}}},\n")
    return "[\n" + "".join(rendered) + "]"


def _core_requirement(distributions, version: str) -> str:
    """Return the requirement every non-core distribution has on the core."""
    # A floor and no ceiling: a part imports nothing from the core, so no
    # newer core can break it, while an older core might not know the part
    # exists (its install hints and its ``doctor`` report come from the map
    # the core ships).
    return f"{distributions.CORE}>={version}"


def _build_requires(package, meta: RootMetadata) -> list[str]:
    """Return a distribution's build requirements."""
    return list(registry.BUILD_REQUIRES) + inherit_requirements(
        package.build_inherit, meta.build_requires, "[build-system].requires"
    )


def _dependencies(package, distributions, meta: RootMetadata) -> list[str]:
    """Return a distribution's ``dependencies``."""
    lines: list[str] = []
    if package.distribution != distributions.CORE:
        lines.append(_core_requirement(distributions, meta.version))
    lines.extend(inherit_requirements(package.inherit, meta.dependencies))
    lines.extend(package.requires)
    return lines


def _optional_dependencies(
    package, distributions, meta: RootMetadata
) -> dict[str, list[str]]:
    """Return a distribution's ``optional-dependencies``."""
    groups: dict[str, list[str]] = {}
    full = distributions.FULL
    for name in package.extras:
        if name not in meta.extras:
            raise ValueError(
                f"{package.distribution}: extra {name!r} is not declared in the "
                "root [project.optional-dependencies]"
            )
        for requirement in meta.extras[name]:
            if requirement_name(requirement) == full:
                raise ValueError(
                    f"{package.distribution}: root extra {name!r} requires "
                    f"{requirement!r}, which would install the full distribution; "
                    "it cannot be re-exported by a partial one"
                )
        groups[name] = list(meta.extras[name])
    for name, siblings in package.siblings:
        if name in groups:
            raise ValueError(
                f"{package.distribution}: extra {name!r} is both a root extra and "
                "a sibling extra"
            )
        for sibling in siblings:
            distributions.get(sibling)  # KeyError names the unknown distribution
        groups[name] = [f"{sibling}>={meta.version}" for sibling in siblings]
    return groups


_PYTHON_VERSION_CLASSIFIER = re.compile(
    r"^Programming Language :: Python :: (\d+\.\d+)$"
)


def _classifiers(package, meta: RootMetadata) -> list[str]:
    """
    Return a distribution's classifiers: the inherited ones plus its own.

    A ``Programming Language :: Python :: X.Y`` classifier is inherited only
    for the versions the distribution's ``requires-python`` admits, so the two
    statements about supported versions cannot contradict each other.
    """
    floor = package.requires_python or meta.requires_python
    inherited = []
    for classifier in meta.classifiers:
        if not classifier.startswith(registry.CLASSIFIER_PREFIXES):
            continue
        version = _PYTHON_VERSION_CLASSIFIER.match(classifier)
        if version is not None and not registry.python_satisfies(
            floor, version.group(1)
        ):
            continue
        inherited.append(classifier)
    return inherited + [c for c in package.classifiers if c not in inherited]


def render_pyproject(package, distributions, meta: RootMetadata) -> str:
    """
    Render a distribution's ``pyproject.toml``.

    Parameters
    ----------
    package : registry.Package
        The distribution's packaging facts.
    distributions : module
        The distribution map (``scikitplot._distributions``).
    meta : RootMetadata
        Inherited root metadata.

    Returns
    -------
    str
        The file content.

    Raises
    ------
    ValueError
        If the registry names a dependency or an extra the root does not
        declare, or re-exports an extra that would install the full
        distribution.
    """
    dist = distributions.get(package.distribution)
    directory = registry.directory_of(dist.name)
    lines = [
        f"# {GENERATED_NOTICE}",
        "#",
        f"# Package metadata of `{dist.name}`: a partial distribution of the",
        "# `scikitplot` import package. Which files it ships is decided by",
        "# scikitplot/_distributions.py; setup.py stages them at build time.",
        "",
        "[build-system]",
        f"requires = {_array(_build_requires(package, meta))}",
        'build-backend = "setuptools.build_meta"',
        "",
        "[project]",
        f"name = {_string(dist.name)}",
        f"version = {_string(meta.version)}",
        f"description = {_string(dist.summary)}",
        (
            f"readme = {{file = {_string(readme_name(directory))}, "
            'content-type = "text/markdown"}'
        ),
        f"requires-python = {_string(package.requires_python or meta.requires_python)}",
        # The licence is declared by setup.py. Its two spellings do not
        # overlap: an SPDX string needs setuptools >= 77, which does not exist
        # for Python 3.8, and the older table form stops being accepted in
        # 2027. setup.py picks the one the running setuptools understands.
        'dynamic = ["license"]',
        f"authors = {_people(meta.authors)}",
        f"maintainers = {_people(meta.maintainers)}",
        f"keywords = {_array(package.keywords)}",
        f"classifiers = {_array(_classifiers(package, meta))}",
        f"dependencies = {_array(_dependencies(package, distributions, meta))}",
    ]
    optional = _optional_dependencies(package, distributions, meta)
    if optional:
        lines += ["", "[project.optional-dependencies]"]
        lines += [f"{name} = {_array(reqs)}" for name, reqs in optional.items()]
    lines += ["", "[project.urls]"]
    lines += [f"{name} = {_string(url)}" for name, url in meta.urls.items()]
    if package.scripts:
        lines += ["", "[project.scripts]"]
        lines += [
            f"{name} = {_string(target)}" for name, target in meta.scripts.items()
        ]
    lines += [
        "",
        "[tool.setuptools]",
        "# Files are listed explicitly by setup.py; MANIFEST.in decides the sdist only.",
        "include-package-data = false",
        "",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# setup.py, MANIFEST.in
# ---------------------------------------------------------------------------

_SETUP_TEMPLATE = '''\
# @@NOTICE@@
#
# flake8: noqa: D213
#
# Authors: The scikit-plots developers
# SPDX-License-Identifier: BSD-3-Clause

"""
Build script of ``@@DISTRIBUTION@@``.

``pyproject.toml`` carries the metadata. This script does the one thing
metadata cannot express: it puts the files this distribution owns in front of
the build.

* Inside the repository it copies them from the one ``scikitplot`` source tree
  (``libs/_tools/staging.py`` decides which, from
  ``scikitplot/_distributions.py``) and removes the copy when the build exits.
* Inside an unpacked source distribution the files are already here, and
  nothing is copied.

Either way the package list and the data files are read from what is on disk,
so a wheel built from the repository and one built from the sdist are the same
wheel.
"""

from __future__ import annotations

import atexit
import glob
import importlib.util
import os
import sys
from pathlib import Path

import setuptools
from setuptools import Extension, setup
from setuptools.command.build_ext import build_ext

HERE = Path(__file__).resolve().parent
DISTRIBUTION = "@@DISTRIBUTION@@"
PACKAGE = "scikitplot"
#: SPDX licence expression covering every file this distribution ships.
LICENSE = "@@LICENSE@@"
#: First setuptools major release that understands ``license_expression``
#: (PEP 639); see ``_license_options``.
PEP639_SETUPTOOLS_MAJOR = 77
#: First Cython release with the ``freethreading_compatible`` directive.
CYTHON_FREETHREADING = (3, 1)
#: Compiled extension modules, as declared in libs/_tools/registry.py.
EXTENSIONS = @@EXTENSIONS@@
#: Cython directives of the full distribution's build (root meson.build).
CYTHON_DIRECTIVES = {
    "language_level": 3,
    "wraparound": False,
    "cdivision": True,
    "initializedcheck": False,
    "nonecheck": False,
    "profile": False,
}


def _refuse_editable() -> None:
    """Stop an editable install, which cannot work with staged files."""
    if {"editable_wheel", "develop"} & set(sys.argv[1:]):
        raise SystemExit(
            f"{DISTRIBUTION} cannot be installed in editable mode: its files are "
            "staged for the build and removed afterwards, so an editable install "
            "would point at nothing.\\n"
            "To develop, install the repository root in editable mode instead:\\n"
            "    pip install -e ."
        )


def _stage_from_repository() -> None:
    """Stage the owned files when building from the repository."""
    if (HERE / "PKG-INFO").is_file():
        return  # an unpacked sdist is self-contained
    tools = HERE.parent / "_tools" / "staging.py"
    if not tools.is_file():
        return  # neither; the guard below explains what is wrong
    spec = importlib.util.spec_from_file_location("_skplt_libs_staging", tools)
    staging = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(staging)
    staging.stage(DISTRIBUTION, HERE)
    if os.environ.get("SKPLT_LIBS_KEEP_STAGED") != "1":
        atexit.register(staging.unstage, HERE)


def _packages() -> list:
    """Return every Python package on disk under ``scikitplot/``, sorted."""
    found = []
    for current, dirnames, filenames in os.walk(HERE / PACKAGE):
        dirnames.sort()
        if "__init__.py" in filenames:
            found.append(".".join(Path(current).relative_to(HERE).parts))
    return sorted(found)


def _package_data(packages: list) -> dict:
    """
    Return the non-module files of each outermost package.

    Every file under ``scikitplot/`` reaches the wheel exactly one way: a
    ``.py`` file in a package directory is a module of that package, and any
    other file is data of the outermost package above it. The paths are
    listed, not globbed, so hidden directories are included and no file name
    is read as a pattern.
    """
    known = set(packages)
    data = {}
    for package in packages:
        parts = package.split(".")
        if any(".".join(parts[:n]) in known for n in range(1, len(parts))):
            continue  # covered by an outer package
        base = HERE.joinpath(*parts)
        files = []
        for current, dirnames, filenames in os.walk(base):
            dirnames.sort()
            is_package = "__init__.py" in filenames
            for filename in sorted(filenames):
                if is_package and filename.endswith(".py"):
                    continue
                relative = (Path(current) / filename).relative_to(base).as_posix()
                files.append(glob.escape(relative))
        data[package] = files
    return data


def _require_every_file_shipped(data: dict) -> None:
    """
    Stop the build if a file on disk would not reach the wheel.

    Everything under an outermost package is shipped, as a module or as data.
    A file outside every package directory is neither, and the build would
    drop it without a word. That can only happen when the distribution map
    gives this distribution a file whose directory it does not own, so it is
    reported as the mistake it is.
    """
    roots = [HERE.joinpath(*package.split(".")) for package in data]
    orphans = []
    for current, _dirnames, filenames in os.walk(HERE / PACKAGE):
        here = Path(current)
        if any(root == here or root in here.parents for root in roots):
            continue
        orphans.extend((here / name).relative_to(HERE).as_posix() for name in filenames)
    if orphans:
        raise SystemExit(
            f"{DISTRIBUTION}: these files are not inside any of its packages "
            f"({sorted(data)}) and would be left out of the wheel:\\n  "
            + "\\n  ".join(sorted(orphans))
            + "\\nGive the distribution the package that contains them, or remove "
            "them from scikitplot/_distributions.py."
        )


def _license_options() -> dict:
    """
    Return the licence in the form the running setuptools understands.

    setuptools 77 introduced ``license_expression`` (PEP 639) and deprecated
    every older spelling; releases before 77, the only ones available for
    Python 3.8, know only ``license``. The expression is the same either way.
    """
    if int(setuptools.__version__.split(".")[0]) >= PEP639_SETUPTOOLS_MAJOR:
        return {"license_expression": LICENSE}
    return {"license": LICENSE}


def _render_templates(templates) -> None:
    """
    Render Tempita templates (``name.in`` to ``name``) for the build.

    Cython is imported here, not at the top: it is a build requirement only
    of the distributions that declare an extension.
    """
    from Cython import Tempita  # noqa: PLC0415

    for template in templates:
        source = HERE / template
        target = source.with_name(source.name[: -len(".in")])
        target.write_text(
            Tempita.sub(source.read_text(encoding="utf-8")), encoding="utf-8"
        )


def _translate_cython(extension) -> None:
    """Translate an extension's ``.pyx`` sources to C++, in place."""
    if not any(source.endswith(".pyx") for source in extension.sources):
        return
    import Cython  # noqa: PLC0415
    from Cython.Build import cythonize  # noqa: PLC0415

    release = tuple(int(part) for part in Cython.__version__.split(".")[:2])
    directives = dict(CYTHON_DIRECTIVES)
    if release >= CYTHON_FREETHREADING:
        directives["freethreading_compatible"] = True
    (translated,) = cythonize([extension], compiler_directives=directives, force=True)
    extension.sources = translated.sources


def _extension_options() -> dict:
    """Return the ``setup()`` options for the compiled extensions, if any."""
    if not EXTENSIONS:
        return {}
    declared = {entry["name"]: entry for entry in EXTENSIONS}

    class BuildExt(build_ext):
        """
        Generate the sources, then compile them the way the full build does.

        Nothing is generated until an extension is actually built, so
        metadata-only steps (``egg_info``, ``sdist``) need neither Cython nor
        a compiler.
        """

        def build_extensions(self):
            msvc = self.compiler.compiler_type == "msvc"
            for extension in self.extensions:
                entry = declared[extension.name]
                _render_templates(entry["templates"])
                _translate_cython(extension)
                standard = entry["cxx_standard"]
                if msvc:
                    extension.extra_compile_args += [
                        f"/std:{standard}",
                        # MSVC keeps the ``__cplusplus`` macro at 199711L
                        # whatever ``/std`` says, unless it is told to
                        # report the real value. The vendored Annoy header
                        # checks that macro and stops with "requires at
                        # least C++17" without this.
                        "/Zc:__cplusplus",
                        "/O2",
                        "/bigobj",
                        "/permissive-",
                    ]
                    extension.define_macros += [
                        ("_CRT_SECURE_NO_WARNINGS", None),
                        ("_USE_MATH_DEFINES", None),
                    ]
                else:
                    extension.extra_compile_args += [
                        f"-std={standard}",
                        "-O3",
                        # A release build carries no debug information. Many
                        # interpreters put -g in the flags they hand to
                        # extensions, which multiplies the size of this
                        # template-heavy module several times over.
                        "-g0",
                        "-fno-strict-aliasing",
                    ]
            super().build_extensions()

    return {
        "ext_modules": [
            Extension(
                entry["name"],
                sources=list(entry["sources"]),
                include_dirs=list(entry["include_dirs"]),
                define_macros=[tuple(macro) for macro in entry["define_macros"]],
                language="c++",
            )
            for entry in EXTENSIONS
        ],
        "cmdclass": {"build_ext": BuildExt},
    }


_refuse_editable()
_stage_from_repository()
PACKAGES = _packages()
if not PACKAGES:
    raise SystemExit(
        f"{DISTRIBUTION}: no Python package found under {HERE / PACKAGE}, so this "
        "build would produce a wheel with no code in it.\\n"
        "Build from a checkout of the scikit-plots repository (this directory "
        "must be libs/<name> beside libs/_tools), or from an sdist of this "
        "distribution."
    )

PACKAGE_DATA = _package_data(PACKAGES)
_require_every_file_shipped(PACKAGE_DATA)

setup(
    packages=PACKAGES,
    package_data=PACKAGE_DATA,
    **_license_options(),
    **_extension_options(),
)
'''


def _count(number: int, noun: str) -> str:
    """Return ``"a <noun>"`` for one and ``"<number> <noun>s"`` otherwise."""
    return f"a {noun}" if number == 1 else f"{number} {noun}s"


def _python_literal(value, indent: int = 0) -> str:
    """
    Render plain data as Python source that a formatter leaves alone.

    Parameters
    ----------
    value : None, bool, int, str, list, tuple or dict
        The data. Tuples are rendered as lists; dictionary keys must be
        strings.
    indent : int, default=0
        Indentation, in spaces, of the line the literal starts on.

    Returns
    -------
    str
        The literal. Every non-empty container has one element per line and
        a trailing comma, which is the one layout ``ruff format`` and
        ``black`` both keep as it is whatever its width.

    Raises
    ------
    TypeError
        If ``value`` holds anything else, or a dictionary key is not a string.

    Notes
    -----
    Developer note: the result must not depend on the interpreter that runs
    the generator, or ``check`` would report drift between machines. Strings
    therefore go through :func:`json.dumps` (ASCII, double quotes), whose
    escapes are all valid Python, and nothing here uses :func:`repr`.
    """
    if value is None or isinstance(value, (bool, int, str)):
        # json.dumps spells None, True and False the JSON way; str() does not.
        return (
            json.dumps(value, ensure_ascii=True)
            if isinstance(value, str)
            else str(value)
        )
    pad = " " * (indent + 4)
    if isinstance(value, (list, tuple)):
        opening, closing = "[", "]"
        items = [_python_literal(item, indent + 4) for item in value]
    elif isinstance(value, dict):
        opening, closing = "{", "}"
        items = []
        for key, item in value.items():
            if not isinstance(key, str):
                raise TypeError(
                    f"dictionary keys must be str, got {type(key).__name__}: {key!r}"
                )
            items.append(
                f"{json.dumps(key, ensure_ascii=True)}: "
                f"{_python_literal(item, indent + 4)}"
            )
    else:
        raise TypeError(
            f"cannot render {type(value).__name__} as a Python literal: {value!r}"
        )
    if not items:
        return opening + closing
    body = "".join(f"{pad}{item},\n" for item in items)
    return f"{opening}\n{body}{' ' * indent}{closing}"


def render_setup(package) -> str:
    """
    Render a distribution's ``setup.py``.

    Parameters
    ----------
    package : registry.Package
        The distribution's packaging facts.

    Returns
    -------
    str
        The file content. It is the same for every distribution except for
        the distribution name, the licence and the extension list.

    Raises
    ------
    SyntaxError
        If the rendered script is not valid Python 3.8.
    """
    extensions = _python_literal([ext._asdict() for ext in package.extensions])
    source = (
        _SETUP_TEMPLATE.replace("@@NOTICE@@", GENERATED_NOTICE)
        .replace("@@DISTRIBUTION@@", package.distribution)
        .replace("@@LICENSE@@", package.license)
        .replace("@@EXTENSIONS@@", extensions)
    )
    # A build script that does not parse fails inside the build backend, far
    # from here and with a worse message. Parse it now, with the grammar of
    # the oldest supported interpreter.
    ast.parse(
        source, filename=f"{package.distribution}/setup.py", feature_version=(3, 8)
    )
    return source


def render_manifest(package) -> str:
    """
    Render a distribution's ``MANIFEST.in`` (what its source distribution holds).

    Parameters
    ----------
    package : registry.Package
        The distribution's packaging facts.

    Returns
    -------
    str
        The file content.
    """
    directory = registry.directory_of(package.distribution)
    # No exclusions are needed: the staged tree holds exactly the owned files
    # (staging leaves caches and native build outputs out), so grafting it is
    # exact.
    return "\n".join(
        [
            f"# {GENERATED_NOTICE}",
            f"include {staging.LICENSE_NAME}",
            "include README.md",
            f"include {readme_name(directory)}",
            f"graft {staging.PACKAGE_NAME}",
            "",
        ]
    )


# ---------------------------------------------------------------------------
# READMEs
# ---------------------------------------------------------------------------


def _install_block(package, distributions, meta: RootMetadata) -> list[str]:
    """Return the installation section of a package description."""
    name = package.distribution
    lines = ["## Install", "", "```sh", f"pip install {name}", "```", ""]
    optional = _optional_dependencies(package, distributions, meta)
    if optional:
        lines += ["Optional extras:", ""]
        for extra, requirements in optional.items():
            lines.append(
                f'- `pip install "{name}[{extra}]"`: '
                + ", ".join(f"`{requirement}`" for requirement in requirements)
            )
        lines.append("")
    return lines


def render_readme_package(package, distributions, meta: RootMetadata) -> str:
    """
    Render the package description shown on the package index.

    Parameters
    ----------
    package : registry.Package
        The distribution's packaging facts.
    distributions : module
        The distribution map.
    meta : RootMetadata
        Inherited root metadata.

    Returns
    -------
    str
        Markdown.
    """
    dist = distributions.get(package.distribution)
    full, core = distributions.FULL, distributions.CORE
    owned = [f"`scikitplot.{tree.replace('/', '.')}`" for tree in dist.trees]
    if dist.name == core:
        owned.insert(0, "the root `scikitplot` package")
    lines = [
        f"<!-- {GENERATED_NOTICE} -->",
        "",
        f"# {dist.name}",
        "",
        dist.summary,
        "",
        (
            f"This is a **partial distribution** of [`{full}`]({meta.urls['repository']}): "
            f"it ships {', '.join(owned)} and nothing else, built from the same source "
            f"tree and with the same version as `{full}`."
        ),
        "",
    ]
    if package.extensions:
        lines += [
            (
                f"It contains {_count(len(package.extensions), 'compiled extension')}. "
                "Wheels need no compiler; building from source needs a C++ "
                "compiler that supports "
                f"{' and '.join(sorted({e.cxx_standard.upper() for e in package.extensions}))}."
            ),
            "",
        ]
    else:
        lines += ["It is pure Python: no compiler is needed to install it.", ""]
    lines += _install_block(package, distributions, meta)
    lines += [
        (
            "Every spelling an installer accepts names the same project, so "
            f"`{dist.name.replace('-', '_')}` installs it too."
        ),
        "",
        "## Use",
        "",
        f"```{'python' if package.example_language == 'python' else 'sh'}",
        package.example.rstrip("\n"),
        "```",
        "",
        "## How it fits with the other distributions",
        "",
    ]
    if dist.name == core:
        lines += [
            (
                f"`{core}` is the core every other partial distribution depends on. It "
                "owns the root `scikitplot/__init__.py`, logging and the `scikitplot` "
                "command line, and has no dependencies."
            ),
        ]
    else:
        lines += [
            (
                f"It depends on `{core}`, which owns the root `scikitplot/__init__.py`, "
                "logging and the `scikitplot` command line."
            ),
        ]
    lines += [
        "",
        (
            "Partial distributions compose: install any of them side by side and they "
            "form one `scikitplot` package. No file belongs to two of them, so "
            "uninstalling one never breaks another."
        ),
        "",
        (
            f"Do not install a partial distribution together with `{full}`: `{full}` "
            "already contains all of them and would own the same files. Run "
            "`scikitplot doctor` to see what is installed and whether it is coherent."
        ),
        "",
        "## Links",
        "",
    ]
    lines += [f"- {name}: {url}" for name, url in meta.urls.items()]
    lines.append("")
    return "\n".join(lines)


def render_readme_directory(package, distributions) -> str:
    """
    Render the README of a ``libs/<name>`` directory, for people in the repository.

    Parameters
    ----------
    package : registry.Package
        The distribution's packaging facts.
    distributions : module
        The distribution map.

    Returns
    -------
    str
        Markdown.
    """
    dist = distributions.get(package.distribution)
    directory = registry.directory_of(dist.name)
    owned = [f"`scikitplot/{tree}/`" for tree in dist.trees]
    owned += [f"`scikitplot/{name}`" for name in dist.files]
    return "\n".join(
        [
            f"<!-- {GENERATED_NOTICE} -->",
            "",
            f"# {dist.name}",
            "",
            dist.summary,
            "",
            "## Files in this directory",
            "",
            "| File | Purpose |",
            "| --- | --- |",
            "| `pyproject.toml` | Package metadata. Generated. |",
            "| `setup.py` | Stages the owned files for the build. Generated. |",
            "| `MANIFEST.in` | Contents of the source distribution. Generated. |",
            f"| `{readme_name(directory)}` | Package description for the index. Generated. |",
            "",
            (
                "There is no copy of the source here. The build stages these paths "
                "from the repository's `scikitplot/` directory and removes them again:"
            ),
            "",
            *[f"- {path}" for path in owned],
            "",
            "## Build and install",
            "",
            "```sh",
            "# from a local clone of the repository",
            f"pip install ./libs/{directory}",
            f"python -m build libs/{directory}",
            "",
            "# straight from GitHub",
            (
                "pip install "
                f'"git+https://github.com/scikit-plots/scikit-plots.git#subdirectory=libs/{directory}"'
            ),
            "```",
            "",
            (
                "To change what this distribution ships, edit "
                "`scikitplot/_distributions.py`; to change how it is packaged, edit "
                "`libs/_tools/registry.py`. Then run `python -m libs._tools generate`."
            ),
            "",
        ]
    )


def render_libs_readme(packages, distributions) -> str:
    """
    Render ``libs/README.md``, the overview of every partial distribution.

    Parameters
    ----------
    packages : sequence of registry.Package
        Every package, in order.
    distributions : module
        The distribution map.

    Returns
    -------
    str
        Markdown.
    """
    rows = []
    for package in packages:
        dist = distributions.get(package.distribution)
        directory = registry.directory_of(dist.name)
        ships = ", ".join(f"`{tree.replace('/', '.')}`" for tree in dist.trees)
        kind = "compiled (C++)" if package.extensions else "pure Python"
        rows.append(
            f"| [`{directory}/`]({directory}/) | `{dist.name}` | {ships} | {kind} |"
        )
    return "\n".join(
        [
            f"<!-- {GENERATED_NOTICE} -->",
            "",
            "# Partial distributions of scikit-plots",
            "",
            (
                f"`{distributions.FULL}` is one large package that needs a compiler "
                "toolchain to build. The directories here publish focused parts of the "
                "same `scikitplot` import package as separate, small distributions, in "
                "the spirit of `mlflow-skinny`."
            ),
            "",
            "| Directory | Distribution | Ships `scikitplot.` | Build |",
            "| --- | --- | --- | --- |",
            *rows,
            "",
            "## How it works",
            "",
            (
                "- **One source tree.** Nothing is copied into `libs/` permanently. Each "
                "`setup.py` stages the files its distribution owns at build time and "
                "removes them when the build exits."
            ),
            (
                "- **One owner per file.** `scikitplot/_distributions.py` says which "
                "distribution owns which path, and no path has two owners, so the "
                f"distributions install side by side. `{distributions.CORE}` owns the "
                "root `__init__.py`; the others depend on it."
            ),
            (
                "- **Generated metadata.** Every file in a lib directory is generated "
                "from `scikitplot/_distributions.py`, `libs/_tools/registry.py` and the "
                "root `pyproject.toml`. Version specifiers are inherited from the root, "
                "so they cannot drift."
            ),
            "",
            "## Commands",
            "",
            "Run from the repository root.",
            "",
            "```sh",
            "python -m libs._tools list       # distributions and what they own",
            "python -m libs._tools generate   # rewrite the generated files",
            "python -m libs._tools check      # fail if generated files are stale",
            "python -m libs._tools build      # build every sdist and wheel",
            "python -m libs._tools verify     # build, then install and test them",
            "```",
            "",
            "## See also",
            "",
            "- https://github.com/mlflow/mlflow/blob/master/libs/skinny/README.md",
            "- https://github.com/mlflow/mlflow/blob/master/libs/skinny/README_SKINNY.md",
            "",
        ]
    )


def render_gitignore() -> str:
    """
    Render ``libs/.gitignore``.

    Returns
    -------
    str
        The file content.

    Notes
    -----
    **Developer.** The first rule is kept from the hand-written file: the
    repository ignores ``mlflow`` directories elsewhere, and ``libs/mlflow``
    must not be caught by that. The rest is what a build can leave behind if
    it is interrupted before it cleans up.
    """
    # No trailing slash on the staged package: with one, the rule matches a
    # directory only, and the link the earlier symlink layout put at
    # ``libs/<name>/scikitplot`` is a file to git, so it was not ignored and
    # could be committed (it then fails "build leaves nothing behind").
    residue = [f"/*/{staging.PACKAGE_NAME}", f"/*/{staging.LICENSE_NAME}"]
    residue += [f"/*/{name}/" for name in staging.RESIDUE_DIR_NAMES]
    residue += ["/*/dist/", "/*/*.egg-info/", "__pycache__/"]
    # What ``npm ci`` installs for the Pyodide probe (libs/_tools/pyodide/).
    residue += ["node_modules/"]
    return "\n".join(
        [
            f"# {GENERATED_NOTICE}",
            "!mlflow",
            "# Staged sources and build residue of the partial distributions.",
            *residue,
            "",
        ]
    )


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------


def _validate(distributions, packages: dict[str, object], root: Path) -> None:
    """Check the two registries agree with each other and with the tree."""
    declared = [dist.name for dist in distributions.DISTRIBUTIONS]
    if sorted(declared) != sorted(packages):
        missing = sorted(set(declared) - set(packages))
        unknown = sorted(set(packages) - set(declared))
        raise ValueError(
            "scikitplot/_distributions.py and libs/_tools/registry.py disagree: "
            f"without packaging facts: {missing}; without an ownership entry: {unknown}"
        )
    for name in declared:
        if distributions.canonicalize_name(name) != name:
            raise ValueError(f"{name!r} is not in canonical form")
        registry.directory_of(name)
    staging.check_ownership(distributions.DISTRIBUTIONS, root / staging.PACKAGE_NAME)

    libs = root / "libs"
    expected = {registry.directory_of(name) for name in declared}
    present = {
        path.name
        for path in libs.iterdir()
        if path.is_dir() and not path.name.startswith(("_", "."))
    }
    stray = sorted(present - expected)
    if stray:
        raise ValueError(
            f"libs/ has directories that are not partial distributions: {stray}. "
            "Declare them in scikitplot/_distributions.py and "
            "libs/_tools/registry.py, or remove them."
        )


def expected_files(root: Path | None = None) -> dict[str, str]:
    """
    Return every generated file and its content.

    Parameters
    ----------
    root : pathlib.Path, optional
        Repository root. Defaults to the repository this file belongs to.

    Returns
    -------
    dict of str to str
        POSIX path relative to the repository root, to file content.

    Raises
    ------
    ValueError
        If the inputs are inconsistent: the two registries disagree, a file
        has two owners, a dependency or extra is not declared in the root, or
        ``libs/`` holds a directory that is not a declared distribution.
    FileNotFoundError
        If an owned path does not exist.
    """
    root = staging.repo_root() if root is None else Path(root)
    distributions = staging.load_distributions(root)
    packages = registry.by_distribution()
    _validate(distributions, packages, root)
    meta = read_root_metadata(root)

    files: dict[str, str] = {
        "libs/README.md": render_libs_readme(list(packages.values()), distributions),
        "libs/.gitignore": render_gitignore(),
    }
    for dist in distributions.DISTRIBUTIONS:
        package = packages[dist.name]
        directory = registry.directory_of(dist.name)
        base = f"libs/{directory}"
        files[f"{base}/pyproject.toml"] = render_pyproject(package, distributions, meta)
        files[f"{base}/setup.py"] = render_setup(package)
        files[f"{base}/MANIFEST.in"] = render_manifest(package)
        files[f"{base}/README.md"] = render_readme_directory(package, distributions)
        files[f"{base}/{readme_name(directory)}"] = render_readme_package(
            package, distributions, meta
        )
    return files


def _stale(root: Path, files: dict[str, str]) -> list[str]:
    """Return the generated paths whose content on disk differs."""
    stale = []
    for relative, content in files.items():
        path = root / relative
        if not path.is_file() or path.read_bytes() != content.encode("utf-8"):
            stale.append(relative)
    return stale


def check(root: Path | None = None) -> list[str]:
    """
    Return the generated files that are missing or out of date.

    Parameters
    ----------
    root : pathlib.Path, optional
        Repository root.

    Returns
    -------
    list of str
        Stale paths relative to the repository root; empty when everything is
        up to date. Nothing is written.
    """
    root = staging.repo_root() if root is None else Path(root)
    return _stale(root, expected_files(root))


def generate(root: Path | None = None) -> list[str]:
    """
    Write every generated file that is missing or out of date.

    Parameters
    ----------
    root : pathlib.Path, optional
        Repository root.

    Returns
    -------
    list of str
        The paths written, relative to the repository root; empty when
        everything was already up to date.

    Notes
    -----
    **Developer.** Files are written as UTF-8 with LF line endings on every
    platform, so the output, and therefore ``check``, does not depend on where
    it ran.
    """
    root = staging.repo_root() if root is None else Path(root)
    files = expected_files(root)
    written = _stale(root, files)
    for relative in written:
        path = root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(files[relative].encode("utf-8"))
    return written
