# Generated by libs/_tools. Do not edit; run: python -m libs._tools generate
#
# flake8: noqa: D213
#
# Authors: The scikit-plots developers
# SPDX-License-Identifier: BSD-3-Clause

"""
Build script of ``scikit-plots-skinny``.

``pyproject.toml`` carries the metadata. This script does the one thing
metadata cannot express: it puts the files this distribution owns in front of
the build.

* Inside the repository it copies them from the one ``scikitplot`` source tree
  (``libs/_tools/staging.py`` decides which, from
  ``scikitplot/_distributions.py``) and removes the copy when the build exits.
* Inside an unpacked source distribution the files are already here, and
  nothing is copied.

Either way the package list and the data files are read from what is on disk,
so a wheel built from the repository and one built from the sdist are the same
wheel.
"""

from __future__ import annotations

import atexit
import glob
import importlib.util
import os
import sys
import sysconfig
from pathlib import Path

import setuptools
from setuptools import Extension, setup
from setuptools.command.build_ext import build_ext

HERE = Path(__file__).resolve().parent
DISTRIBUTION = "scikit-plots-skinny"
PACKAGE = "scikitplot"
#: SPDX licence expression covering every file this distribution ships.
LICENSE = "BSD-3-Clause"
#: First setuptools major release that understands ``license_expression``
#: (PEP 639); see ``_license_options``.
PEP639_SETUPTOOLS_MAJOR = 77
#: First Cython release with the ``freethreading_compatible`` directive.
CYTHON_FREETHREADING = (3, 1)
#: Compiled extension modules, as declared in libs/_tools/registry.py.
EXTENSIONS = []
#: Environment variable with which the builder asks for the multithreaded
#: code of an extension: ``1`` compiles it in, ``0`` or unset leaves it out.
#: Unset means out because that is what the full distribution's Meson build
#: does, and the two builds must produce the same behaviour until both change.
THREADS_ENV = "SKPLT_BUILD_THREADS"
#: Prefixes of ``sysconfig.get_platform()`` for targets without threads: a
#: WebAssembly interpreter (Pyodide, JupyterLite, WASI) runs on one thread,
#: and starting a second one fails at run time, not at build time.
PLATFORMS_WITHOUT_THREADS = ("emscripten", "wasi")
#: Cython directives of the full distribution's build (root meson.build).
CYTHON_DIRECTIVES = {
    "language_level": 3,
    "wraparound": False,
    "cdivision": True,
    "initializedcheck": False,
    "nonecheck": False,
    "profile": False,
}


def _refuse_editable() -> None:
    """Stop an editable install, which cannot work with staged files."""
    if {"editable_wheel", "develop"} & set(sys.argv[1:]):
        raise SystemExit(
            f"{DISTRIBUTION} cannot be installed in editable mode: its files are "
            "staged for the build and removed afterwards, so an editable install "
            "would point at nothing.\n"
            "To develop, install the repository root in editable mode instead:\n"
            "    pip install -e ."
        )


def _stage_from_repository() -> None:
    """Stage the owned files when building from the repository."""
    if (HERE / "PKG-INFO").is_file():
        return  # an unpacked sdist is self-contained
    tools = HERE.parent / "_tools" / "staging.py"
    if not tools.is_file():
        return  # neither; the guard below explains what is wrong
    spec = importlib.util.spec_from_file_location("_skplt_libs_staging", tools)
    staging = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(staging)
    staging.stage(DISTRIBUTION, HERE)
    if os.environ.get("SKPLT_LIBS_KEEP_STAGED") != "1":
        atexit.register(staging.unstage, HERE)


def _packages() -> list:
    """Return every Python package on disk under ``scikitplot/``, sorted."""
    found = []
    for current, dirnames, filenames in os.walk(HERE / PACKAGE):
        dirnames.sort()
        if "__init__.py" in filenames:
            found.append(".".join(Path(current).relative_to(HERE).parts))
    return sorted(found)


def _package_data(packages: list) -> dict:
    """
    Return the non-module files of each outermost package.

    Every file under ``scikitplot/`` reaches the wheel exactly one way: a
    ``.py`` file in a package directory is a module of that package, and any
    other file is data of the outermost package above it. The paths are
    listed, not globbed, so hidden directories are included and no file name
    is read as a pattern.
    """
    known = set(packages)
    data = {}
    for package in packages:
        parts = package.split(".")
        if any(".".join(parts[:n]) in known for n in range(1, len(parts))):
            continue  # covered by an outer package
        base = HERE.joinpath(*parts)
        files = []
        for current, dirnames, filenames in os.walk(base):
            dirnames.sort()
            is_package = "__init__.py" in filenames
            for filename in sorted(filenames):
                if is_package and filename.endswith(".py"):
                    continue
                relative = (Path(current) / filename).relative_to(base).as_posix()
                files.append(glob.escape(relative))
        data[package] = files
    return data


def _require_every_file_shipped(data: dict) -> None:
    """
    Stop the build if a file on disk would not reach the wheel.

    Everything under an outermost package is shipped, as a module or as data.
    A file outside every package directory is neither, and the build would
    drop it without a word. That can only happen when the distribution map
    gives this distribution a file whose directory it does not own, so it is
    reported as the mistake it is.
    """
    roots = [HERE.joinpath(*package.split(".")) for package in data]
    orphans = []
    for current, _dirnames, filenames in os.walk(HERE / PACKAGE):
        here = Path(current)
        if any(root == here or root in here.parents for root in roots):
            continue
        orphans.extend((here / name).relative_to(HERE).as_posix() for name in filenames)
    if orphans:
        raise SystemExit(
            f"{DISTRIBUTION}: these files are not inside any of its packages "
            f"({sorted(data)}) and would be left out of the wheel:\n  "
            + "\n  ".join(sorted(orphans))
            + "\nGive the distribution the package that contains them, or remove "
            "them from scikitplot/_distributions.py."
        )


def _license_options() -> dict:
    """
    Return the licence in the form the running setuptools understands.

    setuptools 77 introduced ``license_expression`` (PEP 639) and deprecated
    every older spelling; releases before 77, the only ones available for
    Python 3.8, know only ``license``. The expression is the same either way.
    """
    if int(setuptools.__version__.split(".")[0]) >= PEP639_SETUPTOOLS_MAJOR:
        return {"license_expression": LICENSE}
    return {"license": LICENSE}


def _render_templates(templates) -> None:
    """
    Render Tempita templates (``name.in`` to ``name``) for the build.

    Cython is imported here, not at the top: it is a build requirement only
    of the distributions that declare an extension.
    """
    from Cython import Tempita  # noqa: PLC0415

    for template in templates:
        source = HERE / template
        target = source.with_name(source.name[: -len(".in")])
        target.write_text(
            Tempita.sub(source.read_text(encoding="utf-8")), encoding="utf-8"
        )


def _translate_cython(extension) -> None:
    """Translate an extension's ``.pyx`` sources to C++, in place."""
    if not any(source.endswith(".pyx") for source in extension.sources):
        return
    import Cython  # noqa: PLC0415
    from Cython.Build import cythonize  # noqa: PLC0415

    release = tuple(int(part) for part in Cython.__version__.split(".")[:2])
    directives = dict(CYTHON_DIRECTIVES)
    if release >= CYTHON_FREETHREADING:
        directives["freethreading_compatible"] = True
    (translated,) = cythonize([extension], compiler_directives=directives, force=True)
    extension.sources = translated.sources


def _threads_enabled(environ=None, platform=None) -> bool:
    """
    Return whether the multithreaded code of the extensions is compiled in.

    Parameters
    ----------
    environ : mapping, optional
        The environment; ``os.environ`` when omitted.
    platform : str, optional
        The platform the build targets; ``sysconfig.get_platform()`` when
        omitted, which is the target's and not the builder's under a
        cross-build.

    Returns
    -------
    bool
        ``True`` when ``SKPLT_BUILD_THREADS`` is ``1``; ``False`` when it is
        ``0`` or unset.

    Raises
    ------
    SystemExit
        If ``SKPLT_BUILD_THREADS`` is set to anything but ``0`` or ``1`` (a
        build option that is misspelled must not be read as its default), or
        is ``1`` for a target without threads (the wheel would build, and
        fail the first time a second thread is started).
    """
    environ = os.environ if environ is None else environ
    platform = sysconfig.get_platform() if platform is None else platform
    value = environ.get(THREADS_ENV, "").strip()
    if value in ("", "0"):
        return False
    if value != "1":
        raise SystemExit(
            f"{THREADS_ENV}={value!r} is not understood. Set it to 1 (compile "
            "the multithreaded code in), or to 0 or nothing (leave it out)."
        )
    if platform.startswith(PLATFORMS_WITHOUT_THREADS):
        raise SystemExit(
            f"{THREADS_ENV}=1 cannot be honoured for {platform}: this target "
            "has no threads. Unset it, or set it to 0."
        )
    return True


def _extension_options() -> dict:
    """Return the ``setup()`` options for the compiled extensions, if any."""
    if not EXTENSIONS:
        return {}
    declared = {entry["name"]: entry for entry in EXTENSIONS}
    threads = _threads_enabled()

    class BuildExt(build_ext):
        """
        Generate the sources, then compile them the way the full build does.

        Nothing is generated until an extension is actually built, so
        metadata-only steps (``egg_info``, ``sdist``) need neither Cython nor
        a compiler.
        """

        def build_extensions(self):
            msvc = self.compiler.compiler_type == "msvc"
            for extension in self.extensions:
                entry = declared[extension.name]
                _render_templates(entry["templates"])
                _translate_cython(extension)
                standard = entry["cxx_standard"]
                if msvc:
                    extension.extra_compile_args += [
                        f"/std:{standard}",
                        # MSVC keeps the ``__cplusplus`` macro at 199711L
                        # whatever ``/std`` says, unless it is told to
                        # report the real value. The vendored Annoy header
                        # checks that macro and stops with "requires at
                        # least C++17" without this.
                        "/Zc:__cplusplus",
                        "/O2",
                        "/bigobj",
                        "/permissive-",
                    ]
                    extension.define_macros += [
                        ("_CRT_SECURE_NO_WARNINGS", None),
                        ("_USE_MATH_DEFINES", None),
                    ]
                else:
                    extension.extra_compile_args += [
                        f"-std={standard}",
                        "-O3",
                        # A release build carries no debug information. Many
                        # interpreters put -g in the flags they hand to
                        # extensions, which multiplies the size of this
                        # template-heavy module several times over.
                        "-g0",
                        "-fno-strict-aliasing",
                    ]
                if threads and entry["threads_macro"]:
                    extension.define_macros += [(entry["threads_macro"], None)]
                    if not msvc:
                        # Compiling and linking with -pthread is how GCC and
                        # Clang are told a program uses threads. MSVC needs
                        # nothing: its runtime is always the threaded one.
                        extension.extra_compile_args += ["-pthread"]
                        extension.extra_link_args += ["-pthread"]
            super().build_extensions()

    return {
        "ext_modules": [
            Extension(
                entry["name"],
                sources=list(entry["sources"]),
                include_dirs=list(entry["include_dirs"]),
                define_macros=[tuple(macro) for macro in entry["define_macros"]],
                language="c++",
            )
            for entry in EXTENSIONS
        ],
        "cmdclass": {"build_ext": BuildExt},
    }


_refuse_editable()
_stage_from_repository()
PACKAGES = _packages()
if not PACKAGES:
    raise SystemExit(
        f"{DISTRIBUTION}: no Python package found under {HERE / PACKAGE}, so this "
        "build would produce a wheel with no code in it.\n"
        "Build from a checkout of the scikit-plots repository (this directory "
        "must be libs/<name> beside libs/_tools), or from an sdist of this "
        "distribution."
    )

PACKAGE_DATA = _package_data(PACKAGES)
_require_every_file_shipped(PACKAGE_DATA)

setup(
    packages=PACKAGES,
    package_data=PACKAGE_DATA,
    **_license_options(),
    **_extension_options(),
)
