# from __future__ import annotations

from dataclasses import dataclass
from typing import Mapping, Sequence

@dataclass(frozen=True)
class SessionConfig:
    tracking_uri: str | None = ...
    public_tracking_uri: str | None = ...
    registry_uri: str | None = ...
    env_file: str | None = ...
    extra_env: Mapping[str, str] | None = ...
    startup_timeout_s: float = ...
    ensure_reachable: bool = ...
    experiment_name: str | None = ...
    create_experiment_if_missing: bool = ...
    default_run_name: str | None = ...
    default_run_tags: Mapping[str, str] | None = ...

@dataclass(frozen=True)
class ServerConfig:
    host: str = ...
    port: int = ...
    auto_host_in_docker: bool = ...
    docker_host: str = ...
    workers: int | None = ...
    backend_store_uri: str | None = ...
    registry_store_uri: str | None = ...
    default_artifact_root: str | None = ...
    serve_artifacts: bool = ...
    no_serve_artifacts: bool = ...
    artifacts_destination: str | None = ...
    artifacts_only: bool = ...
    allowed_hosts: str | None = ...
    cors_allowed_origins: str | None = ...
    x_frame_options: str | None = ...
    disable_security_middleware: bool = ...
    static_prefix: str | None = ...
    uvicorn_opts: str | None = ...
    gunicorn_opts: str | None = ...
    waitress_opts: str | None = ...
    expose_prometheus: str | None = ...
    app_name: str | None = ...
    dev: bool = ...
    secrets_cache_ttl: int | None = ...
    secrets_cache_max_size: int | None = ...
    strict_cli_compat: bool = ...
    extra_args: Sequence[str] | None = ...
    def validate(self, *, for_managed_tracking: bool) -> None: ...
