// Run 143 — provider binary output is a path-free candidate until reader acceptance.
import fs from 'node:fs';
const src=fs.readFileSync(process.argv[2],'utf8');
const css=fs.readFileSync(process.argv[3],'utf8');
let pass=0,fail=0;
function ok(c,n){if(c)pass++;else{fail++;console.error('FAIL '+n)}}
function extract(name){
  for(const pre of ['async function ','function ']){
    const i=src.indexOf(pre+name+'('); if(i<0)continue;
    let d=0,st=false,q=null,esc=false,line=false,block=false;
    for(let j=i;j<src.length;j++){
      const c=src[j],n=src[j+1]||'';
      if(line){if(c==='\n')line=false;continue}
      if(block){if(c==='*'&&n==='/'){block=false;j++}continue}
      if(q){if(esc)esc=false;else if(c==='\\')esc=true;else if(c===q)q=null;continue}
      if(c==='/'&&n==='/'){line=true;j++;continue}
      if(c==='/'&&n==='*'){block=true;j++;continue}
      if(c==='"'||c==="'"||c==='`'){q=c;continue}
      if(c==='{'){d++;st=true}else if(c==='}'&&st&&--d===0)return src.slice(i,j+1)
    }
  }
  throw new Error('missing '+name);
}

ok(src.includes("var _PROVIDER_ARTIFACT_SERVER_CONTRACT = 'scikitplot-provider-artifact-output-v1'"),'provider output request contract is explicit');
ok(src.includes("var _PROVIDER_ARTIFACT_RECEIPT_CONTRACT = 'scikitplot-provider-artifact-output-receipt-v1'"),'provider output receipt contract is explicit');
ok(/function _zipEditProviderArtifactCapabilityParse[\s\S]*?chat_text_is_output_authority !== false[\s\S]*?resource_input_is_output_authority !== false/.test(src),'capability discovery requires chat and input-resource non-authority assertions');
ok(/function _zipEditProviderArtifactCapabilityParse[\s\S]*?generators\.length > 32/.test(src),'provider generator catalogue is bounded');
ok(/function _zipEditProviderArtifactCapabilityParse[\s\S]*?'image\/png'[\s\S]*?'audio\/wav'/.test(src),'browser accepts only bounded image/audio output MIME allowlist');
ok(/function _zipEditProviderGeneratorForEntry[\s\S]*?generator\.diagnostic===true/.test(src),'diagnostic stub generators are never normal user generation actions');
ok(/function _zipEditProviderGeneratorForEntry[\s\S]*?generator\.kind!==spec\.kind[\s\S]*?generator\.mimeTypes\.indexOf\(spec\.mime\)<0/.test(src),'generator selection requires exact kind and target MIME');
ok(/async function _zipEditStageProviderReplacement[\s\S]*?ZIP_EDIT_PROVIDER_PROMPT_REQUIRED/.test(src),'provider generation requires explicit reader instruction');
ok(/async function _zipEditStageProviderReplacement[\s\S]*?ZIP_EDIT_PROVIDER_CONSENT_REQUIRED/.test(src),'provider generation requires explicit egress consent');
ok(/async function _zipEditStageProviderReplacement[\s\S]*?contract:_PROVIDER_ARTIFACT_SERVER_CONTRACT[\s\S]*?generator_id:generator\.id[\s\S]*?mime_type:spec\.mime/.test(src),'generation request uses dedicated output schema');
ok(!/payload=\{[^}]*path:/s.test(extract('_zipEditStageProviderReplacement')),'provider generation request contains no ZIP path');
ok(!/payload=\{[^}]*archive/s.test(extract('_zipEditStageProviderReplacement')),'provider generation request contains no archive authority');
ok(/async function _zipEditStageProviderReplacement[\s\S]*?credentials:'omit'[\s\S]*?Content-Type':'application\/json'/.test(src),'browser sends only JSON prompt contract to proxy output endpoint');
ok(/async function _zipEditReadProviderArtifactBlob[\s\S]*?total>limit/.test(src),'generated response stream is hard-capped while reading');
ok(/async function _zipEditReadProviderArtifactBlob[\s\S]*?content-length[\s\S]*?length>limit/.test(src),'declared generated size is rejected before streaming when excessive');
ok(/function _zipEditProviderArtifactReceipt[\s\S]*?x-ai-artifact-contract[\s\S]*?x-ai-artifact-sha256[\s\S]*?x-ai-artifact-receipt/.test(src),'browser requires binary output contract/hash/receipt headers');
ok(/function _zipEditProviderArtifactReceipt[\s\S]*?Object\.prototype\.hasOwnProperty\.call\(doc,'path'\)/.test(src),'provider receipt carrying path authority is rejected');
ok(/function _zipEditProviderArtifactReceipt[\s\S]*?doc\.provider!==generator\.provider[\s\S]*?doc\.model!==generator\.model[\s\S]*?doc\.generator_id!==generator\.id/.test(src),'receipt binds exact provider/model/generator identity');
ok(/function _zipEditProviderArtifactReceipt[\s\S]*?doc\.output_sha256!==outputSha[\s\S]*?doc\.prompt_sha256!==promptSha/.test(src),'receipt binds exact prompt and output SHA-256');
ok(/async function _zipEditStageProviderReplacement[\s\S]*?_zipEditSha256Blob\(blob[\s\S]*?_zipEditProviderArtifactReceipt/.test(src),'browser hashes generated bytes before accepting receipt');
ok(/async function _zipEditStageProviderReplacement[\s\S]*?_extractZipEntry\(st\.job,entry[\s\S]*?_zipEditValidateBinaryBlob\(entry,original[\s\S]*?_zipEditValidateBinaryBlob\(entry,blob/.test(src),'generated candidate reuses original/replacement signature and decode validation');
ok(src.includes("source:'provider-binary',lane:'binary-provider'"),'generated candidate has distinct provider provenance lane');
ok(/async function _zipEditStageProviderReplacement[\s\S]*?provenance:receipt[\s\S]*?promptSha256:promptSha/.test(src),'staged candidate keeps bounded generation provenance');
ok(/async function _zipEditStageProviderReplacement[\s\S]*?accepted:true/.test(src),'generated candidate is staged for review without server write until final apply');
ok(src.includes('This receipt grants no ZIP path authority.'),'binary review explicitly states receipt has no path authority');
ok(src.includes('Generate with AI…'),'inventory exposes explicit provider generation action');
ok(/generate\.disabled=st\.busy \|\| !st\.caps \|\| !st\.consent[\s\S]*?!String\(st\.instruction\.value/.test(src),'generation action stays disabled without consent and prompt');
ok(/async function _zipEditApply[\s\S]*?row\.source === 'provider-binary'[\s\S]*?authorized\.push\(row\.path\)/.test(src),'provider candidate path enters authorization only from accepted browser state');
ok(/async function _zipEditApply[\s\S]*?proposal\.source==='provider-binary'[\s\S]*?provenance\.output_sha256!==sha/.test(src),'final apply re-hashes provider bytes against receipt provenance');
ok(/async function _zipEditApply[\s\S]*?provenance\.output_size[\s\S]*?provenance\.mime_type[\s\S]*?provenance\.prompt_sha256/.test(src),'final apply rechecks size MIME and prompt provenance');
ok(src.includes('Chat text and media-input capability never grant binary write authority'),'UI explicitly separates input/chat from binary output authority');
ok(src.includes('Media mN ids never enter server authorization'),'read-only model media refs remain outside write authority');
ok(/async function _openZipEditWorkflow[\s\S]*?_zipEditProviderArtifactCapabilityDiscover/.test(src),'ZIP workflow discovers output capability separately from chat/resource capability');
ok(/st\.providerArtifactCaps = results\[3\]/.test(src),'provider output capability has independent state slot');
ok(/function _closeZipEditLayer[\s\S]*?st\.providerArtifactCaps = null/.test(src),'closing workflow invalidates provider output capability state');
ok(css.includes('.ai-assistant-panel-zip-edit-proposal[data-lane="binary-provider"]'),'provider-generated candidates have distinct review styling');
ok(css.includes('.ai-assistant-panel-zip-edit-generate'),'provider generation action has explicit UI selector');
ok(src.includes('provider generation provenance'),'aggregate review attestation explicitly covers provider provenance');
ok(src.includes('No production binary-output generator is advertised by this proxy.'),'UI fails closed when no production generator is advertised');
ok(!extract('_zipEditStageProviderReplacement').includes('b64_json'),'browser never interprets chat/provider base64 conventions itself');

const capFactory=new Function(`
 var _PROVIDER_ARTIFACT_SERVER_CONTRACT='scikitplot-provider-artifact-output-v1';
 var _PROVIDER_ARTIFACT_RECEIPT_CONTRACT='scikitplot-provider-artifact-output-receipt-v1';
 ${extract('_zipEditProviderArtifactCapabilityParse')}
 return _zipEditProviderArtifactCapabilityParse;
`);
const parseCaps=capFactory();
function health(overrides={}){
 const raw={version:1,contract:'scikitplot-provider-artifact-output-v1',receipt_contract:'scikitplot-provider-artifact-output-receipt-v1',endpoint:'/v1/artifacts/provider-output',max_request_bytes:65536,max_prompt_chars:12000,max_output_bytes:67108864,chat_text_is_output_authority:false,resource_input_is_output_authority:false,generators:[{id:'openai/gpt-image-2',provider:'openai',model:'gpt-image-2',kind:'image',mime_types:['image/png','image/jpeg','image/webp'],max_output_bytes:16777216,diagnostic:false}]};
 Object.assign(raw,overrides); return {capabilities:{provider_artifact_output:raw}};
}
let caps=parseCaps(health(),'https://proxy.example');
ok(caps&&caps.endpoint==='https://proxy.example/v1/artifacts/provider-output','valid output capability resolves only under health origin');
ok(caps&&caps.generators.length===1&&caps.generators[0].mimeTypes.includes('image/png'),'valid generator catalogue is normalized');
ok(parseCaps(health({chat_text_is_output_authority:true}),'https://proxy.example')===null,'chat-text output authority claim fails capability discovery');
ok(parseCaps(health({resource_input_is_output_authority:true}),'https://proxy.example')===null,'input-resource output authority claim fails capability discovery');
ok(parseCaps(health({endpoint:'https://evil.example/out'}),'https://proxy.example')===null,'absolute/cross-origin output endpoint fails closed');
ok(parseCaps(health({generators:[{id:'x/y',provider:'x',model:'m',kind:'video',mime_types:['video/mp4'],max_output_bytes:1}]}),'https://proxy.example')===null,'unimplemented video output generator cannot be silently accepted');
ok(parseCaps(health({generators:[{id:'x/y',provider:'x',model:'m',kind:'image',mime_types:['image/gif'],max_output_bytes:1}]}),'https://proxy.example')===null,'GIF input/replacement support does not imply provider GIF output support');

const genFactory=new Function(`
 var _zipEditState={providerArtifactCaps:{generators:[
  {id:'stub/generated-png',provider:'stub',model:'fixture',kind:'image',mimeTypes:['image/png'],maxOutputBytes:10,diagnostic:true},
  {id:'openai/gpt-image-2',provider:'openai',model:'gpt-image-2',kind:'image',mimeTypes:['image/png'],maxOutputBytes:10,diagnostic:false}
 ]}};
 function _zipEditBinaryReplacementSpec(entry){return entry.spec||null;}
 ${extract('_zipEditProviderGeneratorForEntry')}
 return _zipEditProviderGeneratorForEntry;
`);
const pick=genFactory();
let g=pick({spec:{kind:'image',mime:'image/png'}});
ok(g&&g.id==='openai/gpt-image-2','normal UI skips diagnostic generator and chooses production exact match');
ok(pick({spec:{kind:'image',mime:'image/gif'}})===null,'generator selection never widens MIME authority');

console.log(`${pass} passed, ${fail} failed`); if(fail)process.exit(1);
