// Run 136 — route max_files is sanitized and enforced before multipart construction.
import fs from 'node:fs';
const src=fs.readFileSync(process.argv[2],'utf8');let pass=0,fail=0;function ok(c,n){if(c)pass++;else{fail++;console.error('FAIL '+n)}}
function extract(name){for(const pre of ['async function ','function ']){const i=src.indexOf(pre+name+'(');if(i<0)continue;let d=0,st=false,q=null,esc=false,line=false,block=false;for(let j=i;j<src.length;j++){const c=src[j],n=src[j+1]||'';if(line){if(c==='\n')line=false;continue}if(block){if(c==='*'&&n==='/'){block=false;j++}continue}if(q){if(esc)esc=false;else if(c==='\\')esc=true;else if(c===q)q=null;continue}if(c==='/'&&n==='/'){line=true;j++;continue}if(c==='/'&&n==='*'){block=true;j++;continue}if(c==='"'||c==="'"||c==='`'){q=c;continue}if(c==='{'){d++;st=true}else if(c==='}'&&st&&--d===0)return src.slice(i,j+1)}}throw new Error('missing '+name)}
const parts=['_resourceRouteConstraintsParse','_resourceTransportCapsParse','_resourceSelectedRoute','_resourceRouteCheck'].map(extract).join('\n');
const h=new Function(`var _RESOURCE_MODALITIES=['text','image','animated_image','vector_image','audio','video','document','archive','data','binary'];var _RESOURCE_ROUTES=['native','tool','extract','context','unsupported'];var _RESOURCE_AUTO_ROUTE_ORDER=['native','tool','extract','context'];var _RESOURCE_MIME_RE=/^[A-Za-z0-9!#$&^_.+*-]{1,80}\\/[A-Za-z0-9!#$&^_.+*-]{1,80}$/;function _safeInt(v,min,max,f){var n=Number(v);if(!Number.isFinite(n))return f;return Math.max(min,Math.min(max,Math.floor(n)));}${parts};return {parse:_resourceTransportCapsParse,check:_resourceRouteCheck};`)();
const MiB=1024*1024;const caps=h.parse({version:3,multipart:true,execution:'enabled',max_files:256,max_file_bytes:512*MiB,max_total_bytes:1024*MiB,models:{'openai/whisper-large-v3':{adapter:'huggingface',execution:'enabled',routes:{audio:['native']},route_constraints:{audio:{native:{max_files:1,max_file_bytes:25*MiB,mime_types:['audio/wav']}}}}}});
const spec=caps.models['openai/whisper-large-v3'].routeConstraints.audio.native;
ok(spec.maxFiles===1,'route max_files is preserved');ok(spec.maxFileBytes===25*MiB,'ASR route byte limit preserved');
let c=h.check(caps,'openai/whisper-large-v3',{modality:'audio',intent:'raw',size:1,mime_type:'audio/wav'});ok(c.supported&&c.maxFiles===1,'route check returns maxFiles authority');
const api=extract('_panelApiCall');const pre=api.indexOf('var routeCounts = Object.create(null)');const form=api.indexOf('var resourceForm = _buildResourceFormData');ok(pre>=0&&form>pre,'route-count preflight occurs before FormData');ok(api.includes("new Error('AI_RESOURCE_ROUTE_COUNT_LIMIT')"),'distinct route count diagnostic exists');ok(api.includes('routeCounts[countKey] > routeCheck.maxFiles'),'count comparison is bounded by provider route');
ok(src.includes("d.code === 'AI_RESOURCE_ROUTE_COUNT_LIMIT'"),'reader-facing safe error copy exists');
console.log(`${pass} passed, ${fail} failed`);if(fail)process.exit(1);
