# Makefile for maintenance tools

# Authors: The scikit-plots developers
# SPDX-License-Identifier: BSD-3-Clause

req:
	python ./requirements/generate_requirements.py

authors:
	python ./docs/generate_authors_table.py
