## Documentation: https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
## This workflow automates the process of publishing your Python package to TestPyPI or PyPI.

name: Publish to TestPyPI|PyPI

## Trigger the workflow manually via GitHub Actions' "workflow_dispatch".
on:
  workflow_dispatch:  # Allows manual triggering of the workflow
    inputs:
      version:  # Specify the version of the package to upload
        description: 'Version to upload to PyPI (e.g., 1.0.0)'
        required: true
      pypi_repo:  # Specify whether to publish to TestPyPI or PyPI
        description: 'Repository to upload to (testpypi or pypi)'
        default: 'testpypi'  # Default to TestPyPI for safety
        required: true
      # debug:  # Specify whether to log for debugging
      #   description: 'Debugging? (true/false)'
      #   default: 'false'  # Default to false for debugging
      #   required: false

jobs:
  publish:
    name: Publish Package to TestPyPI|PyPI
    runs-on: ubuntu-latest  # Use the latest Ubuntu virtual environment

    permissions:
      # IMPORTANT: This permission is mandatory for secure publishing
      id-token: write  # Required for trusted publishing

    ## Restrict this job to the 'publish_pypi' environment
    ## If Activated, Accessing Environment Secret for 'publish_pypi'
    # environment:
    #   publish_pypi  # Specify the environment for environment secrets
    #   url: https://pypi.org/p/<your-pypi-project-name>
    env:
      SKPLT_VERSION: ${{ github.event.inputs.version }}

    steps:
      # Step 1: Check out the code from the repository
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # Step 2: Set up the Python environment
      - name: Python Setup
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: '3.x'  # Specify the Python version

      # Step 3: Install dependencies for building and publishing
      - name: Install build dependencies
        run: |
          # Install the necessary tools for building and publishing
          # pip install --upgrade setuptools wheel build twine
          pip install -U wheelhouse_uploader pyyaml

      # # Step 4a:Build source and wheel distributions
      # - name: Build source and wheel distributions
      #   run: |
      #     # Build both source distribution (sdist) and built distribution (wheel)
      #     python -m build
      #     twine check --strict dist/*
      #     # twine upload dist/*
      #     env:
      #       TWINE_USERNAME: __token__
      #       TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}

      # Step 4b: Downloading the package
      - name: Downloading wheels and sdist from staging
        run: |
          echo "Download $SKPLT_VERSION wheels and sdist"
          python -m wheelhouse_uploader fetch \
            --version $SKPLT_VERSION \
            --local-folder dist/ \
            scikit-plots \
            https://pypi.anaconda.org/scikit-plots-wheels-staging/simple/scikit-plots/

      # - name: Check dist has the correct number of artifacts
      #   run: |
      #     python build_tools/github/check_wheels.py
          
      # Step 5a: Publish the package to TestPyPI (if selected)
      - name: Publish package distributions to TestPyPI
        if: ${{ github.event.inputs.pypi_repo == 'testpypi' }}
        uses: pypa/gh-action-pypi-publish@15c56dba361d8335944d31a2ecd17d700fc7bcbc # v1.12.2
        with:
          user: __token__
          # password: ${{ secrets.TEST_PYPI_API_TOKEN }}  # Accessing Repository Secret TestPyPI API token
          repository-url: https://test.pypi.org/legacy/
          print-hash: true

      # Step 5b: Publish the package to PyPI (if selected)
      - name: Publish package distributions to  PyPI
        if: ${{ github.event.inputs.pypi_repo == 'pypi' }}  # Run only if 'pypi' is chosen
        uses: pypa/gh-action-pypi-publish@15c56dba361d8335944d31a2ecd17d700fc7bcbc # v1.12.2
        with:
          print-hash: true