## Documentation: https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
## This workflow automates the process of publishing your Python package to TestPyPI or PyPI.

name: Upload to TestPyPI|PyPI

## Trigger the workflow manually via GitHub Actions' "workflow_dispatch".
on:
  workflow_dispatch:  # Allows manual triggering of the workflow
    inputs:
      pkg_name:  # Specify package name
        description: 'Python Lib Name'
        default: 'scikit-plots'
        required: true
      version:  # Specify the version of the package to upload
        description: 'Version for PyPI (e.g., 1.0.0)'
        default: '0.4.0.post0'
        required: true
      conda_source:  # Specify whether to conda pkg source
        description: 'Conda Pkg Source'
        default: 'scikit-plots-wheels-staging-nightly'  # Default
        required: true
      pypi_repo:  # Specify whether to publish to TestPyPI or PyPI
        description: 'Upload (test-pypi or pypi)'
        default: 'test-pypi'  # Default to TestPyPI for safety
        required: true

permissions: # Grants read-only permission to repository contents
  contents: read # to fetch code (actions/checkout)
  id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing

jobs:
  pypi-publish:
    name: Upload release to TestPyPI|PyPI
    runs-on: ubuntu-latest  # Use the latest Ubuntu virtual environment

    ## Restrict this job to the 'publish_pypi' environment
    ## If Activated, Accessing Environment Secret for 'publish_pypi'
    # environment:
    #   publish_pypi  # Specify the environment for environment secrets
    #   url: https://pypi.org/p/<your-pypi-project-name>
    env:  # Step level enviroment NAME: '', $NAME, ${{ env.NAME }}
      PKG_NAME: ${{ github.event.inputs.pkg_name }}
      SKPLT_VERSION: ${{ github.event.inputs.version }}
      CONDA_SOURCE: ${{ github.event.inputs.conda_source }}
      PYPI_REPO: ${{ github.event.inputs.pypi_repo }}

    steps:
      # Step 1: Check out the code from the repository
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # Step 2: Set up the Python environment
      - name: Python Setup
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: '3.8'  # Specify the Python version

      # Step 3: Install dependencies for building and publishing
      - name: Install build dependencies
        run: |
          # Install the necessary tools for building and publishing
          # pip install --upgrade setuptools wheel build twine
          pip install -qU wheelhouse_uploader apache-libcloud==2.2.1 pyyaml twine

      # # Step 4a:Build source and wheel distributions
      # - name: Build source and wheel distributions
      #   run: |
      #     # Build both source distribution (sdist) and built distribution (wheel)
      #     python -m build
      #     twine check --strict dist/*
      #     # twine upload dist/*
      #     env:
      #       TWINE_USERNAME: __token__
      #       TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
      
      # Step 4b: Download wheels and sdist from Anaconda
      - name: Download wheels and sdist from Anaconda staging
        if: success()
        # see https://github.com/marketplace/actions/setup-miniconda for why
        # `-el {0}` is required.
        shell: bash -el {0}
        run: |
          echo "Download $SKPLT_VERSION wheels and sdist"
          python -m wheelhouse_uploader fetch \
            --version $SKPLT_VERSION \
            --local-folder dist/ \
            scikit-plots \
            https://pypi.anaconda.org/$CONDA_SOURCE/simple/scikit-plots/
          ls -al dist/
          # Filter or delete platform-specific files as needed
          # find dist/ -type f ! -name "*.whl" -delete  # Example to delete non-wheel files

      # - name: Check dist has the correct number of artifacts
      #   run: |
      #     python build_tools/github/check_wheels.py publish-to-test-pypi.yml
          
      # Step 5a: Publish the package to TestPyPI (if selected)
      - name: Publish package distributions to TestPyPI
        if: ${{ env.PYPI_REPO == 'test-pypi' }}
        uses: pypa/gh-action-pypi-publish@15c56dba361d8335944d31a2ecd17d700fc7bcbc # v1.12.2
        with:
          # packages-dir: dist/  # default
          # user: __token__  # default name
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}  # Accessing Repository Secret TestPyPI API token
          repository-url: https://test.pypi.org/legacy/
          verify-metadata: true
          skip-existing: true
          print-hash: true
          verbose: true

      # Step 5b: Publish the package to PyPI (if selected)
      - name: Publish package distributions to  PyPI
        if: ${{ env.PYPI_REPO == 'pypi' }}  # Run only if 'pypi' is chosen
        uses: pypa/gh-action-pypi-publish@15c56dba361d8335944d31a2ecd17d700fc7bcbc # v1.12.2
        with:
          # user: __token__  # default name
          password: ${{ secrets.PYPI_API_TOKEN }}  # Accessing Repository Secret PyPI API token
          repository-url: https://pypi.org/p/$PKG_NAME
          verify-metadata: true
          skip-existing: true
          print-hash: true
          verbose: true